; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=rewrite-statepoints-for-gc,verify -rs4gc-remat-addrspace1-derived-from-base-at-alloc < %s | FileCheck %s

target triple = "arm64-apple-macosx"

declare oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @callee(i64, i64, ptr addrspace(1))
declare void @llvm.aarch64.oxcaml.trap.publish(ptr, i64, ptr)
declare { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
declare ptr @__gxx_personality_v0(...)

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_gep_rejoin(
; CHECK-LABEL: @invoke_gep_rejoin(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_gep_rejoin, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[SKIP:%.*]], label [[JOIN:%.*]], label [[TRY:%.*]]
; CHECK:       try:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ:%.*]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[OBJ]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL7:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[OBJ_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 2
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[OBJ_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[JOIN_DS:%.*]] = phi i64 [ [[DS]], [[ENTRY:%.*]] ], [ [[CALL_GCAGG]], [[NORMAL]] ], [ [[REC_GCAGG5]], [[RECOVER]] ]
; CHECK-NEXT:    [[JOIN_ALLOC:%.*]] = phi i64 [ [[ALLOC]], [[ENTRY]] ], [ [[CALL_GCAGG1]], [[NORMAL]] ], [ [[REC_GCAGG4]], [[RECOVER]] ]
; CHECK-NEXT:    [[OBJ_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[OBJ_EH_RECOVER]], [[RECOVER]] ], [ [[OBJ_RELOCATED]], [[NORMAL]] ], [ [[OBJ]], [[ENTRY]] ]
; CHECK-NEXT:    [[FIELD_ADDR_REMAT:%.*]] = getelementptr i8, ptr addrspace(1) [[OBJ_EXNROOT_SELECT]], i64 96
; CHECK-NEXT:    [[FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[FIELD_ADDR_REMAT]], align 8
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[JOIN_DS]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[JOIN_ALLOC]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
;
  i1 %skip,
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %obj)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_gep_rejoin, %recover))
  %field.addr = getelementptr i8, ptr addrspace(1) %obj, i64 96
  br i1 %skip, label %join, label %try

try:
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_ds = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %normal_alloc = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  br label %join

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  br label %join

join:
  %join_ds = phi i64 [ %ds, %entry ], [ %normal_ds, %normal ], [ %recovered_ds, %recover ]
  %join_alloc = phi i64 [ %alloc, %entry ], [ %normal_alloc, %normal ], [ %recovered_alloc, %recover ]
  %field = load ptr addrspace(1), ptr addrspace(1) %field.addr, align 8
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %join_ds, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %join_alloc, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %field, 2
  ret { i64, i64, ptr addrspace(1) } %ret2
}

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_base_equiv_rejoin(
; CHECK-LABEL: @invoke_base_equiv_rejoin(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CHOOSE:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    br label [[SETUP:%.*]]
; CHECK:       right:
; CHECK-NEXT:    br label [[SETUP]]
; CHECK:       setup:
; CHECK-NEXT:    [[SAME_BASE:%.*]] = phi ptr addrspace(1) [ [[OBJ:%.*]], [[LEFT]] ], [ [[OBJ]], [[RIGHT]] ]
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_base_equiv_rejoin, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[SKIP:%.*]], label [[JOIN:%.*]], label [[TRY:%.*]]
; CHECK:       try:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[SAME_BASE]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[SAME_BASE]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL7:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[SAME_BASE_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 2
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[SAME_BASE_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[JOIN_DS:%.*]] = phi i64 [ [[DS]], [[SETUP]] ], [ [[CALL_GCAGG]], [[NORMAL]] ], [ [[REC_GCAGG5]], [[RECOVER]] ]
; CHECK-NEXT:    [[JOIN_ALLOC:%.*]] = phi i64 [ [[ALLOC]], [[SETUP]] ], [ [[CALL_GCAGG1]], [[NORMAL]] ], [ [[REC_GCAGG4]], [[RECOVER]] ]
; CHECK-NEXT:    [[SAME_BASE_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[SAME_BASE_EH_RECOVER]], [[RECOVER]] ], [ [[SAME_BASE_RELOCATED]], [[NORMAL]] ], [ [[SAME_BASE]], [[SETUP]] ]
; CHECK-NEXT:    [[FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[SAME_BASE_EXNROOT_SELECT]], align 8
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[JOIN_DS]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[JOIN_ALLOC]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
;
  i1 %choose,
  i1 %skip,
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %obj)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  br i1 %choose, label %left, label %right

left:
  br label %setup

right:
  br label %setup

setup:
  %same.base = phi ptr addrspace(1) [ %obj, %left ], [ %obj, %right ]
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_base_equiv_rejoin, %recover))
  br i1 %skip, label %join, label %try

try:
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_ds = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %normal_alloc = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  br label %join

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  br label %join

join:
  %join_ds = phi i64 [ %ds, %setup ], [ %normal_ds, %normal ], [ %recovered_ds, %recover ]
  %join_alloc = phi i64 [ %alloc, %setup ], [ %normal_alloc, %normal ], [ %recovered_alloc, %recover ]
  %field = load ptr addrspace(1), ptr addrspace(1) %same.base, align 8
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %join_ds, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %join_alloc, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %field, 2
  ret { i64, i64, ptr addrspace(1) } %ret2
}

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_recovery_duplicate_phi_edges(
; CHECK-LABEL: @invoke_recovery_duplicate_phi_edges(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_recovery_duplicate_phi_edges, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ:%.*]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[OBJ]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL7:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[OBJ_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 2
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[OBJ_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    switch i64 [[TAG:%.*]], label [[OTHER:%.*]] [
; CHECK-NEXT:    i64 3, label [[JOIN]]
; CHECK-NEXT:    i64 61, label [[JOIN]]
; CHECK-NEXT:    ]
; CHECK:       other:
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[JOIN_DS:%.*]] = phi i64 [ [[CALL_GCAGG]], [[NORMAL]] ], [ [[REC_GCAGG5]], [[RECOVER]] ], [ [[REC_GCAGG5]], [[RECOVER]] ], [ [[REC_GCAGG5]], [[OTHER]] ]
; CHECK-NEXT:    [[JOIN_ALLOC:%.*]] = phi i64 [ [[CALL_GCAGG1]], [[NORMAL]] ], [ [[REC_GCAGG4]], [[RECOVER]] ], [ [[REC_GCAGG4]], [[RECOVER]] ], [ [[REC_GCAGG4]], [[OTHER]] ]
; CHECK-NEXT:    [[MERGED:%.*]] = phi ptr addrspace(1) [ [[OBJ_RELOCATED]], [[NORMAL]] ], [ [[OBJ_EH_RECOVER]], [[RECOVER]] ], [ [[OBJ_EH_RECOVER]], [[RECOVER]] ], [ [[OBJ_EH_RECOVER]], [[OTHER]] ]
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[JOIN_DS]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[JOIN_ALLOC]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[MERGED]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
;
  i64 %tag,
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %obj)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_recovery_duplicate_phi_edges, %recover))
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_ds = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %normal_alloc = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  br label %join

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  switch i64 %tag, label %other [
  i64 3, label %join
  i64 61, label %join
  ]

other:
  br label %join

join:
  %join_ds = phi i64 [ %normal_ds, %normal ], [ %recovered_ds, %recover ], [ %recovered_ds, %recover ], [ %recovered_ds, %other ]
  %join_alloc = phi i64 [ %normal_alloc, %normal ], [ %recovered_alloc, %recover ], [ %recovered_alloc, %recover ], [ %recovered_alloc, %other ]
  %merged = phi ptr addrspace(1) [ %obj, %normal ], [ %obj, %recover ], [ %obj, %recover ], [ %obj, %other ]
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %join_ds, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %join_alloc, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %merged, 2
  ret { i64, i64, ptr addrspace(1) } %ret2
}

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_recovery_internal_phi_use(
; CHECK-LABEL: @invoke_recovery_internal_phi_use(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CHOOSE:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    br label [[SETUP:%.*]]
; CHECK:       right:
; CHECK-NEXT:    br label [[SETUP]]
; CHECK:       setup:
; CHECK-NEXT:    [[SAME_BASE:%.*]] = phi ptr addrspace(1) [ [[OBJ:%.*]], [[LEFT]] ], [ [[OBJ]], [[RIGHT]] ]
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_recovery_internal_phi_use, [[RECOVER:%.*]]))
; CHECK-NEXT:    br label [[TRY:%.*]]
; CHECK:       try:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[SAME_BASE]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[SAME_BASE]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL7:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[SAME_BASE_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 2
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[SAME_BASE_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    br i1 [[WHICH:%.*]], label [[RECOVER_LEFT:%.*]], label [[RECOVER_RIGHT:%.*]]
; CHECK:       recover.left:
; CHECK-NEXT:    br label [[RECOVER_JOIN:%.*]]
; CHECK:       recover.right:
; CHECK-NEXT:    br label [[RECOVER_JOIN]]
; CHECK:       recover.join:
; CHECK-NEXT:    [[RECOVERED_PTR:%.*]] = phi ptr addrspace(1) [ [[SAME_BASE_EH_RECOVER]], [[RECOVER_LEFT]] ], [ [[SAME_BASE_EH_RECOVER]], [[RECOVER_RIGHT]] ]
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[JOIN_DS:%.*]] = phi i64 [ [[CALL_GCAGG]], [[NORMAL]] ], [ [[REC_GCAGG5]], [[RECOVER_JOIN]] ]
; CHECK-NEXT:    [[JOIN_ALLOC:%.*]] = phi i64 [ [[CALL_GCAGG1]], [[NORMAL]] ], [ [[REC_GCAGG4]], [[RECOVER_JOIN]] ]
; CHECK-NEXT:    [[MERGED:%.*]] = phi ptr addrspace(1) [ [[SAME_BASE_RELOCATED]], [[NORMAL]] ], [ [[RECOVERED_PTR]], [[RECOVER_JOIN]] ]
; CHECK-NEXT:    [[FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[MERGED]], align 8
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[JOIN_DS]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[JOIN_ALLOC]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
;
  i1 %choose,
  i1 %which,
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %obj)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  br i1 %choose, label %left, label %right

left:
  br label %setup

right:
  br label %setup

setup:
  %same.base = phi ptr addrspace(1) [ %obj, %left ], [ %obj, %right ]
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_recovery_internal_phi_use, %recover))
  br label %try

try:
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_ds = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %normal_alloc = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  br label %join

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  br i1 %which, label %recover.left, label %recover.right

recover.left:
  br label %recover.join

recover.right:
  br label %recover.join

recover.join:
  %recovered.ptr = phi ptr addrspace(1) [ %same.base, %recover.left ], [ %same.base, %recover.right ]
  br label %join

join:
  %join_ds = phi i64 [ %normal_ds, %normal ], [ %recovered_ds, %recover.join ]
  %join_alloc = phi i64 [ %normal_alloc, %normal ], [ %recovered_alloc, %recover.join ]
  %merged = phi ptr addrspace(1) [ %same.base, %normal ], [ %recovered.ptr, %recover.join ]
  %field = load ptr addrspace(1), ptr addrspace(1) %merged, align 8
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %join_ds, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %join_alloc, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %field, 2
  ret { i64, i64, ptr addrspace(1) } %ret2
}

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_base_gep_rejoin(
; CHECK-LABEL: @invoke_base_gep_rejoin(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[OBJ:%.*]] = getelementptr i8, ptr addrspace(1) [[CHUNK:%.*]], i64 40, !is_base_value !0
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_base_gep_rejoin, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[SKIP:%.*]], label [[JOIN:%.*]], label [[TRY:%.*]]
; CHECK:       try:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[OBJ]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL7:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[OBJ_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL7]], 2
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[OBJ_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[JOIN_DS:%.*]] = phi i64 [ [[DS]], [[ENTRY:%.*]] ], [ [[CALL_GCAGG]], [[NORMAL]] ], [ [[REC_GCAGG5]], [[RECOVER]] ]
; CHECK-NEXT:    [[JOIN_ALLOC:%.*]] = phi i64 [ [[ALLOC]], [[ENTRY]] ], [ [[CALL_GCAGG1]], [[NORMAL]] ], [ [[REC_GCAGG4]], [[RECOVER]] ]
; CHECK-NEXT:    [[OBJ_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[OBJ_EH_RECOVER]], [[RECOVER]] ], [ [[OBJ_RELOCATED]], [[NORMAL]] ], [ [[OBJ]], [[ENTRY]] ]
; CHECK-NEXT:    [[FIELD_ADDR_REMAT:%.*]] = getelementptr i8, ptr addrspace(1) [[OBJ_EXNROOT_SELECT]], i64 8
; CHECK-NEXT:    [[FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[FIELD_ADDR_REMAT]], align 8
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[JOIN_DS]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[JOIN_ALLOC]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
;
  i1 %skip,
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %chunk)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  %obj = getelementptr i8, ptr addrspace(1) %chunk, i64 40, !is_base_value !0
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_base_gep_rejoin, %recover))
  %field.addr = getelementptr i8, ptr addrspace(1) %obj, i64 8
  br i1 %skip, label %join, label %try

try:
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_ds = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %normal_alloc = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  br label %join

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  br label %join

join:
  %join_ds = phi i64 [ %ds, %entry ], [ %normal_ds, %normal ], [ %recovered_ds, %recover ]
  %join_alloc = phi i64 [ %alloc, %entry ], [ %normal_alloc, %normal ], [ %recovered_alloc, %recover ]
  %field = load ptr addrspace(1), ptr addrspace(1) %field.addr, align 8
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %join_ds, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %join_alloc, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %field, 2
  ret { i64, i64, ptr addrspace(1) } %ret2
}

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_inttoptr_derived_rejoin(
; CHECK-LABEL: @invoke_inttoptr_derived_rejoin(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_inttoptr_derived_rejoin, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[OBJ_INT:%.*]] = ptrtoint ptr addrspace(1) [[OBJ:%.*]] to i64
; CHECK-NEXT:    [[FIELD_INT:%.*]] = add i64 [[OBJ_INT]], 96
; CHECK-NEXT:    [[FIELD_ADDR:%.*]] = inttoptr i64 [[FIELD_INT]] to ptr addrspace(1)
; CHECK-NEXT:    br i1 [[SKIP:%.*]], label [[JOIN:%.*]], label [[TRY:%.*]]
; CHECK:       try:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[OBJ]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL11:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[OBJ_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL11]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL11]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL11]], 2
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[OBJ_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[STATEPOINT_TOKEN12:%.*]] = call oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[REC_GCAGG5]], i64 [[REC_GCAGG4]], ptr addrspace(1) [[OBJ_EH_RECOVER]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ_EH_RECOVER]]) ]
; CHECK-NEXT:    [[RECOVER_CALL13:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN12]])
; CHECK-NEXT:    [[OBJ_EH_RECOVER_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN12]], i32 0, i32 0)
; CHECK-NEXT:    [[RECOVER_CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[RECOVER_CALL13]], 0
; CHECK-NEXT:    [[RECOVER_CALL_GCAGG6:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[RECOVER_CALL13]], 1
; CHECK-NEXT:    [[RECOVER_CALL_GCAGG7:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[RECOVER_CALL13]], 2
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[JOIN_DS:%.*]] = phi i64 [ [[DS]], [[ENTRY:%.*]] ], [ [[CALL_GCAGG]], [[NORMAL]] ], [ [[RECOVER_CALL_GCAGG]], [[RECOVER]] ]
; CHECK-NEXT:    [[JOIN_ALLOC:%.*]] = phi i64 [ [[ALLOC]], [[ENTRY]] ], [ [[CALL_GCAGG1]], [[NORMAL]] ], [ [[RECOVER_CALL_GCAGG6]], [[RECOVER]] ]
; CHECK-NEXT:    [[OBJ_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[OBJ_EH_RECOVER_RELOCATED]], [[RECOVER]] ], [ [[OBJ_RELOCATED]], [[NORMAL]] ], [ [[OBJ]], [[ENTRY]] ]
; CHECK-NEXT:    [[OBJ_INT_REMAT:%.*]] = ptrtoint ptr addrspace(1) [[OBJ_EXNROOT_SELECT]] to i64
; CHECK-NEXT:    [[FIELD_INT_REMAT:%.*]] = add i64 [[OBJ_INT_REMAT]], 96
; CHECK-NEXT:    [[FIELD_ADDR_REMAT:%.*]] = inttoptr i64 [[FIELD_INT_REMAT]] to ptr addrspace(1)
; CHECK-NEXT:    [[STATEPOINT_TOKEN14:%.*]] = call oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[JOIN_DS]], i64 [[JOIN_ALLOC]], ptr addrspace(1) [[OBJ_EXNROOT_SELECT]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ_EXNROOT_SELECT]]) ]
; CHECK-NEXT:    [[POST15:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN14]])
; CHECK-NEXT:    [[OBJ_EXNROOT_SELECT_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN14]], i32 0, i32 0)
; CHECK-NEXT:    [[OBJ_INT_REMAT_REMAT:%.*]] = ptrtoint ptr addrspace(1) [[OBJ_EXNROOT_SELECT_RELOCATED]] to i64
; CHECK-NEXT:    [[FIELD_INT_REMAT_REMAT:%.*]] = add i64 [[OBJ_INT_REMAT_REMAT]], 96
; CHECK-NEXT:    [[FIELD_ADDR_REMAT_REMAT:%.*]] = inttoptr i64 [[FIELD_INT_REMAT_REMAT]] to ptr addrspace(1)
; CHECK-NEXT:    [[POST_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[POST15]], 0
; CHECK-NEXT:    [[POST_GCAGG8:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[POST15]], 1
; CHECK-NEXT:    [[POST_GCAGG9:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[POST15]], 2
; CHECK-NEXT:    [[FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[FIELD_ADDR_REMAT_REMAT]], align 8
; CHECK-NEXT:    [[BASE_FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[OBJ_EXNROOT_SELECT_RELOCATED]], align 8
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[POST_GCAGG]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[POST_GCAGG8]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
;
  i1 %skip,
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %obj)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_inttoptr_derived_rejoin, %recover))
  %obj.int = ptrtoint ptr addrspace(1) %obj to i64
  %field.int = add i64 %obj.int, 96
  %field.addr = inttoptr i64 %field.int to ptr addrspace(1)
  br i1 %skip, label %join, label %try

try:
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_ds = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %normal_alloc = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  br label %join

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  %recover_call = call oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %recovered_ds, i64 %recovered_alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  %recover_ds2 = extractvalue { i64, i64, ptr addrspace(1) } %recover_call, 0
  %recover_alloc2 = extractvalue { i64, i64, ptr addrspace(1) } %recover_call, 1
  br label %join

join:
  %join_ds = phi i64 [ %ds, %entry ], [ %normal_ds, %normal ], [ %recover_ds2, %recover ]
  %join_alloc = phi i64 [ %alloc, %entry ], [ %normal_alloc, %normal ], [ %recover_alloc2, %recover ]
  %post = call oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %join_ds, i64 %join_alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  %post_ds = extractvalue { i64, i64, ptr addrspace(1) } %post, 0
  %post_alloc = extractvalue { i64, i64, ptr addrspace(1) } %post, 1
  %field = load ptr addrspace(1), ptr addrspace(1) %field.addr, align 8
  %base.field = load ptr addrspace(1), ptr addrspace(1) %obj, align 8
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %post_ds, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %post_alloc, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %field, 2
  ret { i64, i64, ptr addrspace(1) } %ret2
}

!0 = !{}
