; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=rewrite-statepoints-for-gc,verify < %s | FileCheck %s

target triple = "arm64-apple-macosx"

declare oxcaml_nofpcc void @callee_v(i64, i64, ptr addrspace(1))
declare oxcaml_nofpcc void @callee_w(i64, i64, ptr addrspace(1))
declare oxcaml_nofpcc void @leaf_callee(i64, i64, ptr addrspace(1)) #0
declare void @use(ptr addrspace(1))
declare void @use2(ptr addrspace(1), ptr addrspace(1))
declare void @use_vec(<2 x ptr addrspace(1)>)
declare void @llvm.aarch64.oxcaml.trap.publish(ptr, i64, ptr)
declare { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
declare ptr @personality(...)

; CASE 26: case26_unreachable_recovery_uses_alloca_fallback
define oxcaml_nofpcc void @case26_unreachable_recovery_uses_alloca_fallback(ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case26_unreachable_recovery_uses_alloca_fallback(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr inttoptr (i32 1 to ptr))
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case26_unreachable_recovery_uses_alloca_fallback, %recover))
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 01: case01_handler_live_direct
define oxcaml_nofpcc void @case01_handler_live_direct(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case01_handler_live_direct(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case01_handler_live_direct, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case01_handler_live_direct, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 24: case24_partially_overlapping_phi_roots
define oxcaml_nofpcc void @case24_partially_overlapping_phi_roots(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b, ptr addrspace(1) %c) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case24_partially_overlapping_phi_roots(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case24_partially_overlapping_phi_roots, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]], i32 0, i32 1, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL_LEFT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_left:
; CHECK-NEXT:    ret void
; CHECK:       right:
; CHECK-NEXT:    [[STATEPOINT_TOKEN7:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[B:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[B]], i32 0, i32 1, ptr addrspace(1) [[C:%.*]]) ]
; CHECK-NEXT:    to label [[NORMAL_RIGHT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_right:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[P_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[Q_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 1), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN8:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1), ptr addrspace(1))) @use2, i32 2, i32 0, ptr addrspace(1) [[P_EH_RECOVER]], ptr addrspace(1) [[Q_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case24_partially_overlapping_phi_roots, %recover))
  br i1 %cond, label %left, label %right
left:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal_left unwind label %recover
normal_left:
  ret void
right:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %b)
  to label %normal_right unwind label %recover
normal_right:
  ret void
recover:
  %p = phi ptr addrspace(1) [ %a, %left ], [ %b, %right ]
  %q = phi ptr addrspace(1) [ %a, %left ], [ %c, %right ]
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use2(ptr addrspace(1) %p, ptr addrspace(1) %q)
  ret void
}

; CASE 23: case23_handler_live_vector_stays_explicit_slot
define oxcaml_nofpcc void @case23_handler_live_vector_stays_explicit_slot(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, <2 x ptr addrspace(1)> %v) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case23_handler_live_vector_stays_explicit_slot(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[V_EXNROOT:%.*]] = alloca <2 x ptr addrspace(1)>, align 16
; CHECK-NEXT:    store volatile <2 x ptr addrspace(1)> <ptr addrspace(1) inttoptr (i64 1 to ptr addrspace(1)), ptr addrspace(1) inttoptr (i64 1 to ptr addrspace(1))>, ptr [[V_EXNROOT]], align 16
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case23_handler_live_vector_stays_explicit_slot, [[RECOVER:%.*]]))
; CHECK-NEXT:    store volatile <2 x ptr addrspace(1)> [[V:%.*]], ptr [[V_EXNROOT]], align 16
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr [[V_EXNROOT]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[V_EXNROOT_LOAD:%.*]] = load volatile <2 x ptr addrspace(1)>, ptr [[V_EXNROOT]], align 16
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN4:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (<2 x ptr addrspace(1)>)) @use_vec, i32 1, i32 0, <2 x ptr addrspace(1)> [[V_EXNROOT_LOAD]], i32 0, i32 0) [ "gc-live"(ptr [[V_EXNROOT]]) ]
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case23_handler_live_vector_stays_explicit_slot, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use_vec(<2 x ptr addrspace(1)> %v)
  ret void
}

; CASE 25: case25_skipped_invoke_keeps_explicit_slot
define oxcaml_nofpcc void @case25_skipped_invoke_keeps_explicit_slot(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case25_skipped_invoke_keeps_explicit_slot(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[HANDLER_EXNROOT:%.*]] = alloca ptr addrspace(1), align 8
; CHECK-NEXT:    store volatile ptr addrspace(1) inttoptr (i64 1 to ptr addrspace(1)), ptr [[HANDLER_EXNROOT]], align 8
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case25_skipped_invoke_keeps_explicit_slot, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    store volatile ptr addrspace(1) [[A:%.*]], ptr [[HANDLER_EXNROOT]], align 8
; CHECK-NEXT:    invoke oxcaml_nofpcc void @leaf_callee(i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A]])
; CHECK-NEXT:    to label [[NORMAL_LEFT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_left:
; CHECK-NEXT:    ret void
; CHECK:       right:
; CHECK-NEXT:    store volatile ptr addrspace(1) [[B:%.*]], ptr [[HANDLER_EXNROOT]], align 8
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[B]], i32 0, i32 0) [ "gc-live"(ptr [[HANDLER_EXNROOT]]) ]
; CHECK-NEXT:    to label [[NORMAL_RIGHT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_right:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[HANDLER_EXNROOT_LOAD:%.*]] = load volatile ptr addrspace(1), ptr [[HANDLER_EXNROOT]], align 8
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN4:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[HANDLER_EXNROOT_LOAD]], i32 0, i32 0) [ "gc-live"(ptr [[HANDLER_EXNROOT]]) ]
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case25_skipped_invoke_keeps_explicit_slot, %recover))
  br i1 %cond, label %left, label %right
left:
  invoke oxcaml_nofpcc void @leaf_callee(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal_left unwind label %recover
normal_left:
  ret void
right:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %b)
  to label %normal_right unwind label %recover
normal_right:
  ret void
recover:
  %handler = phi ptr addrspace(1) [ %a, %left ], [ %b, %right ]
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %handler)
  ret void
}

attributes #0 = { "gc-leaf-function" }

; CASE 02: case02_handler_phi_two_invokes_diff
define oxcaml_nofpcc void @case02_handler_phi_two_invokes_diff(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case02_handler_phi_two_invokes_diff(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case02_handler_phi_two_invokes_diff, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL_LEFT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_left:
; CHECK-NEXT:    ret void
; CHECK:       right:
; CHECK-NEXT:    [[STATEPOINT_TOKEN7:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_w, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[B:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[B]]) ]
; CHECK-NEXT:    to label [[NORMAL_RIGHT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_right:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[HANDLER_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN8:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[HANDLER_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case02_handler_phi_two_invokes_diff, %recover))
  br i1 %cond, label %left, label %right
left:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal_left unwind label %recover
normal_left:
  ret void
right:
  invoke oxcaml_nofpcc void @callee_w(i64 %ds, i64 %alloc, ptr addrspace(1) %b)
  to label %normal_right unwind label %recover
normal_right:
  ret void
recover:
  %handler = phi ptr addrspace(1) [ %a, %left ], [ %b, %right ]
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %handler)
  ret void
}

; CASE 03: case03_handler_phi_two_invokes_same
define oxcaml_nofpcc void @case03_handler_phi_two_invokes_same(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case03_handler_phi_two_invokes_same(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case03_handler_phi_two_invokes_same, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[AFTER1:%.*]] unwind label [[RECOVER]]
; CHECK:       after1:
; CHECK-NEXT:    [[A_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[STATEPOINT_TOKEN7:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_w, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[A_RELOCATED]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A_RELOCATED]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[HANDLER_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN8:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[HANDLER_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case03_handler_phi_two_invokes_same, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %after1 unwind label %recover
after1:
  invoke oxcaml_nofpcc void @callee_w(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %handler = phi ptr addrspace(1) [ %a, %entry ], [ %a, %after1 ]
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %handler)
  ret void
}

; CASE 04: case04_handler_phi_three_invokes
define oxcaml_nofpcc void @case04_handler_phi_three_invokes(i64 %tag, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b, ptr addrspace(1) %c) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case04_handler_phi_three_invokes(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case04_handler_phi_three_invokes, [[RECOVER:%.*]]))
; CHECK-NEXT:    switch i64 [[TAG:%.*]], label [[LEFT:%.*]] [
; CHECK-NEXT:    i64 1, label [[MIDDLE:%.*]]
; CHECK-NEXT:    i64 2, label [[RIGHT:%.*]]
; CHECK-NEXT:    ]
; CHECK:       left:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL_LEFT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_left:
; CHECK-NEXT:    ret void
; CHECK:       middle:
; CHECK-NEXT:    [[STATEPOINT_TOKEN7:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_w, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[B:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[B]]) ]
; CHECK-NEXT:    to label [[NORMAL_MIDDLE:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_middle:
; CHECK-NEXT:    ret void
; CHECK:       right:
; CHECK-NEXT:    [[STATEPOINT_TOKEN10:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[C:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[C]]) ]
; CHECK-NEXT:    to label [[NORMAL_RIGHT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_right:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[HANDLER_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN11:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[HANDLER_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case04_handler_phi_three_invokes, %recover))
  switch i64 %tag, label %left [ i64 1, label %middle i64 2, label %right ]
left:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal_left unwind label %recover
normal_left:
  ret void
middle:
  invoke oxcaml_nofpcc void @callee_w(i64 %ds, i64 %alloc, ptr addrspace(1) %b)
  to label %normal_middle unwind label %recover
normal_middle:
  ret void
right:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %c)
  to label %normal_right unwind label %recover
normal_right:
  ret void
recover:
  %handler = phi ptr addrspace(1) [ %a, %left ], [ %b, %middle ], [ %c, %right ]
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %handler)
  ret void
}

; CASE 05: case05_split_lpad_phi
define oxcaml_nofpcc void @case05_split_lpad_phi(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case05_split_lpad_phi(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case05_split_lpad_phi, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL_LEFT:%.*]] unwind label [[LEFT_LPAD:%.*]]
; CHECK:       normal_left:
; CHECK-NEXT:    ret void
; CHECK:       right:
; CHECK-NEXT:    [[STATEPOINT_TOKEN7:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_w, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[B:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[B]]) ]
; CHECK-NEXT:    to label [[NORMAL_RIGHT:%.*]] unwind label [[RIGHT_LPAD:%.*]]
; CHECK:       normal_right:
; CHECK-NEXT:    ret void
; CHECK:       left_lpad:
; CHECK-NEXT:    [[LEFT_LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    br label [[RECOVER]]
; CHECK:       right_lpad:
; CHECK-NEXT:    [[RIGHT_LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    br label [[RECOVER]]
; CHECK:       recover:
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[HANDLER_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN8:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[HANDLER_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case05_split_lpad_phi, %recover))
  br i1 %cond, label %left, label %right
left:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal_left unwind label %left_lpad
normal_left:
  ret void
right:
  invoke oxcaml_nofpcc void @callee_w(i64 %ds, i64 %alloc, ptr addrspace(1) %b)
  to label %normal_right unwind label %right_lpad
normal_right:
  ret void
left_lpad:
  %left_lp = landingpad token cleanup
  br label %recover
right_lpad:
  %right_lp = landingpad token cleanup
  br label %recover
recover:
  %handler = phi ptr addrspace(1) [ %a, %left_lpad ], [ %b, %right_lpad ]
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %handler)
  ret void
}

; CASE 06: case06_handler_live_derived_gep
define oxcaml_nofpcc void @case06_handler_live_derived_gep(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case06_handler_live_derived_gep(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case06_handler_live_derived_gep, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[FIELD_REMAT:%.*]] = getelementptr i8, ptr addrspace(1) [[A_EH_RECOVER]], i64 8
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[FIELD_REMAT]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case06_handler_live_derived_gep, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %field = getelementptr i8, ptr addrspace(1) %a, i64 8
  call void @use(ptr addrspace(1) %field)
  ret void
}

; CASE 07: case07_handler_live_freeze
define oxcaml_nofpcc void @case07_handler_live_freeze(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case07_handler_live_freeze(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case07_handler_live_freeze, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[F:%.*]] = freeze ptr addrspace(1) [[A_EH_RECOVER]]
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[F]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case07_handler_live_freeze, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %f = freeze ptr addrspace(1) %a
  call void @use(ptr addrspace(1) %f)
  ret void
}

; CASE 08: case08_boundary_switch_two_edges
define oxcaml_nofpcc void @case08_boundary_switch_two_edges(i64 %tag, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case08_boundary_switch_two_edges(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case08_boundary_switch_two_edges, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[A_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    switch i64 [[TAG:%.*]], label [[OTHER:%.*]] [
; CHECK-NEXT:    i64 1, label [[JOIN]]
; CHECK-NEXT:    i64 2, label [[JOIN]]
; CHECK-NEXT:    ]
; CHECK:       other:
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[A_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[A_EH_RECOVER]], [[OTHER]] ], [ [[A_EH_RECOVER]], [[RECOVER]] ], [ [[A_EH_RECOVER]], [[RECOVER]] ], [ [[A_RELOCATED]], [[NORMAL]] ]
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EXNROOT_SELECT]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case08_boundary_switch_two_edges, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  br label %join
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  switch i64 %tag, label %other [ i64 1, label %join i64 2, label %join ]
other:
  br label %join
join:
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 09: case09_boundary_switch_three_edges
define oxcaml_nofpcc void @case09_boundary_switch_three_edges(i64 %tag, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case09_boundary_switch_three_edges(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case09_boundary_switch_three_edges, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[A_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[A_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[A_EH_RECOVER]], [[RECOVER]] ], [ [[A_RELOCATED]], [[NORMAL]] ]
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EXNROOT_SELECT]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case09_boundary_switch_three_edges, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  br label %join
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  switch i64 %tag, label %join [ i64 1, label %join i64 2, label %join i64 3, label %join ]
join:
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 10: case10_boundary_cond_same_successor
define oxcaml_nofpcc void @case10_boundary_cond_same_successor(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case10_boundary_cond_same_successor(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case10_boundary_cond_same_successor, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[A_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[A_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[A_EH_RECOVER]], [[RECOVER]] ], [ [[A_RELOCATED]], [[NORMAL]] ]
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EXNROOT_SELECT]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case10_boundary_cond_same_successor, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  br label %join
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  br i1 %cond, label %join, label %join
join:
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 11: case11_boundary_via_trampoline
define oxcaml_nofpcc void @case11_boundary_via_trampoline(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case11_boundary_via_trampoline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case11_boundary_via_trampoline, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[A_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[TRAMP1:%.*]], label [[TRAMP2:%.*]]
; CHECK:       tramp1:
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       tramp2:
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[A_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[A_EH_RECOVER]], [[TRAMP2]] ], [ [[A_EH_RECOVER]], [[TRAMP1]] ], [ [[A_RELOCATED]], [[NORMAL]] ]
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EXNROOT_SELECT]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case11_boundary_via_trampoline, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  br label %join
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  br i1 %cond, label %tramp1, label %tramp2
tramp1:
  br label %join
tramp2:
  br label %join
join:
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 12: case12_boundary_local_loaded_value
define oxcaml_nofpcc void @case12_boundary_local_loaded_value(i1 %retry, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case12_boundary_local_loaded_value(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case12_boundary_local_loaded_value, [[RECOVER:%.*]]))
; CHECK-NEXT:    br label [[TRY:%.*]]
; CHECK:       try:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr addrspace(1) [ [[A:%.*]], [[ENTRY:%.*]] ], [ [[NEXT_EH_RECOVER:%.*]], [[RETRY_BLOCK:%.*]] ]
; CHECK-NEXT:    [[ADDR_REMAT:%.*]] = getelementptr i8, ptr addrspace(1) [[CUR]], i64 8
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[ADDR_REMAT]], align 8
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[NEXT]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[NEXT]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[NEXT_EH_RECOVER]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    br i1 [[RETRY:%.*]], label [[RETRY_BLOCK]], label [[EXIT:%.*]]
; CHECK:       retry_block:
; CHECK-NEXT:    br label [[TRY]]
; CHECK:       exit:
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[NEXT_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case12_boundary_local_loaded_value, %recover))
  br label %try
try:
  %cur = phi ptr addrspace(1) [ %a, %entry ], [ %next, %retry_block ]
  %addr = getelementptr i8, ptr addrspace(1) %cur, i64 8
  %next = load ptr addrspace(1), ptr addrspace(1) %addr, align 8
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %next)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  br i1 %retry, label %retry_block, label %exit
retry_block:
  br label %try
exit:
  call void @use(ptr addrspace(1) %next)
  ret void
}

; CASE 13: case13_two_roots_same_handler
define oxcaml_nofpcc void @case13_two_roots_same_handler(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case13_two_roots_same_handler(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case13_two_roots_same_handler, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]], i32 0, i32 1, ptr addrspace(1) [[B:%.*]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[B_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 1), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1), ptr addrspace(1))) @use2, i32 2, i32 0, ptr addrspace(1) [[A_EH_RECOVER]], ptr addrspace(1) [[B_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case13_two_roots_same_handler, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use2(ptr addrspace(1) %a, ptr addrspace(1) %b)
  ret void
}

; CASE 14: case14_same_root_two_uses
define oxcaml_nofpcc void @case14_same_root_two_uses(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case14_same_root_two_uses(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case14_same_root_two_uses, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EH_RECOVER]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A_EH_RECOVER]]) ]
; CHECK-NEXT:    [[A_EH_RECOVER_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN5]], i32 0, i32 0)
; CHECK-NEXT:    [[STATEPOINT_TOKEN6:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EH_RECOVER_RELOCATED]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case14_same_root_two_uses, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %a)
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 15: case15_base_equiv_ptrtoint_roundtrip
define oxcaml_nofpcc void @case15_base_equiv_ptrtoint_roundtrip(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case15_base_equiv_ptrtoint_roundtrip(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case15_base_equiv_ptrtoint_roundtrip, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[I:%.*]] = ptrtoint ptr addrspace(1) [[A_EH_RECOVER]] to i64
; CHECK-NEXT:    [[ROUND:%.*]] = inttoptr i64 [[I]] to ptr addrspace(1)
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[ROUND]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case15_base_equiv_ptrtoint_roundtrip, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %i = ptrtoint ptr addrspace(1) %a to i64
  %round = inttoptr i64 %i to ptr addrspace(1)
  call void @use(ptr addrspace(1) %round)
  ret void
}

; CASE 16: case16_int_arithmetic_derived
define oxcaml_nofpcc void @case16_int_arithmetic_derived(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case16_int_arithmetic_derived(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case16_int_arithmetic_derived, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[I:%.*]] = ptrtoint ptr addrspace(1) [[A_EH_RECOVER]] to i64
; CHECK-NEXT:    [[J:%.*]] = add i64 [[I]], 8
; CHECK-NEXT:    [[DERIVED:%.*]] = inttoptr i64 [[J]] to ptr addrspace(1)
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[DERIVED]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case16_int_arithmetic_derived, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %i = ptrtoint ptr addrspace(1) %a to i64
  %j = add i64 %i, 8
  %derived = inttoptr i64 %j to ptr addrspace(1)
  call void @use(ptr addrspace(1) %derived)
  ret void
}

; CASE 17: case17_two_independent_recover_uses
define oxcaml_nofpcc void @case17_two_independent_recover_uses(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case17_two_independent_recover_uses(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case17_two_independent_recover_uses, [[RECOVER_LEFT:%.*]]))
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL_LEFT:%.*]] unwind label [[RECOVER_LEFT]]
; CHECK:       normal_left:
; CHECK-NEXT:    ret void
; CHECK:       right:
; CHECK-NEXT:    [[STATEPOINT_TOKEN10:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_w, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[B:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 1, i32 0, ptr addrspace(1) [[B]]) ]
; CHECK-NEXT:    to label [[NORMAL_RIGHT:%.*]] unwind label [[RECOVER_RIGHT:%.*]]
; CHECK:       normal_right:
; CHECK-NEXT:    ret void
; CHECK:       recover_left:
; CHECK-NEXT:    [[LP_LEFT:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC_LEFT:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_LEFT_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_LEFT]], 0
; CHECK-NEXT:    [[REC_LEFT_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_LEFT]], 1
; CHECK-NEXT:    [[REC_LEFT_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_LEFT]], 2
; CHECK-NEXT:    [[REC_LEFT_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_LEFT]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN11:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
; CHECK:       recover_right:
; CHECK-NEXT:    [[LP_RIGHT:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC_RIGHT:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[B_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 1, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_RIGHT_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_RIGHT]], 0
; CHECK-NEXT:    [[REC_RIGHT_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_RIGHT]], 1
; CHECK-NEXT:    [[REC_RIGHT_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_RIGHT]], 2
; CHECK-NEXT:    [[REC_RIGHT_GCAGG6:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC_RIGHT]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN12:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[B_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case17_two_independent_recover_uses, %recover_left))
  br i1 %cond, label %left, label %right
left:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal_left unwind label %recover_left
normal_left:
  ret void
right:
  invoke oxcaml_nofpcc void @callee_w(i64 %ds, i64 %alloc, ptr addrspace(1) %b)
  to label %normal_right unwind label %recover_right
normal_right:
  ret void
recover_left:
  %lp_left = landingpad token cleanup
  %rec_left = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %a)
  ret void
recover_right:
  %lp_right = landingpad token cleanup
  %rec_right = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %b)
  ret void
}

; CASE 18: case18_nested_boundary_two_joins
define oxcaml_nofpcc void @case18_nested_boundary_two_joins(i64 %tag, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case18_nested_boundary_two_joins(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case18_nested_boundary_two_joins, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[A_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    br label [[JOIN2:%.*]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    br label [[JOIN1:%.*]]
; CHECK:       join1:
; CHECK-NEXT:    br label [[JOIN2]]
; CHECK:       join2:
; CHECK-NEXT:    [[A_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[A_EH_RECOVER]], [[JOIN1]] ], [ [[A_RELOCATED]], [[NORMAL]] ]
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EXNROOT_SELECT]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case18_nested_boundary_two_joins, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  br label %join2
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  switch i64 %tag, label %join1 [ i64 1, label %join1 i64 2, label %join1 ]
join1:
  br label %join2
join2:
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 19: case19_recover_phi_to_boundary
define oxcaml_nofpcc void @case19_recover_phi_to_boundary(i1 %cond, i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a, ptr addrspace(1) %b) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case19_recover_phi_to_boundary(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case19_recover_phi_to_boundary, [[RECOVER:%.*]]))
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL_LEFT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_left:
; CHECK-NEXT:    ret void
; CHECK:       right:
; CHECK-NEXT:    [[STATEPOINT_TOKEN7:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_w, i32 3, i32 0, i64 [[DS]], i64 [[ALLOC]], ptr addrspace(1) [[B:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[B]]) ]
; CHECK-NEXT:    to label [[NORMAL_RIGHT:%.*]] unwind label [[RECOVER]]
; CHECK:       normal_right:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[HANDLER_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       join:
; CHECK-NEXT:    [[STATEPOINT_TOKEN8:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[HANDLER_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case19_recover_phi_to_boundary, %recover))
  br i1 %cond, label %left, label %right
left:
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal_left unwind label %recover
normal_left:
  ret void
right:
  invoke oxcaml_nofpcc void @callee_w(i64 %ds, i64 %alloc, ptr addrspace(1) %b)
  to label %normal_right unwind label %recover
normal_right:
  ret void
recover:
  %handler = phi ptr addrspace(1) [ %a, %left ], [ %b, %right ]
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  br i1 %cond, label %join, label %join
join:
  call void @use(ptr addrspace(1) %handler)
  ret void
}

; CASE 20: case20_call_after_recover_keeps_slot_live
define oxcaml_nofpcc void @case20_call_after_recover_keeps_slot_live(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case20_call_after_recover_keeps_slot_live(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case20_call_after_recover_keeps_slot_live, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EH_RECOVER]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A_EH_RECOVER]]) ]
; CHECK-NEXT:    [[A_EH_RECOVER_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN5]], i32 0, i32 0)
; CHECK-NEXT:    [[STATEPOINT_TOKEN6:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EH_RECOVER_RELOCATED]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case20_call_after_recover_keeps_slot_live, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %a)
  call void @use(ptr addrspace(1) %a)
  ret void
}

; CASE 21: case21_same_store_program_different_logical_roots
define oxcaml_nofpcc void @case21_same_store_program_different_logical_roots(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case21_same_store_program_different_logical_roots(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case21_same_store_program_different_logical_roots, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1), ptr addrspace(1))) @use2, i32 2, i32 0, ptr addrspace(1) [[A_EH_RECOVER]], ptr addrspace(1) [[A_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case21_same_store_program_different_logical_roots, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  ret void
recover:
  %handler = phi ptr addrspace(1) [ %a, %entry ]
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use2(ptr addrspace(1) %handler, ptr addrspace(1) %a)
  ret void
}

; CASE 22: case22_normal_and_exception_use_share_root_slot
define oxcaml_nofpcc void @case22_normal_and_exception_use_share_root_slot(i64 %ds, i64 %alloc, ptr %trap, ptr addrspace(1) %a) gc "oxcaml" personality ptr @personality {
; CHECK-LABEL: @case22_normal_and_exception_use_share_root_slot(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP:%.*]], i64 1, ptr blockaddress(@case22_normal_and_exception_use_share_root_slot, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (i64, i64, ptr addrspace(1))) @callee_v, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[A:%.*]], i32 0, i32 0) [ "gc-live"(ptr addrspace(1) [[A]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[A]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[A_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[STATEPOINT_TOKEN5:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_RELOCATED]], i32 0, i32 0)
; CHECK-NEXT:    ret void
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[A_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG1:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG2:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[STATEPOINT_TOKEN6:%.*]] = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 2882400000, i32 0, ptr elementtype(void (ptr addrspace(1))) @use, i32 1, i32 0, ptr addrspace(1) [[A_EH_RECOVER]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(ptr %trap, i64 1, ptr blockaddress(@case22_normal_and_exception_use_share_root_slot, %recover))
  invoke oxcaml_nofpcc void @callee_v(i64 %ds, i64 %alloc, ptr addrspace(1) %a)
  to label %normal unwind label %recover
normal:
  call void @use(ptr addrspace(1) %a)
  ret void
recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  call void @use(ptr addrspace(1) %a)
  ret void
}
