; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=rewrite-statepoints-for-gc,verify -rs4gc-remat-addrspace1-derived-from-base-at-alloc < %s | FileCheck %s

target triple = "arm64-apple-macosx"

declare oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @callee(i64, i64, ptr addrspace(1))
declare void @llvm.aarch64.oxcaml.trap.publish(ptr, i64, ptr)
declare void @llvm.aarch64.oxcaml.push.trap(ptr)
declare { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
declare ptr @__gxx_personality_v0(...)

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_gep_handler_live(
; CHECK-LABEL: @invoke_gep_handler_live(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_gep_handler_live, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ:%.*]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[OBJ]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL8:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[OBJ_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL8]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL8]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL8]], 2
; CHECK-NEXT:    [[FIELD_ADDR_REMAT6:%.*]] = getelementptr i8, ptr addrspace(1) [[OBJ_RELOCATED]], i64 24
; CHECK-NEXT:    [[NORMAL_FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[FIELD_ADDR_REMAT6]], align 8
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[CALL_GCAGG]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[CALL_GCAGG1]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[NORMAL_FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[OBJ_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[FIELD_ADDR_REMAT:%.*]] = getelementptr i8, ptr addrspace(1) [[OBJ_EH_RECOVER]], i64 24
; CHECK-NEXT:    [[HANDLER_FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[FIELD_ADDR_REMAT]], align 8
; CHECK-NEXT:    [[RET3:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[REC_GCAGG5]], 0
; CHECK-NEXT:    [[RET4:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET3]], i64 [[REC_GCAGG4]], 1
; CHECK-NEXT:    [[RET5:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET4]], ptr addrspace(1) [[HANDLER_FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET5]]
;
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %obj)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_gep_handler_live, %recover))
  %field.addr = getelementptr i8, ptr addrspace(1) %obj, i64 24
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_field = load ptr addrspace(1), ptr addrspace(1) %field.addr, align 8
  %pair = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %alloc2 = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %pair, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %alloc2, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %normal_field, 2
  ret { i64, i64, ptr addrspace(1) } %ret2

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  %handler_field = load ptr addrspace(1), ptr addrspace(1) %field.addr, align 8
  %ret3 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %recovered_ds, 0
  %ret4 = insertvalue { i64, i64, ptr addrspace(1) } %ret3, i64 %recovered_alloc, 1
  %ret5 = insertvalue { i64, i64, ptr addrspace(1) } %ret4, ptr addrspace(1) %handler_field, 2
  ret { i64, i64, ptr addrspace(1) } %ret5
}

define oxcaml_nofpcc { i64, i64, ptr addrspace(1) } @invoke_gep_nested_recovery_trap(
; CHECK-LABEL: @invoke_gep_nested_recovery_trap(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.trap.publish(ptr [[TRAP_BLOCK:%.*]], i64 1, ptr blockaddress(@invoke_gep_nested_recovery_trap, [[RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[DS:%.*]], i64 [[ALLOC:%.*]], ptr addrspace(1) [[OBJ:%.*]], i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ]]), "oxcaml-eh-live"(i32 0, i32 0, ptr addrspace(1) [[OBJ]]) ]
; CHECK-NEXT:    to label [[NORMAL:%.*]] unwind label [[RECOVER]]
; CHECK:       normal:
; CHECK-NEXT:    [[CALL13:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN]])
; CHECK-NEXT:    [[OBJ_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    [[CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL13]], 0
; CHECK-NEXT:    [[CALL_GCAGG1:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL13]], 1
; CHECK-NEXT:    [[CALL_GCAGG2:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[CALL13]], 2
; CHECK-NEXT:    [[FIELD_ADDR_REMAT11:%.*]] = getelementptr i8, ptr addrspace(1) [[OBJ_RELOCATED]], i64 24
; CHECK-NEXT:    [[NORMAL_FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[FIELD_ADDR_REMAT11]], align 8
; CHECK-NEXT:    [[RET0:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[CALL_GCAGG]], 0
; CHECK-NEXT:    [[RET1:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET0]], i64 [[CALL_GCAGG1]], 1
; CHECK-NEXT:    [[RET2:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET1]], ptr addrspace(1) [[NORMAL_FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET2]]
; CHECK:       recover:
; CHECK-NEXT:    [[LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 0
; CHECK-NEXT:    [[REC_GCAGG3:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 1
; CHECK-NEXT:    [[REC_GCAGG4:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 2
; CHECK-NEXT:    [[REC_GCAGG5:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[REC]], 3
; CHECK-NEXT:    [[OBJ_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 0, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    br label [[NESTED:%.*]]
; CHECK:       nested:
; CHECK-NEXT:    [[OBJ_EXNROOT_SELECT:%.*]] = phi ptr addrspace(1) [ [[OBJ_EH_RECOVER]], [[RECOVER]] ]
; CHECK-NEXT:    call void @llvm.aarch64.oxcaml.push.trap(ptr blockaddress(@invoke_gep_nested_recovery_trap, [[INNER_RECOVER:%.*]]))
; CHECK-NEXT:    [[STATEPOINT_TOKEN16:%.*]] = invoke oxcaml_nofpcc token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype({ i64, i64, ptr addrspace(1) } (i64, i64, ptr addrspace(1))) @callee, i32 3, i32 0, i64 [[REC_GCAGG5]], i64 [[REC_GCAGG4]], ptr addrspace(1) inttoptr (i64 1 to ptr addrspace(1)), i32 0, i32 0) [ "deopt"(), "gc-live"(ptr addrspace(1) [[OBJ_EXNROOT_SELECT]]), "oxcaml-eh-live"(i32 1, i32 0, ptr addrspace(1) [[OBJ_EXNROOT_SELECT]]) ]
; CHECK-NEXT:    to label [[INNER_NORMAL:%.*]] unwind label [[INNER_RECOVER]]
; CHECK:       inner_normal:
; CHECK-NEXT:    [[INNER_CALL17:%.*]] = call { i64, i64, ptr addrspace(1) } @llvm.experimental.gc.result.sl_i64i64p1s(token [[STATEPOINT_TOKEN16]])
; CHECK-NEXT:    [[OBJ_EXNROOT_SELECT_RELOCATED:%.*]] = call coldcc ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token [[STATEPOINT_TOKEN16]], i32 0, i32 0)
; CHECK-NEXT:    [[INNER_CALL_GCAGG:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[INNER_CALL17]], 0
; CHECK-NEXT:    [[INNER_CALL_GCAGG6:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[INNER_CALL17]], 1
; CHECK-NEXT:    [[INNER_CALL_GCAGG7:%.*]] = extractvalue { i64, i64, ptr addrspace(1) } [[INNER_CALL17]], 2
; CHECK-NEXT:    [[FIELD_ADDR_REMAT:%.*]] = getelementptr i8, ptr addrspace(1) [[OBJ_EXNROOT_SELECT_RELOCATED]], i64 24
; CHECK-NEXT:    [[INNER_FIELD:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[FIELD_ADDR_REMAT]], align 8
; CHECK-NEXT:    [[RET3:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[INNER_CALL_GCAGG]], 0
; CHECK-NEXT:    [[RET4:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET3]], i64 [[INNER_CALL_GCAGG6]], 1
; CHECK-NEXT:    [[RET5:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET4]], ptr addrspace(1) [[INNER_FIELD]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET5]]
; CHECK:       inner_recover:
; CHECK-NEXT:    [[INNER_LP:%.*]] = landingpad token
; CHECK-NEXT:    cleanup
; CHECK-NEXT:    [[INNER_REC:%.*]] = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
; CHECK-NEXT:    [[OBJ_EXNROOT_SELECT_EH_RECOVER:%.*]] = call ptr addrspace(1) @llvm.oxcaml.gc.eh.recover(i32 1, i32 0), !oxcaml.exnroot.load !0
; CHECK-NEXT:    [[INNER_REC_GCAGG:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[INNER_REC]], 0
; CHECK-NEXT:    [[INNER_REC_GCAGG8:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[INNER_REC]], 1
; CHECK-NEXT:    [[INNER_REC_GCAGG9:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[INNER_REC]], 2
; CHECK-NEXT:    [[INNER_REC_GCAGG10:%.*]] = extractvalue { ptr addrspace(1), i64, i64, i64 } [[INNER_REC]], 3
; CHECK-NEXT:    [[RET6:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 [[INNER_REC_GCAGG10]], 0
; CHECK-NEXT:    [[RET7:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET6]], i64 [[INNER_REC_GCAGG9]], 1
; CHECK-NEXT:    [[RET8:%.*]] = insertvalue { i64, i64, ptr addrspace(1) } [[RET7]], ptr addrspace(1) [[OBJ_EXNROOT_SELECT_EH_RECOVER]], 2
; CHECK-NEXT:    ret { i64, i64, ptr addrspace(1) } [[RET8]]
;
  i64 %ds,
  i64 %alloc,
  ptr %trap_block,
  ptr addrspace(1) %obj)
  gc "oxcaml" personality ptr @__gxx_personality_v0 {
entry:
  call void @llvm.aarch64.oxcaml.trap.publish(
  ptr %trap_block,
  i64 1,
  ptr blockaddress(@invoke_gep_nested_recovery_trap, %recover))
  %field.addr = getelementptr i8, ptr addrspace(1) %obj, i64 24
  %call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %ds, i64 %alloc, ptr addrspace(1) %obj)
  "statepoint-id"="0" [ "deopt"() ]
  to label %normal unwind label %recover

normal:
  %normal_field = load ptr addrspace(1), ptr addrspace(1) %field.addr, align 8
  %pair = extractvalue { i64, i64, ptr addrspace(1) } %call, 0
  %alloc2 = extractvalue { i64, i64, ptr addrspace(1) } %call, 1
  %ret0 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %pair, 0
  %ret1 = insertvalue { i64, i64, ptr addrspace(1) } %ret0, i64 %alloc2, 1
  %ret2 = insertvalue { i64, i64, ptr addrspace(1) } %ret1, ptr addrspace(1) %normal_field, 2
  ret { i64, i64, ptr addrspace(1) } %ret2

recover:
  %lp = landingpad token cleanup
  %rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 2
  %recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %rec, 3
  br label %nested

nested:
  call void @llvm.aarch64.oxcaml.push.trap(
  ptr blockaddress(@invoke_gep_nested_recovery_trap, %inner_recover))
  %inner_call = invoke oxcaml_nofpcc { i64, i64, ptr addrspace(1) }
  @callee(i64 %recovered_ds, i64 %recovered_alloc,
  ptr addrspace(1) inttoptr (i64 1 to ptr addrspace(1)))
  "statepoint-id"="0" [ "deopt"() ]
  to label %inner_normal unwind label %inner_recover

inner_normal:
  %inner_field = load ptr addrspace(1), ptr addrspace(1) %field.addr, align 8
  %inner_pair = extractvalue { i64, i64, ptr addrspace(1) } %inner_call, 0
  %inner_alloc = extractvalue { i64, i64, ptr addrspace(1) } %inner_call, 1
  %ret3 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %inner_pair, 0
  %ret4 = insertvalue { i64, i64, ptr addrspace(1) } %ret3, i64 %inner_alloc, 1
  %ret5 = insertvalue { i64, i64, ptr addrspace(1) } %ret4, ptr addrspace(1) %inner_field, 2
  ret { i64, i64, ptr addrspace(1) } %ret5

inner_recover:
  %inner_lp = landingpad token cleanup
  %inner_rec = call { ptr addrspace(1), i64, i64, i64 } @llvm.aarch64.oxcaml.trap.recover()
  %inner_recovered_alloc = extractvalue { ptr addrspace(1), i64, i64, i64 } %inner_rec, 2
  %inner_recovered_ds = extractvalue { ptr addrspace(1), i64, i64, i64 } %inner_rec, 3
  %ret6 = insertvalue { i64, i64, ptr addrspace(1) } poison, i64 %inner_recovered_ds, 0
  %ret7 = insertvalue { i64, i64, ptr addrspace(1) } %ret6, i64 %inner_recovered_alloc, 1
  %ret8 = insertvalue { i64, i64, ptr addrspace(1) } %ret7, ptr addrspace(1) %obj, 2
  ret { i64, i64, ptr addrspace(1) } %ret8
}
