# oxsmt build entry points. smt/ is a standalone stdlib-only subproject; the
# dev loop never builds or runs the compiler (DESIGN.md §1, §3).
#
# The bare `dune` on PATH is a Jane Street dispatch wrapper that fails outside
# jane workspaces, so we pin the opam toolchain explicitly.

# OPAM_BIN: the opam 5.4.0 toolchain bin dir. Overridable (env or `make OPAM_BIN=...`)
# so this is not hard-pinned to one developer's home when CI runs off-box; the default
# is this environment's toolchain (M0-harness-hygiene).
OPAM_BIN ?= /usr/local/home/jujacobs/.opam/5.4.0/bin
DUNE := $(OPAM_BIN)/dune
export PATH := $(OPAM_BIN):$(PATH)

# Harness knobs (override on the command line, e.g. `make test SOLVER=path/to/other`).
# SOLVER defaults to the real solver CLI (tests/solver, M1-wiring): it drives the shipped
# session layer and implements the harness contract. The stub (unknown for every
# check-sat) stays buildable as a fallback / for harness plumbing tests — override
# `SOLVER=_build/default/tests/harness/stub_solver.exe` to use it.
# LOGS/STATS resolve relative to the make invocation dir (the project root).
SOLVER   ?= _build/default/tests/solver/oxsmt_cli.exe
# EVAL: the N-version model evaluator CLI (tests/eval). The harness runs it on every
# sat verdict's model before accepting (DESIGN.md §8 layer 1). A sat we cannot
# self-check is a failure, never a pass.
EVAL     ?= _build/default/tests/eval/eval_cli.exe
# LOGS/STATS resolve relative to the make invocation dir. `make` is meant to run from
# main/, where ../logs is the sibling log dir (DESIGN §11 topology). From a worktree,
# ../logs would resolve to worktrees/logs — so pass LOGS=<abs path> when running suites
# from a task worktree (M0-harness-hygiene). CI runs from main/, so the default is right.
LOGS     ?= ../logs
STATS    ?= $(LOGS)/stats
CASES    ?= tests/cases
FIXTURES ?= tests/harness/fixtures
HARNESS_ARGS := --solver $(SOLVER) --eval $(EVAL) --dir $(CASES) --dir $(FIXTURES) \
                --logs $(LOGS) --stats $(STATS)

# SAT bench corpus. Defaults to the uf50/uuf50 families (the M1 verdict-agreement
# target, solved in seconds); GLOBs at runtime and tolerates absence. Override to
# run elsewhere, e.g. `make sat-bench SAT_CORPUS=../corpora/SAT` for the whole
# tree (which includes intentionally-hard families like pigeon-hole).
SAT_CORPUS ?= ../corpora/SAT/uf50-218 ../corpora/SAT/uuf50-218

# Adversarial perf corpus (committed, generated by tests/perf/gen_perf.ml).
PERF_CASES ?= tests/perf/cases

# smtlib-corpus knob: which public corpus to smoke-parse. Default is QF_UFLIA (the target
# logic). Corpora are a sibling of main/, never in git, so ../corpora resolves from main/
# (from a worktree, override SMTLIB_CORPUS to ../../corpora/... — same caveat as LOGS).
SMTLIB_CORPUS ?= ../corpora/QF_UFLIA

# OxCaml compile check (task oxcaml-check). The shipped smt/ libraries must compile
# under Jane Street's OxCaml compiler too, not just stock OCaml — "pure OxCaml" kept
# true by test, not intention. The compiler is resolved from the boot sysdeps with no
# network (`sysdep-run -source boot -attr-path oxcaml.r5`); override OXCAML_BIN to pin a
# different install. Built in an isolated dir so it never clobbers the stock _build.
OXCAML_BIN       ?= $(shell sysdep-run -source boot -attr-path oxcaml.r5 -print-bin-dir 2>/dev/null)
OXCAML_BUILD_DIR ?= _build-oxcaml
# The shipped libraries (archive stem = dir/libname); excludes tests/ and tools/.
OXCAML_LIBS := smt/core/oxsmt_core smt/interface/oxsmt_interface \
               smt/preprocess/oxsmt_preprocess smt/solver/oxsmt_solver \
               smt/smtlib/oxsmt_smtlib smt/smtlib/parser/oxsmt_smtlib_parser \
               smt/theories/euf/oxsmt_euf smt/theories/lia/oxsmt_lia

.PHONY: build build-oxcaml fmt test core-test sat-test sat-bench perf-gen perf-bench preprocess-test lia-test euf-test wiring-test smtlib-test smtlib-corpus eval-test bench gate promote check-frozen spine status status-fresh mutants

## build — compile everything under smt/ (stdlib-only). Fast dev loop.
build:
	$(DUNE) build @@default

## build-oxcaml — compile the shipped smt/ libraries with the OxCaml toolchain
##   (task oxcaml-check). Keeps "pure OxCaml" TRUE BY TEST: type-checks all of smt/
##   then compiles every shipped library to native (.cmxa) + bytecode (.cma) with
##   OxCaml's flambda2 compiler, in an isolated build dir. This is NOT compiler
##   integration (DESIGN §1 non-goal) — same dune project, a different compiler on
##   PATH. The inline PATH puts OxCaml's ocamlopt first and drops opam's ocamlfind,
##   so dune's context compiler is OxCaml. Deliberately builds NO native executables:
##   the nix OxCaml runtime targets a newer glibc than this el8 box's system linker,
##   so linking an .exe fails on __isoc23_strtol / dlopen undefined refs — a
##   C-toolchain plumbing mismatch, not a source incompatibility (library compilation
##   is unaffected). Nightly-intent, alongside status-fresh and mutants.
build-oxcaml:
	@test -n "$(OXCAML_BIN)" || { echo "build-oxcaml: OxCaml toolchain not found (sysdep-run -source boot -attr-path oxcaml.r5); set OXCAML_BIN=" >&2; exit 1; }
	@ver=$$($(OXCAML_BIN)/ocamlopt.opt -version); \
	  case "$$ver" in \
	    *+ox*) echo "build-oxcaml: using $$ver at $(OXCAML_BIN)" ;; \
	    *) echo "build-oxcaml: resolved compiler '$$ver' at $(OXCAML_BIN) is not OxCaml (no '+ox' in version); refusing" >&2; exit 1 ;; \
	  esac
	PATH="$(OXCAML_BIN):/usr/bin:/bin" $(DUNE) build --root . --build-dir=$(OXCAML_BUILD_DIR) @smt/check
	PATH="$(OXCAML_BIN):/usr/bin:/bin" $(DUNE) build --root . --build-dir=$(OXCAML_BUILD_DIR) \
	  $(foreach l,$(OXCAML_LIBS),$(l).cmxa $(l).cma)
	@mkdir -p $(LOGS)
	@echo "oxcaml library build: OK $$($(OXCAML_BIN)/ocamlopt.opt -version)" | tee $(LOGS)/oxcaml-build.log
	@echo "build-oxcaml: OK — smt/ type-checks and all shipped libraries compile (native + bytecode) under OxCaml"

## core-test — smt/core unit + property self-test (stdlib-only, deterministic).
##   Separate from `test` (the .smt2 harness): this is the in-tree TCB check for
##   the term layer (ADR-0003). Nonzero exit on any failed check.
core-test:
	$(DUNE) exec smt/core/test/core_test.exe

## sat-test — CDCL SAT core (smt/solver) unit + property self-test (stdlib-only,
##   deterministic). Exact learned-clause/backjump/antecedent checks on textbook
##   conflicts, assumption semantics, incremental add-after-solve, every sat model
##   self-checked by evaluation, and thousands of random CNFs cross-checked against
##   an independent DPLL oracle. Nonzero exit on any failed check (TASKS.md M1-sat).
sat-test:
	$(DUNE) exec smt/solver/test/sat_test.exe

## sat-bench — run the SAT core over a DIMACS corpus ($(SAT_CORPUS)). GLOBs
##   **/*.cnf at runtime, label-checks uf*/uuf* families, self-checks every sat
##   model, and tolerates an absent corpus with a clear message. Digest to stdout,
##   full per-file log under $(LOGS). Deterministic (slowest ranking by conflicts).
sat-bench:
	@mkdir -p $(LOGS)
	$(DUNE) build smt/solver/test/sat_bench.exe
	_build/default/smt/solver/test/sat_bench.exe $(SAT_CORPUS) --log $(LOGS)/sat-bench.log

## perf-gen — regenerate the committed adversarial perf corpus ($(PERF_CASES)).
##   Run only to refresh cases after editing a family in tests/perf/gen_perf.ml;
##   the generated .smt2 are committed for a fixed, reviewable corpus (DESIGN §8.4).
perf-gen:
	$(DUNE) build tests/perf/gen_perf.exe
	_build/default/tests/perf/gen_perf.exe $(PERF_CASES)

## perf-bench — run the solver CLI over the adversarial perf corpus and print a
##   per-case { verdict, counters, wall_ms } table. A VISIBILITY tool, not a gate
##   (DESIGN §8: perf is surfaced, not gated); its stdout is NOT a committed golden
##   (wall-clock allowed). Full log under $(LOGS)/perf. Override SOLVER as for `test`.
perf-bench:
	@mkdir -p $(LOGS)/perf
	$(DUNE) build $(SOLVER) tests/perf/perf_bench.exe
	_build/default/tests/perf/perf_bench.exe $(SOLVER) $(PERF_CASES) --log $(LOGS)/perf/perf-bench.log

## preprocess-test — smt/preprocess unit + property self-test (stdlib-only,
##   deterministic). Brute-force equivalence-by-evaluation for the desugaring
##   passes, brute-force original<=>CNF for the Tseitin clausifier, Pipeline
##   Debug.check on outputs, determinism, and the Unsupported boundary. Nonzero
##   exit on any failed check.
preprocess-test:
	$(DUNE) exec smt/preprocess/test/preprocess_test.exe

## wiring-test — session layer (smt/interface) semantics + namespace guards. Push/pop
##   retraction, assert-after-check, THE SOUNDNESS RULE (theory atom -> unknown), model
##   extraction, and the reserved-namespace guard on both the session and the parser. Lives
##   under tests/solver (links the test-only parser). Nonzero exit on any failed check.
wiring-test:
	$(DUNE) exec tests/solver/wiring_test.exe

## euf-test — smt/theories/euf proof-producing congruence closure (Nieuwenhuis-
##   Oliveras) unit + property self-test (stdlib-only, deterministic). The textbook
##   refutation with exact conflict premises, deep congruence chains, (dis)equality
##   propagation, thousands of randomized assert sequences cross-checked against an
##   INDEPENDENT naive quadratic congruence closure (equivalence classes +
##   consistency verdict), explanation-soundness replay, interleaved
##   assert/push/pop/check vs scratch recomputation, and run-twice determinism.
##   Nonzero exit on any failed check (TASKS.md M2-euf).
euf-test:
	$(DUNE) exec smt/theories/euf/test/euf_test.exe

## lia-test — smt/theories/lia unit + property self-test (stdlib-only, deterministic).
##   Exact rational/δ-rational arithmetic incl. overflow guards; hand cases (DdM
##   feasible/infeasible systems, infeasible bound chains with exact Farkas multipliers,
##   gcd-tightening, strict-vs-nonstrict via δ, unbounded); thousands of random bounded
##   systems cross-checked against exhaustive integer enumeration (verdict + returned
##   model); an INDEPENDENT Farkas verifier run on every conflict plus a tampered-certificate
##   mutant demo; near-max_int overflow raising cleanly with state intact; and a
##   run-twice determinism check (pivot count logged). Nonzero exit on any failed check.
lia-test:
	$(DUNE) exec smt/theories/lia/test/lia_test.exe

## smtlib-test — round-trip suite for the SMT-LIB2 printer + test-only parser.
##   Deterministic and corpus-independent (committed test): round-trip A (print->parse
##   over ~30 programmatic sessions covering every node, quoting, negatives, div/mod, deep
##   nesting) and round-trip B (parse->print->parse over tests/cases + harness fixtures +
##   gate honeypots). Nonzero exit on any round-trip mismatch or lost :status.
smtlib-test:
	$(DUNE) build smt/smtlib/test/roundtrip_test.exe
	$(DUNE) exec smt/smtlib/test/roundtrip_test.exe -- \
	  tests/cases tests/harness/fixtures tests/gate/honeypots

## smtlib-corpus — parse-only smoke over a public corpus (default $(SMTLIB_CORPUS)).
##   Corpora are never in git, so this is SEPARATE from smtlib-test. Reports
##   ok/unsupported/malformed/crashed counts; digest to stdout, full per-file log to
##   $(LOGS). Crashes fail the run; unsupported constructs are expected diversity.
smtlib-corpus:
	$(DUNE) build smt/smtlib/test/corpus_smoke.exe
	$(DUNE) exec smt/smtlib/test/corpus_smoke.exe -- \
	  $(SMTLIB_CORPUS) --log $(LOGS)/smtlib-corpus-smoke.log

## eval-test — N-version model-evaluator self-test (tests/eval, task #74, DESIGN.md §8
##   layer 1 / §10). Independent judge: consumes oxsmt_core ONLY, written from spec with
##   no access to solver internals. One satisfying + one falsifying model per Term node,
##   the gate's real sat cases + .model sidecars (all MODEL-SATISFIES), deliberately-
##   corrupted models (MODEL-FAILS), the euclidean div/mod sign matrix, and overflow
##   raising. Nonzero exit on any failed check. The `eval` CLI is built alongside.
eval-test:
	$(DUNE) build tests/eval/eval_cli.exe
	$(DUNE) exec tests/eval/test/eval_test.exe -- $(CASES)

## fmt — format all sources in place with ocamlformat.
fmt:
	$(DUNE) fmt

## check-frozen — enforce the frozen-interface hashes (DESIGN.md §10, §11).
##   Recomputes sha256 of the five frozen core .mlis and diffs FROZEN.sha256;
##   red (with the unfreeze instructions) on any drift. Runs first in `test`.
check-frozen:
	tools/check_frozen.sh check

## spine — regenerate SPINE.md, the master's concatenated view of the frozen
##   core .mlis (DESIGN.md §11). Commit the result; it is a generated file.
spine:
	tools/check_frozen.sh spine

## test — frozen-interface guard, harness self-test, then the .smt2 golden/expect
##   regression. check-frozen runs FIRST so a drifted frozen .mli fails every
##   suite run. Then the pure unit self-test (proves red-detection works), then
##   diffs produced-vs-golden over tests/cases + fixtures. Digest to stdout,
##   full detail under $(LOGS)/harness, exact stats under $(STATS). Nonzero on
##   any diff or missing golden. Override SOLVER to test the real solver.
test: check-frozen
	$(DUNE) build tests/harness/run_harness.exe tests/harness/stub_solver.exe \
	  tests/solver/oxsmt_cli.exe tests/eval/eval_cli.exe
	$(DUNE) exec tests/harness/harness_test.exe -- $(EVAL) $(CASES)/bool_or_sat.smt2
	$(DUNE) exec tests/harness/run_harness.exe -- $(HARNESS_ARGS)

## bench — run the performance/adversarial corpus, emit digest to ../logs.
bench:
	@echo "not yet implemented (see TASKS.md: M0-harness)" && exit 1

## mutants — seeded-fault mutation testing (DESIGN.md §10). Applies each registry
##   patch in a throwaway worktree off HEAD, runs the mutant's declared suite, and
##   requires it goes red. Full registry by default; `make mutants MODULE=core`
##   filters by module. SURVIVORS exit 1 (an oracle gap — halt feature work on
##   that module); PATCH-FAILED/LINT-REJECT exit 2. Digest to stdout, full log to
##   ../logs/mutants-<stamp>.log. See tools/mutants/registry/README.md.
mutants:
	tools/mutants/run.sh $(MODULE)

## gate — Lean 4 certification (external oracle). Runs honeypots first (aborts
## red if any is certified), then the tests/cases corpus, using the
## content-addressed cache in ../cache. Digest to stdout; full log to ../logs.
gate:
	$(DUNE) build tests/gate/gate.exe
	_build/default/tests/gate/gate.exe selftest
	_build/default/tests/gate/gate.exe run

## status — regenerate STATUS.md by AGGREGATING existing artifacts (DESIGN §8.4, §11).
##   Reads TASKS.md, git, the latest gate log, the most recent existing stats
##   JSONL, committed line budgets, and the last captured harness digest. Does
##   NOT run the harness — so the committed STATUS.md is byte-stable given the
##   same (repo, logs): back-to-back `make status` produce identical output. The
##   only per-run-varying line is "generated at <HEAD>" (git HEAD, never
##   wall-clock); per-goal wall_ms lives only in the uncommitted stats sidecar,
##   never in the committed file. Prints a ~5-line digest; overwrites STATUS.md.
status:
	$(DUNE) build tools/status_gen/status_gen.exe
	$(DUNE) exec tools/status_gen/status_gen.exe -- \
	  --repo . --logs $(LOGS) --stats $(STATS) --tasks TASKS.md \
	  --budgets tools/line_budgets.txt \
	  --harness-digest $(LOGS)/harness/last-digest.txt --out STATUS.md

## status-fresh — refresh inputs, then regenerate (the nightly path). Runs the
##   fast harness once (writing a new stats JSONL + capturing its digest) so the
##   pass/fail line and stats reflect the current tree, then aggregates via
##   `status`. Not on the plain-`make status` path precisely because it mutates
##   inputs (new stats file) — keeping generation and refresh separate is what
##   makes the committed artifact's diff meaningful.
status-fresh:
	$(DUNE) build tests/harness/run_harness.exe tests/harness/stub_solver.exe \
	  tests/solver/oxsmt_cli.exe tests/eval/eval_cli.exe
	@mkdir -p $(LOGS)/harness
	-$(DUNE) exec tests/harness/run_harness.exe -- $(HARNESS_ARGS) > $(LOGS)/harness/last-digest.txt 2>&1
	$(MAKE) status LOGS=$(LOGS) STATS=$(STATS)

## promote — accept current solver output as golden (the promote workflow).
##   Rewrites the .smt2.expected sidecars for missing/mismatched goldens and
##   prints a per-file diffstat so the promoting agent sees what it accepts.
##   Label mismatches and solver errors are never masked — they still fail.
promote:
	$(DUNE) build tests/harness/run_harness.exe tests/harness/stub_solver.exe \
	  tests/solver/oxsmt_cli.exe tests/eval/eval_cli.exe
	$(DUNE) exec tests/harness/run_harness.exe -- $(HARNESS_ARGS) --promote
