# oxsmt build entry points. smt/ is a standalone stdlib-only subproject; the
# dev loop never builds or runs the compiler (DESIGN.md §1, §3).
#
# The bare `dune` on PATH is a Jane Street dispatch wrapper that fails outside
# jane workspaces, so we pin the opam toolchain explicitly.

# OPAM_BIN: the opam 5.4.0 toolchain bin dir. Overridable (env or `make OPAM_BIN=...`)
# so this is not hard-pinned to one developer's home when CI runs off-box; the default
# is this environment's toolchain (M0-harness-hygiene).
OPAM_BIN ?= /usr/local/home/jujacobs/.opam/5.4.0/bin
DUNE := $(OPAM_BIN)/dune
export PATH := $(OPAM_BIN):$(PATH)

# Harness knobs (override on the command line, e.g. `make test SOLVER=path/to/other`).
# SOLVER defaults to the real solver CLI (tests/solver, M1-wiring): it drives the shipped
# session layer and implements the harness contract. The stub (unknown for every
# check-sat) stays buildable as a fallback / for harness plumbing tests — override
# `SOLVER=_build/default/tests/harness/stub_solver.exe` to use it.
# LOGS/STATS resolve relative to the make invocation dir (the project root).
SOLVER   ?= _build/default/tests/solver/oxsmt_cli.exe
# EVAL: the N-version model evaluator CLI (tests/eval). The harness runs it on every
# sat verdict's model before accepting (DESIGN.md §8 layer 1). A sat we cannot
# self-check is a failure, never a pass.
EVAL     ?= _build/default/tests/eval/eval_cli.exe
# LOGS/STATS resolve relative to the make invocation dir. `make` is meant to run from
# main/, where ../logs is the sibling log dir (DESIGN §11 topology). From a worktree,
# ../logs would resolve to worktrees/logs — so pass LOGS=<abs path> when running suites
# from a task worktree (M0-harness-hygiene). CI runs from main/, so the default is right.
LOGS     ?= ../logs
STATS    ?= $(LOGS)/stats
CASES    ?= tests/cases
FIXTURES ?= tests/harness/fixtures
HARNESS_ARGS := --solver $(SOLVER) --eval $(EVAL) --dir $(CASES) --dir $(FIXTURES) \
                --logs $(LOGS) --stats $(STATS)

# SAT bench corpus. Defaults to the uf50/uuf50 families (the M1 verdict-agreement
# target, solved in seconds); GLOBs at runtime and tolerates absence. Override to
# run elsewhere, e.g. `make sat-bench SAT_CORPUS=../corpora/SAT` for the whole
# tree (which includes intentionally-hard families like pigeon-hole).
SAT_CORPUS ?= ../corpora/SAT/uf50-218 ../corpora/SAT/uuf50-218

# Adversarial perf corpus (committed, generated by tests/perf/gen_perf.ml).
PERF_CASES ?= tests/perf/cases

# smtlib-corpus knob: which public corpus to smoke-parse. Default is QF_UFLIA (the target
# logic). Corpora are a sibling of main/, never in git, so ../corpora resolves from main/
# (from a worktree, override SMTLIB_CORPUS to ../../corpora/... — same caveat as LOGS).
SMTLIB_CORPUS ?= ../corpora/QF_UFLIA

# OxCaml compile check (task oxcaml-check). The shipped smt/ libraries must compile
# under Jane Street's OxCaml compiler too, not just stock OCaml — "pure OxCaml" kept
# true by test, not intention. The compiler is resolved from the boot sysdeps with no
# network (`sysdep-run -source boot -attr-path oxcaml.r5`); override OXCAML_BIN to pin a
# different install. Built in an isolated dir so it never clobbers the stock _build.
OXCAML_BIN       ?= $(shell sysdep-run -source boot -attr-path oxcaml.r5 -print-bin-dir 2>/dev/null)
OXCAML_BUILD_DIR ?= _build-oxcaml
# The shipped libraries (archive stem = dir/libname); excludes tests/ and tools/.
OXCAML_LIBS := smt/core/oxsmt_core smt/interface/oxsmt_interface \
               smt/preprocess/oxsmt_preprocess smt/solver/oxsmt_solver \
               smt/smtlib/oxsmt_smtlib smt/smtlib/parser/oxsmt_smtlib_parser \
               smt/theories/euf/oxsmt_euf smt/theories/lia/oxsmt_lia

# corpus-run knobs (board #124). Parallel sweep over the solver CLI: CORPUS_JOBS workers
# (default 48, leaving headroom on this 64-core box for in-flight builds), CORPUS_TIMEOUT
# seconds hard per-file budget (2s is enough — theory files degrade to a fast unknown
# pre-adapter). Files above CORPUS_MAX_BYTES (the 20 MB precedent) are skipped.
CORPUS_DIRS ?= ../corpora/QF_UF ../corpora/QF_LIA ../corpora/QF_UFLIA
CORPUS_TIMEOUT ?= 2
CORPUS_JOBS ?= 48
CORPUS_MAX_BYTES ?= 20971520
# board #60 counted cutoff: set to a positive N for a deterministic, load-independent
# per-file effort cap (SAT conflicts + decisions + seam Final-rounds). Empty (default) =
# unbounded; the run still records per-file effort so an uncapped sweep calibrates N.
CORPUS_MAX_EFFORT ?=
# board #69: the GENEROUS wall safety net for `corpus-run-release`. The counted cap is the
# binding cutoff; this only backstops pathological unbounded between-tick work (codex AP2b).
# Large enough that it essentially never fires for a well-calibrated N.
CORPUS_RELEASE_TIMEOUT ?= 120
# board #69: sample dirs for `make dev-release-check` (dev≡release verdict-equality gate).
# Default = the committed regression cases; override with a corpus subset for a wider sweep.
DEV_RELEASE_DIRS ?= tests/cases

.PHONY: build build-oxcaml fmt test core-test core-prelude-test sat-test seam-test sat-bench corpus-run corpus-run-release promote-baseline dev-release-check driver-equiv-test perf-gen perf-bench preprocess-test bigint-test lia-test lia-adapter-test euf-test euf-adapter-test combine-test wiring-test smtlib-test smtlib-corpus fuzz-lex eval-test bench gate promote check-frozen spine status status-fresh status-test mutants

## build — compile everything under smt/ (stdlib-only). Fast dev loop.
build:
	$(DUNE) build @@default

## build-oxcaml — compile the shipped smt/ libraries with the OxCaml toolchain
##   (task oxcaml-check). Keeps "pure OxCaml" TRUE BY TEST: type-checks all of smt/
##   then compiles every shipped library to native (.cmxa) + bytecode (.cma) with
##   OxCaml's flambda2 compiler, in an isolated build dir. This is NOT compiler
##   integration (DESIGN §1 non-goal) — same dune project, a different compiler on
##   PATH. The inline PATH puts OxCaml's ocamlopt first and drops opam's ocamlfind,
##   so dune's context compiler is OxCaml. Deliberately builds NO native executables:
##   the nix OxCaml runtime targets a newer glibc than this el8 box's system linker,
##   so linking an .exe fails on __isoc23_strtol / dlopen undefined refs — a
##   C-toolchain plumbing mismatch, not a source incompatibility (library compilation
##   is unaffected). Nightly-intent, alongside status-fresh and mutants.
build-oxcaml:
	@test -n "$(OXCAML_BIN)" || { echo "build-oxcaml: OxCaml toolchain not found (sysdep-run -source boot -attr-path oxcaml.r5); set OXCAML_BIN=" >&2; exit 1; }
	@ver=$$($(OXCAML_BIN)/ocamlopt.opt -version); \
	  case "$$ver" in \
	    *+ox*) echo "build-oxcaml: using $$ver at $(OXCAML_BIN)" ;; \
	    *) echo "build-oxcaml: resolved compiler '$$ver' at $(OXCAML_BIN) is not OxCaml (no '+ox' in version); refusing" >&2; exit 1 ;; \
	  esac
	PATH="$(OXCAML_BIN):/usr/bin:/bin" $(DUNE) build --root . --build-dir=$(OXCAML_BUILD_DIR) @smt/check
	PATH="$(OXCAML_BIN):/usr/bin:/bin" $(DUNE) build --root . --build-dir=$(OXCAML_BUILD_DIR) \
	  $(foreach l,$(OXCAML_LIBS),$(l).cmxa $(l).cma)
	@mkdir -p $(LOGS)
	@echo "oxcaml library build: OK $$($(OXCAML_BIN)/ocamlopt.opt -version)" | tee $(LOGS)/oxcaml-build.log
	@echo "build-oxcaml: OK — smt/ type-checks and all shipped libraries compile (native + bytecode) under OxCaml"

## core-test — smt/core unit + property self-test (stdlib-only, deterministic).
##   Separate from `test` (the .smt2 harness): this is the in-tree TCB check for
##   the term layer (ADR-0003). Nonzero exit on any failed check.
core-test:
	$(DUNE) exec smt/core/test/core_test.exe

## core-prelude-test — external-consumer test for the M4 core prelude (task/core-prelude):
##   an oxsmt_core-only lib names the ADR-0005 THEORY vocabulary (Atom/Lit/Explanation/
##   Theory/Model) re-exported from Oxsmt_core and builds a Model via Model.of_alist,
##   including its raise-on-duplicate-term contract. Nonzero exit on any failed check.
core-prelude-test:
	$(DUNE) exec tests/core_prelude/prelude_test.exe

## sat-test — CDCL SAT core (smt/solver) unit + property self-test (stdlib-only,
##   deterministic). Exact learned-clause/backjump/antecedent checks on textbook
##   conflicts, assumption semantics, incremental add-after-solve, every sat model
##   self-checked by evaluation, and thousands of random CNFs cross-checked against
##   an independent DPLL oracle. Nonzero exit on any failed check (TASKS.md M1-sat).
sat-test:
	$(DUNE) exec smt/solver/test/sat_test.exe

## seam-test — CDCL(T) theory-callback seam (smt/solver, ADR-0005 §3) self-test via a
##   scripted MOCK theory: theory conflict at various trail depths, propagation-then-
##   conflict, lazy explain (called iff analysis resolves a theory literal), push/pop
##   synchronization under backjumps + Luby restarts, a final-check split, and a
##   no-theory regression (inert theory bit-identical to no theory).
seam-test:
	$(DUNE) exec smt/solver/test/seam_test.exe

## cert-test — certificate emission-wiring self-test (smt/certificate, ADR-0013 §4.0, M5
##   step 1). Drives the frozen Sat trace seam through the Recorder and pins each hook for
##   the four Unsat exits + E3 Theory_prop materialization + the ordered-RUP antecedent
##   order; every check is discriminating (RED against the pre-wiring core). Also asserts a
##   traced solve is bit-identical (verdict/model/counters) to an untraced one. Nonzero
##   exit on any failed check.
cert-test:
	$(DUNE) exec smt/certificate/test/cert_emit_test.exe

## sat-bench — run the SAT core over a DIMACS corpus ($(SAT_CORPUS)). GLOBs
##   **/*.cnf at runtime, label-checks uf*/uuf* families, self-checks every sat
##   model, and tolerates an absent corpus with a clear message. Digest to stdout,
##   full per-file log under $(LOGS). Deterministic (slowest ranking by conflicts).
sat-bench:
	@mkdir -p $(LOGS)
	$(DUNE) build smt/solver/test/sat_bench.exe
	_build/default/smt/solver/test/sat_bench.exe $(SAT_CORPUS) --log $(LOGS)/sat-bench.log

## perf-gen — regenerate the committed adversarial perf corpus ($(PERF_CASES)).
##   Run only to refresh cases after editing a family in tests/perf/gen_perf.ml;
##   the generated .smt2 are committed for a fixed, reviewable corpus (DESIGN §8.4).
perf-gen:
	$(DUNE) build tests/perf/gen_perf.exe
	_build/default/tests/perf/gen_perf.exe $(PERF_CASES)

## perf-bench — run the solver CLI over the adversarial perf corpus and print a
##   per-case { verdict, counters, wall_ms } table. A VISIBILITY tool, not a gate
##   (DESIGN §8: perf is surfaced, not gated); its stdout is NOT a committed golden
##   (wall-clock allowed). Full log under $(LOGS)/perf. Override SOLVER as for `test`.
perf-bench:
	@mkdir -p $(LOGS)/perf
	$(DUNE) build $(SOLVER) tests/perf/perf_bench.exe
	_build/default/tests/perf/perf_bench.exe $(SOLVER) $(PERF_CASES) --log $(LOGS)/perf/perf-bench.log

## corpus-run — parallel, label-checked sweep of the full pre-labeled SMT-LIB corpus
##   ($(CORPUS_DIRS)), no Lean. Fans out $(CORPUS_JOBS) corpus_classify processes with a
##   hard $(CORPUS_TIMEOUT)s per-file timeout. Payload: ZERO soundness mismatches — a
##   definite verdict contradicting a file's :status is CRITICAL and exits nonzero;
##   unknown-vs-label is the expected v1 completeness gap. Digest to stdout; per-file
##   detail to $(LOGS)/corpus-run.raw; a JSON summary in the committed baseline schema
##   (oxsmt-corpus-baseline/v1) to $(LOGS)/corpus-run.json. It NEVER writes the committed
##   snapshot tests/corpus/baseline_summary.json — promoting a milestone snapshot is a
##   deliberate manual copy+commit (see tests/README.md). Repeatable — M4 re-runs it.
corpus-run:
	@mkdir -p $(LOGS)
	$(DUNE) build tests/corpus/corpus_classify.exe
	CLASSIFY=_build/default/tests/corpus/corpus_classify.exe \
	  CORPUS_TIMEOUT=$(CORPUS_TIMEOUT) CORPUS_JOBS=$(CORPUS_JOBS) \
	  CORPUS_MAX_BYTES=$(CORPUS_MAX_BYTES) CORPUS_MAX_EFFORT=$(CORPUS_MAX_EFFORT) \
	  CORPUS_JSON=$(LOGS)/corpus-run.json CORPUS_RAW=$(LOGS)/corpus-run.raw \
	  bash tests/corpus/corpus_run.sh $(CORPUS_DIRS)

## corpus-run-release — the PROMOTABLE measurement (board #69). Builds the classifier
##   with `--profile release` (assertions off) — the classifier also forces debug oracles
##   off at startup — so `--stamp` reports release-config; corpus_run.sh records that stamp
##   plus the build commit + clean/dirty tree into the run JSON, and only such a run passes
##   `make promote-baseline`. Pair with a counted cutoff (CORPUS_MAX_EFFORT=N) for a
##   load-independent, byte-reproducible headline.
corpus-run-release:
	@test -n "$(CORPUS_MAX_EFFORT)" || { \
	  echo "corpus-run-release: CORPUS_MAX_EFFORT must be a finite N (codex AP2a) — a" >&2; \
	  echo "  promotable run is cut off by the deterministic counted budget, never wall-only." >&2; \
	  echo "  e.g. make corpus-run-release CORPUS_MAX_EFFORT=50000" >&2; \
	  exit 1; }
	@mkdir -p $(LOGS)
	$(DUNE) build --profile release tests/corpus/corpus_classify.exe
	CLASSIFY=_build/default/tests/corpus/corpus_classify.exe \
	  CORPUS_TIMEOUT=$(CORPUS_RELEASE_TIMEOUT) CORPUS_JOBS=$(CORPUS_JOBS) \
	  CORPUS_MAX_BYTES=$(CORPUS_MAX_BYTES) CORPUS_MAX_EFFORT=$(CORPUS_MAX_EFFORT) \
	  CORPUS_JSON=$(LOGS)/corpus-run.json CORPUS_RAW=$(LOGS)/corpus-run.raw \
	  bash tests/corpus/corpus_run.sh $(CORPUS_DIRS)
	@# AP5(i): CLASSIFY is a LITERAL (not $$(CLASSIFY)), so a promotable run is bound to the
	@# freshly-built --profile release exe and cannot be pointed at another binary via a
	@# make/env override. CORPUS_RELEASE_TIMEOUT is a GENEROUS safety net only — the counted
	@# CORPUS_MAX_EFFORT is the binding, load-independent cutoff (AP2b: the wall still
	@# backstops unbounded between-tick work; a file that hits it is a deterministic-enough
	@# unknown, never counted-solved).

## promote-baseline — fail-closed headline promote (board #69). Copies a corpus-run JSON to
##   the committed tests/corpus/baseline_summary.json ONLY IF its provenance stamp is
##   release_config=true, dirty=false, build_commit==HEAD, finite max_effort, and
##   mismatch_count=0. No override. Defaults to the last run JSON.
promote-baseline:
	bash tools/promote_baseline.sh $(LOGS)/corpus-run.json

## dev-release-check — repeatable dev≡release output-equality gate (board #69, codex AP4 /
##   budget-reviewer H1). Builds corpus_classify under dev and --profile release and asserts
##   byte-identical verdict+effort on $(DEV_RELEASE_DIRS) (default tests/cases): the release
##   profile (assertions + debug oracles off) must be PERF-ONLY, never verdict-affecting.
dev-release-check:
	DUNE="$(DUNE)" DEV_RELEASE_DIRS="$(DEV_RELEASE_DIRS)" bash tools/dev_release_check.sh

## preprocess-test — smt/preprocess unit + property self-test (stdlib-only,
##   deterministic). Brute-force equivalence-by-evaluation for the desugaring
##   passes, brute-force original<=>CNF for the Tseitin clausifier, Pipeline
##   Debug.check on outputs, determinism, and the Unsupported boundary. Nonzero
##   exit on any failed check.
preprocess-test:
	$(DUNE) exec smt/preprocess/test/preprocess_test.exe

## wiring-test — session layer (smt/interface) semantics + namespace guards. Push/pop
##   retraction, assert-after-check, THE SOUNDNESS RULE (theory atom -> unknown), model
##   extraction, and the reserved-namespace guard on both the session and the parser. Lives
##   under tests/solver (links the test-only parser). Nonzero exit on any failed check.
wiring-test:
	$(DUNE) build tests/solver/oxsmt_cli.exe
	$(DUNE) exec tests/solver/wiring_test.exe

## driver-equiv-test — the driver-equivalence guard (task #133). Builds corpus_classify
##   (the headline measurement driver) and oxsmt_cli (the shipped batch path), then asserts
##   they return equivalent verdicts over a deterministic committed sample (tests/cases +
##   tests/corpus/equiv_fixtures — presolve-active, no-op, incremental, and parse-fail
##   files across QF_UF/QF_LIA/QF_UFLIA). Makes any future driver split loud: the two must
##   drive the Session identically or the official sweep would measure a path that differs
##   from the one that ships (a measurement-integrity hazard). Point it at a real corpus
##   subtree for a wider spot-sweep: append dirs after the committed ones. Nonzero on any
##   divergence, error, or classifier nondeterminism.
driver-equiv-test:
	$(DUNE) build tests/corpus/driver_equiv_test.exe tests/corpus/corpus_classify.exe \
	  tests/solver/oxsmt_cli.exe
	_build/default/tests/corpus/driver_equiv_test.exe \
	  --classify _build/default/tests/corpus/corpus_classify.exe \
	  --cli _build/default/tests/solver/oxsmt_cli.exe \
	  tests/cases tests/corpus/equiv_fixtures

## euf-test — smt/theories/euf proof-producing congruence closure (Nieuwenhuis-
##   Oliveras) unit + property self-test (stdlib-only, deterministic). The textbook
##   refutation with exact conflict premises, deep congruence chains, (dis)equality
##   propagation, thousands of randomized assert sequences cross-checked against an
##   INDEPENDENT naive quadratic congruence closure (equivalence classes +
##   consistency verdict), explanation-soundness replay, interleaved
##   assert/push/pop/check vs scratch recomputation, and run-twice determinism.
##   Nonzero exit on any failed check (TASKS.md M2-euf).
euf-test:
	OXSMT_EUF_SELF_CHECK=1 $(DUNE) exec smt/theories/euf/test/euf_test.exe

## euf-adapter-test — ADR-0005 THEORY adapter (Euf_adapter) adversarial self-test
##   (stdlib-only, deterministic). Drives the frozen THEORY surface only (create /
##   register_atom / assert_lit / check / explain / push / pop / model) and cross-checks
##   every observable against an INDEPENDENT naive congruence closure: conflict &
##   propagation explanation soundness (replayed to entailment), premises never leak the
##   reserved true<>false axiom, predicate/bool-lit encoding, push/pop restoration (deep
##   nesting, pop-below-conflict, assert-after-pop), model-induced equality + predicate
##   truth + Bool-Eq currency, and run-twice determinism. Nonzero exit on any failed check
##   (TASKS.md M4-adapters).
euf-adapter-test:
	OXSMT_EUF_SELF_CHECK=1 $(DUNE) exec smt/theories/euf/test/euf_adapter_test.exe

## bigint-test — smt/theories/lia Bigint self-test (core-bignum W2, stdlib-only): limb-
##   boundary hand vectors, pure-OCaml property vectors, a Knuth add-back regression vector,
##   a deep-growth tripwire (hundreds of limbs), and an INDEPENDENT Python differential
##   oracle. Nonzero exit on any failed check (the suite the bigint mutants run against).
bigint-test:
	$(DUNE) exec smt/theories/lia/test/bigint_test.exe

## lia-test — smt/theories/lia unit + property self-test (stdlib-only, deterministic).
##   Exact rational/δ-rational arithmetic incl. overflow guards; hand cases (DdM
##   feasible/infeasible systems, infeasible bound chains with exact Farkas multipliers,
##   gcd-tightening, strict-vs-nonstrict via δ, unbounded); thousands of random bounded
##   systems cross-checked against exhaustive integer enumeration (verdict + returned
##   model); an INDEPENDENT Farkas verifier run on every conflict plus a tampered-certificate
##   mutant demo; near-max_int overflow raising cleanly with state intact; and a
##   run-twice determinism check (pivot count logged). Nonzero exit on any failed check.
lia-test:
	$(DUNE) exec smt/theories/lia/test/lia_test.exe

## lia-adapter-test — smt/theories/lia THEORY-adapter (ADR-0005 M4) unit + property
##   self-test (stdlib-only, deterministic). Currency round-trip (Atom/Lit <-> Term),
##   conflict rule tags with a PUBLIC-OUTPUT Farkas verifier, bound propagation + lazy
##   precedence-valid explain, Final Sat/Split/Conflict incl. a CONTRACT-SPLIT
##   distinct-constraining-atoms check and Split->Sat drive, push/pop restoration +
##   recheck-after-backtrack (E5), CONTRACT-POISON overflow->unknown with bricked reuse,
##   idempotent register, and run-twice determinism. Nonzero exit on any failed check.
lia-adapter-test:
	$(DUNE) exec smt/theories/lia/test/lia_adapter_test.exe

## combine-test — smt/combine Nelson-Oppen model-based combination by INTERNALIZATION
##   (internalization ADR). Three layers, all stdlib-only + deterministic: (1) MECHANICS
##   over a programmable mock theory (routing incl. internalize-into-A fan-out, push/pop
##   lockstep, propagation/explain provenance, pin poison, sort-directed model merge);
##   (2) INTEGRATION over a toy EUF + toy LIA + mini DPLL(T) driver; (3) the ADR §6 corpus
##   through the REAL Euf_adapter + Lia_adapter (W1/R1/tower, f(x+1)<f(y+1), numeral corner,
##   k(x+1)≠k(1) buried-LIA, p(x+1), Bool leaf UNSAT + compound degrade-to-unknown,
##   mixed-equality totality, deep tower, pure-QF_LIA zero-split, use-history transition,
##   push/pop-reassert). Nonzero exit on any failed check.
combine-test:
	OXSMT_EUF_SELF_CHECK=1 $(DUNE) exec smt/combine/test/combine_test.exe

## smtlib-test — round-trip suite for the SMT-LIB2 printer + test-only parser.
##   Deterministic and corpus-independent (committed test): round-trip A (print->parse
##   over ~30 programmatic sessions covering every node, quoting, negatives, div/mod, deep
##   nesting) and round-trip B (parse->print->parse over tests/cases + harness fixtures +
##   gate honeypots). Nonzero exit on any round-trip mismatch or lost :status.
smtlib-test:
	$(DUNE) build smt/smtlib/test/roundtrip_test.exe smt/smtlib/test/fuzz_lex.exe
	$(DUNE) exec smt/smtlib/test/roundtrip_test.exe -- \
	  tests/cases tests/harness/fixtures tests/gate/honeypots
	$(DUNE) exec smt/smtlib/test/fuzz_lex.exe -- 500

## fuzz-lex — standing adversarial round-trip fuzzer for the shared lexer (ADR-0008).
##   Deterministic (fixed seeds). Checks printer<->lexer kind preservation, print->parse
##   round-trip, and lexer idempotence over token-boundary-adversarial inputs. A smaller
##   subset also runs inside smtlib-test; this target runs the full stream.
##   Override iterations per seed: make fuzz-lex FUZZ_ITERS=100000
FUZZ_ITERS ?= 20000
fuzz-lex:
	$(DUNE) build smt/smtlib/test/fuzz_lex.exe
	$(DUNE) exec smt/smtlib/test/fuzz_lex.exe -- $(FUZZ_ITERS)

## smtlib-corpus — parse-only smoke over a public corpus (default $(SMTLIB_CORPUS)).
##   Corpora are never in git, so this is SEPARATE from smtlib-test. Reports
##   ok/unsupported/malformed/crashed counts; digest to stdout, full per-file log to
##   $(LOGS). Crashes fail the run; unsupported constructs are expected diversity.
smtlib-corpus:
	$(DUNE) build smt/smtlib/test/corpus_smoke.exe
	$(DUNE) exec smt/smtlib/test/corpus_smoke.exe -- \
	  $(SMTLIB_CORPUS) --log $(LOGS)/smtlib-corpus-smoke.log

## eval-test — N-version model-evaluator self-test (tests/eval, task #74, DESIGN.md §8
##   layer 1 / §10). Independent judge: consumes oxsmt_core ONLY, written from spec with
##   no access to solver internals. One satisfying + one falsifying model per Term node,
##   the gate's real sat cases + .model sidecars (all MODEL-SATISFIES), deliberately-
##   corrupted models (MODEL-FAILS), the euclidean div/mod sign matrix, and overflow
##   raising. Nonzero exit on any failed check. The `eval` CLI is built alongside.
eval-test:
	$(DUNE) build tests/eval/eval_cli.exe
	$(DUNE) exec tests/eval/test/eval_test.exe -- $(CASES)

## fmt — format all sources in place with ocamlformat.
fmt:
	$(DUNE) fmt

## check-frozen — enforce the frozen-interface hashes (DESIGN.md §10, §11).
##   Recomputes sha256 of the five frozen core .mlis and diffs FROZEN.sha256;
##   red (with the unfreeze instructions) on any drift. Runs first in `test`.
check-frozen:
	tools/check_frozen.sh check

## spine — regenerate SPINE.md, the master's concatenated view of the frozen
##   core .mlis (DESIGN.md §11). Commit the result; it is a generated file.
spine:
	tools/check_frozen.sh spine

## test — frozen-interface guard, harness self-test, the .smt2 golden/expect
##   regression, then the smtlib round-trip suite. check-frozen runs FIRST so a drifted
##   frozen .mli fails every suite run. Then the pure unit self-test (proves red-detection
##   works), then diffs produced-vs-golden over tests/cases + fixtures. Finally smtlib-test
##   (round-trip A/B over the same committed .smt2 corpus) runs on the fast path too: a
##   golden that parses but is not printer-round-trippable (e.g. a degenerate symbol name)
##   must be caught here, not only in an on-demand suite. Digest to stdout, full detail
##   under $(LOGS)/harness, exact stats under $(STATS). Nonzero on any diff or missing
##   golden. Override SOLVER to test the real solver.
test: check-frozen
	$(DUNE) build tests/harness/run_harness.exe tests/harness/stub_solver.exe \
	  tests/solver/oxsmt_cli.exe tests/eval/eval_cli.exe
	OXSMT_EUF_SELF_CHECK=1 $(DUNE) exec tests/harness/harness_test.exe -- $(EVAL) $(CASES)/bool_or_sat.smt2
	OXSMT_EUF_SELF_CHECK=1 $(DUNE) exec tests/harness/run_harness.exe -- $(HARNESS_ARGS)
	$(MAKE) combine-test
	$(MAKE) smtlib-test
	$(MAKE) lemma-test
	$(MAKE) cert-test
	$(MAKE) driver-equiv-test

## lemma-test — ADR-0012 lemma-tier tranche-1 acceptance: the soundness-rule honeypots
##   (H-SOUND / H-REFUTE / H-PUSHPOP / H-REPEAT-REFUTE) + gate/forge/cap negatives + the M1
##   dedup regression (lemma_honeypot_test), plus lemma-reviewer-2's verbatim C1/C2 wrong-
##   Unsat reproducers (crit_repro), all end-to-end through the real Session + Cdclt +
##   Combine + EUF + LIA stack (no mocks). Nonzero exit on any failed check.
lemma-test:
	$(DUNE) exec smt/ematch/test/lemma_honeypot_test.exe
	$(DUNE) exec smt/ematch/test/crit_repro.exe
	$(DUNE) exec smt/ematch/test/matcher_test.exe

## bench — run the performance/adversarial corpus, emit digest to ../logs.
bench:
	@echo "not yet implemented (see TASKS.md: M0-harness)" && exit 1

## mutants — seeded-fault mutation testing (DESIGN.md §10). Applies each registry
##   patch in a throwaway worktree off HEAD, runs the mutant's declared suite, and
##   requires it goes red. Full registry by default; `make mutants MODULE=core`
##   filters by module. SURVIVORS exit 1 (an oracle gap — halt feature work on
##   that module); PATCH-FAILED/LINT-REJECT exit 2. Digest to stdout, full log to
##   ../logs/mutants-<stamp>.log. See tools/mutants/registry/README.md.
mutants:
	tools/mutants/run.sh $(MODULE)

## gate — Lean 4 certification (external oracle). Runs honeypots first (aborts
## red if any is certified), then the tests/cases corpus, using the
## content-addressed cache in ../cache. Digest to stdout; full log to ../logs.
gate:
	$(DUNE) build tests/gate/gate.exe
	_build/default/tests/gate/gate.exe selftest
	_build/default/tests/gate/gate.exe run

## status — regenerate STATUS.md by AGGREGATING existing artifacts (DESIGN §8.4, §11).
##   Reads TASKS.md, git, the latest gate log, the most recent existing stats
##   JSONL, committed line budgets, and the last captured harness digest. Does
##   NOT run the harness — so the committed STATUS.md is byte-stable given the
##   same (repo, logs): back-to-back `make status` produce identical output. The
##   only per-run-varying line is "generated at <HEAD>" (git HEAD, never
##   wall-clock); per-goal wall_ms lives only in the uncommitted stats sidecar,
##   never in the committed file. Prints a ~5-line digest; overwrites STATUS.md.
status:
	$(DUNE) build tools/status_gen/status_gen.exe
	$(DUNE) exec tools/status_gen/status_gen.exe -- \
	  --repo . --logs $(LOGS) --stats $(STATS) --tasks TASKS.md \
	  --budgets tools/line_budgets.txt \
	  --harness-digest $(LOGS)/harness/last-digest.txt --out STATUS.md

## status-test — status_gen self-test: the gate-log provenance parse (task #133),
##   incl. the pid-form dir name from the gate fix round. Nonzero exit on any failure.
status-test:
	$(DUNE) exec tools/status_gen/status_gen.exe -- selftest

## status-fresh — refresh inputs, then regenerate (the nightly path). Runs the
##   fast harness once (writing a new stats JSONL + capturing its digest) so the
##   pass/fail line and stats reflect the current tree, then aggregates via
##   `status`. Not on the plain-`make status` path precisely because it mutates
##   inputs (new stats file) — keeping generation and refresh separate is what
##   makes the committed artifact's diff meaningful.
status-fresh:
	$(DUNE) build tests/harness/run_harness.exe tests/harness/stub_solver.exe \
	  tests/solver/oxsmt_cli.exe tests/eval/eval_cli.exe
	@mkdir -p $(LOGS)/harness
	-$(DUNE) exec tests/harness/run_harness.exe -- $(HARNESS_ARGS) > $(LOGS)/harness/last-digest.txt 2>&1
	$(MAKE) status LOGS=$(LOGS) STATS=$(STATS)

## promote — accept current solver output as golden (the promote workflow).
##   Rewrites the .smt2.expected sidecars for missing/mismatched goldens and
##   prints a per-file diffstat so the promoting agent sees what it accepts.
##   Label mismatches and solver errors are never masked — they still fail.
promote:
	$(DUNE) build tests/harness/run_harness.exe tests/harness/stub_solver.exe \
	  tests/solver/oxsmt_cli.exe tests/eval/eval_cli.exe
	$(DUNE) exec tests/harness/run_harness.exe -- $(HARNESS_ARGS) --promote
