(* Generated by vox_attribute_time.sh's scaling corpus: exactly 16 refinement
   obligations, each a widening of a bound that holds by transitivity.  No
   arithmetic, so nothing here depends on overflow reasoning and every
   obligation is genuinely discharged rather than trivially rejected. *)
let widen_00 (n : int{ _ > 1 }) : int{ _ > 0 } = n
let widen_01 (n : int{ _ > 2 }) : int{ _ > 1 } = n
let widen_02 (n : int{ _ > 3 }) : int{ _ > 2 } = n
let widen_03 (n : int{ _ > 4 }) : int{ _ > 3 } = n
let widen_04 (n : int{ _ > 5 }) : int{ _ > 4 } = n
let widen_05 (n : int{ _ > 6 }) : int{ _ > 5 } = n
let widen_06 (n : int{ _ > 7 }) : int{ _ > 6 } = n
let widen_07 (n : int{ _ > 8 }) : int{ _ > 7 } = n
let widen_08 (n : int{ _ > 9 }) : int{ _ > 8 } = n
let widen_09 (n : int{ _ > 10 }) : int{ _ > 9 } = n
let widen_10 (n : int{ _ > 11 }) : int{ _ > 10 } = n
let widen_11 (n : int{ _ > 12 }) : int{ _ > 11 } = n
let widen_12 (n : int{ _ > 13 }) : int{ _ > 12 } = n
let widen_13 (n : int{ _ > 14 }) : int{ _ > 13 } = n
let widen_14 (n : int{ _ > 15 }) : int{ _ > 14 } = n
let widen_15 (n : int{ _ > 16 }) : int{ _ > 15 } = n
