(* Generated by vox_attribute_time.sh's scaling corpus: exactly 4 refinement
   obligations, each a widening of a bound that holds by transitivity.  No
   arithmetic, so nothing here depends on overflow reasoning and every
   obligation is genuinely discharged rather than trivially rejected. *)
let widen_00 (n : int{ _ > 1 }) : int{ _ > 0 } = n
let widen_01 (n : int{ _ > 2 }) : int{ _ > 1 } = n
let widen_02 (n : int{ _ > 3 }) : int{ _ > 2 } = n
let widen_03 (n : int{ _ > 4 }) : int{ _ > 3 } = n
