/**************************************************************************/
/*                                                                        */
/*                                 OCaml                                  */
/*                                                                        */
/*      KC Sivaramakrishnan, Indian Institute of Technology, Madras       */
/*                   Tom Kelly, OCaml Labs Consultancy                    */
/*                 Stephen Dolan, University of Cambridge                 */
/*                                                                        */
/*   Copyright 2019 Indian Institute of Technology, Madras                */
/*   Copyright 2021 OCaml Labs Consultancy Ltd                            */
/*   Copyright 2019 University of Cambridge                               */
/*                                                                        */
/*   All rights reserved.  This file is distributed under the terms of    */
/*   the GNU Lesser General Public License version 2.1, with the          */
/*   special exception on linking described in the file LICENSE.          */
/*                                                                        */
/**************************************************************************/

#ifndef _GNU_SOURCE
#define _GNU_SOURCE /* for dl_iterate_phdr (ELF build-id) */
#endif

#define CAML_INTERNALS

#include "caml/platform.h"
#include "caml/frame_descriptors.h"
#include "caml/major_gc.h" /* for caml_major_cycles_completed */
#include "caml/memory.h"
#include "caml/fail.h"
#include "caml/shared_heap.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <link.h>

struct caml_frame_descrs {
  int num_descr;
  int mask;
  frame_descr** descriptors;
  caml_frametable_list *frametables;
  caml_frametable_list *zombies;
  caml_plat_mutex mutex;
};
/* Let us call 'capacity' the length of the descriptors array.

   We maintain the following invariants:
     capacity = mask + 1
     capacity = 0 || Is_power_of_2(capacity)
     num_desc <= 2 * num_descr <= capacity

   For an extensible array we would maintain
      num_desc <= capacity,
    but this is a linear-problem hash table, we need to ensure that
    free slots are frequent enough, so we use a twice-larger capacity:
      num_desc * 2 <= capacity

   We keep the list of frametables that was used to build the hashtable.
   We use it when rebuilding the table after resizing.

   We keep the list of frametables which need to be removed (zombies).
   We remove them in a STW handler before any new addition.

   We allow the user to call functions for frametable removal at any
   time, even inside a STW section (e.g. during custom block finalization).
   To this end, we use a mutex to protect the frametable insertions in
   the zombies list.

   All other modifications should only happen in a STW section.
*/

/* Defined in code generated by ocamlopt */
extern intnat * caml_frametable[];

/* PROTOTYPE (frame-lazy, task #53): a persistent, memory-mapped frame-descriptor
   table. The compiler binary is non-PIE (fixed load address), so every
   [frame_descr*] sits at an identical absolute address in every process; the
   hashtable is therefore a pure function of the linked binary and byte-identical
   across all runs. Instead of rebuilding it at every startup (~7.5 ms on the
   74 MB fleet compiler), the first process writes it to a cache file and later
   processes [mmap] it read-only and point [descriptors] at the mapping. Only the
   handful of buckets actually probed at GC/backtrace time fault in.

   Opt-in via CAML_FRAME_CACHE=<path> (default off ⇒ behaviour identical to
   baseline). The mapped array is read-only; the first runtime frametable
   registration/removal (e.g. Dynlink) copies it out to the heap first
   ([ensure_heap_descriptors]). Staleness is guarded by an O(1) binary-identity
   token; a mismatch falls back to a normal build. This is a prototype (env-gated,
   token guard not a full BuildID) — see frame-lazy-findings.md. */
static int frame_descrs_from_cache = 0;
static void *frame_cache_map = NULL;    /* mmap base, kept for process life */
static size_t frame_cache_map_len = 0;

/* Note: [cur] is bound by this macro */
#define iter_list(list,cur) \
  for (caml_frametable_list *cur = list; cur != NULL; cur = cur->next)

static frame_descr * next_frame_descr(frame_descr * d) {
  unsigned char num_allocs = 0, *p;
  CAMLassert(Retaddr_frame(d) >= 4096);
  if (!frame_return_to_C(d)) {
    /* Skip to end of live_ofs */
    p = frame_end_of_live_ofs(d);
    /* Skip alloc_lengths if present */
    if (frame_has_allocs(d)) {
      num_allocs = *p;
      p += num_allocs + 1;
    }
    /* Skip debug info if present */
    if (frame_has_debug(d)) {
      /* Align to 32 bits */
      p = Align_to(p, uint32_t);
      p += sizeof(uint32_t) * (frame_has_allocs(d) ? num_allocs : 1);
    }
    /* Align to word size */
    p = Align_to(p, void*);
    return ((frame_descr*) p);
  } else {
    /* This marks the top of an ML stack chunk. Skip over empty
     * frame descriptor */
    /* Skip to address of zero-sized live_ofs */
    CAMLassert(d->num_live == 0);
    p = (unsigned char*)&d->live_ofs[0];
    /* Align to word size */
    p = Align_to(p, void*);
    return ((frame_descr*) p);
  }
}

static intnat count_descriptors(caml_frametable_list *list) {
  intnat num_descr = 0;
  iter_list(list,cur) {
    num_descr += *((intnat*) cur->frametable);
  }
  return num_descr;
}

static caml_frametable_list* frametables_list_tail(caml_frametable_list *list) {
  caml_frametable_list *tail = NULL;
  iter_list(list,cur) {
    tail = cur;
  }
  return tail;
}

static int capacity(caml_frame_descrs table) {
  int capacity = table.mask + 1;
  CAMLassert(capacity == 0 || Is_power_of_2(capacity));
  return capacity;
}

static void fill_hashtable(
  caml_frame_descrs *table, caml_frametable_list *new_frametables)
{
  iter_list(new_frametables,cur) {
    intnat * tbl = (intnat*) cur->frametable;
    intnat len = *tbl;
    frame_descr * d = (frame_descr *)(tbl + 1);
    for (intnat j = 0; j < len; j++) {
      uintnat h = Hash_retaddr(Retaddr_frame(d), table->mask);
      while (table->descriptors[h] != NULL) {
        h = (h+1) & table->mask;
      }
      table->descriptors[h] = d;
      d = next_frame_descr(d);
    }
  }
}

static void remove_entry(caml_frame_descrs *table, frame_descr * d) {
  uintnat i;
  uintnat r;
  uintnat j;

  i = Hash_retaddr(Retaddr_frame(d), table->mask);
  while (table->descriptors[i] != d) {
    i = (i+1) & table->mask;
  }

 r1:
  j = i;
  table->descriptors[i] = NULL;
 r2:
  i = (i+1) & table->mask;
  // r3
  if(table->descriptors[i] == NULL) return;
  r = Hash_retaddr(Retaddr_frame(table->descriptors[i]), table->mask);
  /* If r is between i and j (cyclically), i.e. if
     table->descriptors[i]->retaddr don't need to be moved */
  if(( ( j < r )  && ( r <= i ) ) ||
     ( ( i < j )  && ( j < r )  ) ||      /* i cycled, r not */
     ( ( r <= i ) && ( i < j ) )     ) {  /* i and r cycled */
    goto r2;
  }
  // r4
  table->descriptors[j] = table->descriptors[i];
  goto r1;
}

/* If [descriptors] currently points at the read-only mmap'd cache, copy it out
   to a heap array before any mutation (registration/removal). After this the
   table behaves exactly as a normally-built one. */
static void ensure_heap_descriptors(caml_frame_descrs *table)
{
  if (!frame_descrs_from_cache) return;
  intnat tblsize = capacity(*table);
  frame_descr **heap =
    (frame_descr **) caml_stat_calloc_noexc(tblsize, sizeof(frame_descr *));
  if (heap == NULL) caml_raise_out_of_memory();
  memcpy(heap, table->descriptors, tblsize * sizeof(frame_descr *));
  table->descriptors = heap;
  frame_descrs_from_cache = 0;
  /* Leave the mmap mapped for the rest of the process; it is small and the
     runtime never tears the frame table down before exit. */
}

static void clean_frame_descriptors(caml_frame_descrs *table)
{
  intnat *tbl, len, decrease = 0;
  frame_descr * d;
  caml_frametable_list *cur = table->zombies, *rem;
  if (cur != NULL) {
    /* About to free frametables: if [descriptors] is the read-only mmap'd
       cache, copy it out to the heap before [remove_entry] mutates it. */
    ensure_heap_descriptors(table);
  }
  while (cur != NULL) {
    tbl = (intnat*) cur->frametable;
    len = *tbl;
    d = (frame_descr *)(tbl + 1);
    for (intnat j = 0; j < len; j++) {
      remove_entry(table, d);
      d = next_frame_descr(d);
    }
    decrease += len;
    rem = cur;
    cur = cur->next;
    caml_stat_free(rem);
  }
  table->num_descr -= decrease;
  table->zombies = NULL;
}

static void add_frame_descriptors(
  caml_frame_descrs *table,
  caml_frametable_list *new_frametables)
{
  CAMLassert(new_frametables != NULL);

  ensure_heap_descriptors(table);

  caml_frametable_list *tail = frametables_list_tail(new_frametables);
  intnat increase = count_descriptors(new_frametables);
  intnat tblsize = capacity(*table);

  /* The size of the hashtable is a power of 2 that must remain
     greater or equal to 2 times the number of descriptors. */

  /* Reallocate the caml_frame_descriptor table if it is too small */
  if(tblsize < (table->num_descr + increase) * 2) {

    /* Merge both lists */
    tail->next = table->frametables;
    table->frametables = NULL;

    intnat num_descr = table->num_descr + increase;

    tblsize = 4;
    while (tblsize < 2 * num_descr) tblsize *= 2;

    table->num_descr = num_descr;
    table->mask = tblsize - 1;

    if (table->descriptors != NULL) caml_stat_free(table->descriptors);
    table->descriptors =
      (frame_descr **) caml_stat_calloc_noexc(tblsize, sizeof(frame_descr *));
    if (table->descriptors == NULL) caml_raise_out_of_memory();

    fill_hashtable(table, new_frametables);
  } else {
    table->num_descr += increase;
    fill_hashtable(table, new_frametables);
    tail->next = table->frametables;
  }

  table->frametables = new_frametables;
}

/* protected by STW sections */
static caml_frame_descrs current_frame_descrs =
  { 0, -1, NULL, NULL, NULL, CAML_PLAT_MUTEX_INITIALIZER };

static caml_frametable_list *cons(
  intnat *frametable, caml_frametable_list *tl)
{
  caml_frametable_list *li = caml_stat_alloc(sizeof(caml_frametable_list));
  li->frametable = frametable;
  li->next = tl;
  return li;
}

/* This function not only creates a new caml_frametable_list cell but
   also makes a copy of the new frametable.
   Here, we allocate, in a single malloc call, the space for the cons
   cell and the (appended) frametable copy. This way, we do not have
   to change the code that unregisters the frametable since calling free
   on the cons cell will automatically free the frametable copy at the
   same time.
*/
static caml_frametable_list *copy_cons(
  intnat **frametable, intnat size, caml_frametable_list *tl)
{
  caml_frametable_list *li =
    caml_stat_alloc(sizeof(caml_frametable_list) + size);
  intnat *frametable_copy = (intnat*)(li + 1);
  memcpy(frametable_copy, *frametable, size);
  *frametable = frametable_copy;
  li->frametable = frametable_copy;
  li->next = tl;
  return li;
}

#define FRAME_CACHE_MAGIC 0x32564d5246584f56ull /* "OXFRMV2" */
#define FRAME_BUILD_ID_MAX 64

struct frame_cache_hdr {
  uint64_t magic;
  uint64_t num_descr;
  uint64_t cap;             /* = mask + 1, length of the descriptors array */
  uint64_t checksum;        /* FNV-1a over the [cap] descriptor words */
  uint32_t build_id_len;
  unsigned char build_id[FRAME_BUILD_ID_MAX];
};

/* The ELF GNU build-id of the running executable. Fixed per binary; the strong
   half of the staleness guard (a cache from any other build is rejected). */
struct frame_buildid { unsigned char id[FRAME_BUILD_ID_MAX]; uint32_t len; };

static int frame_buildid_cb(struct dl_phdr_info *info, size_t sz, void *data)
{
  (void) sz;
  struct frame_buildid *out = (struct frame_buildid *) data;
  for (int i = 0; i < info->dlpi_phnum; i++) {
    const ElfW(Phdr) *ph = &info->dlpi_phdr[i];
    if (ph->p_type != PT_NOTE) continue;
    const char *p = (const char *) (info->dlpi_addr + ph->p_vaddr);
    const char *end = p + ph->p_memsz;
    while (p + sizeof(ElfW(Nhdr)) <= end) {
      const ElfW(Nhdr) *n = (const ElfW(Nhdr) *) p;
      const char *name = p + sizeof(*n);
      const char *desc = name + ((n->n_namesz + 3) & ~3u);
      if (n->n_type == NT_GNU_BUILD_ID && n->n_namesz == 4
          && memcmp(name, "GNU", 4) == 0
          && n->n_descsz > 0 && n->n_descsz <= FRAME_BUILD_ID_MAX) {
        memcpy(out->id, desc, n->n_descsz);
        out->len = n->n_descsz;
        return 1;
      }
      p = desc + ((n->n_descsz + 3) & ~3u);
    }
  }
  return 1; /* only the main program (first object) is inspected */
}

static void frame_get_buildid(struct frame_buildid *out)
{
  out->len = 0;
  dl_iterate_phdr(frame_buildid_cb, out);
}

static uint64_t frame_checksum(frame_descr **d, intnat cap)
{
  uint64_t h = 1469598103934665603ull;
  for (intnat i = 0; i < cap; i++)
    h = (h ^ (uint64_t)(uintnat) d[i]) * 1099511628211ull;
  return h;
}

/* Point [current_frame_descrs] at a valid cache file; return 1 on success. Any
   mismatch (magic / build-id / count / size / checksum) returns 0 so the caller
   silently falls back to a normal build. */
static int frame_cache_load(const char *path, caml_frametable_list *fts)
{
  intnat num_descr = count_descriptors(fts);
  int fd = open(path, O_RDONLY);
  if (fd < 0) return 0;
  struct stat st;
  if (fstat(fd, &st) < 0
      || (size_t) st.st_size < sizeof(struct frame_cache_hdr)) {
    close(fd); return 0;
  }
  void *m = mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
  close(fd);
  if (m == MAP_FAILED) return 0;
  struct frame_cache_hdr *h = (struct frame_cache_hdr *) m;
  if (h->cap > (SIZE_MAX - sizeof(*h)) / sizeof(frame_descr *)) {
    munmap(m, st.st_size); return 0; /* prevent size_t overflow of [want] */
  }
  size_t want = sizeof(*h) + (size_t) h->cap * sizeof(frame_descr *);
  struct frame_buildid bid;
  frame_get_buildid(&bid);
  frame_descr **descrs = (frame_descr **) ((char *) m + sizeof(*h));
  if (h->magic != FRAME_CACHE_MAGIC
      || h->num_descr != (uint64_t) num_descr
      || (size_t) st.st_size != want
      || h->build_id_len != bid.len
      || memcmp(h->build_id, bid.id, bid.len) != 0
      || h->checksum != frame_checksum(descrs, (intnat) h->cap)) {
    munmap(m, st.st_size);
    return 0;
  }
  current_frame_descrs.descriptors = descrs;
  current_frame_descrs.mask = (int) (h->cap - 1);
  current_frame_descrs.num_descr = (int) num_descr;
  current_frame_descrs.frametables = fts;
  frame_descrs_from_cache = 1;
  frame_cache_map = m;
  frame_cache_map_len = st.st_size;
  return 1;
}

/* Write the freshly-built table to [path] atomically (temp + rename). Failures
   are silent: caching is best-effort. */
static void frame_cache_store(const char *path)
{
  intnat cap = capacity(current_frame_descrs);
  size_t body = (size_t) cap * sizeof(frame_descr *);
  char tmp[4096];
  if (snprintf(tmp, sizeof(tmp), "%s.tmp.%ld", path, (long) getpid())
      >= (int) sizeof(tmp))
    return;
  int fd = open(tmp, O_WRONLY | O_CREAT | O_TRUNC, 0644);
  if (fd < 0) return;
  struct frame_cache_hdr h;
  memset(&h, 0, sizeof(h));
  h.magic = FRAME_CACHE_MAGIC;
  h.num_descr = (uint64_t) current_frame_descrs.num_descr;
  h.cap = (uint64_t) cap;
  h.checksum = frame_checksum(current_frame_descrs.descriptors, cap);
  struct frame_buildid bid;
  frame_get_buildid(&bid);
  h.build_id_len = bid.len;
  memcpy(h.build_id, bid.id, bid.len);
  int ok = (write(fd, &h, sizeof(h)) == (ssize_t) sizeof(h))
        && (write(fd, current_frame_descrs.descriptors, body) == (ssize_t) body);
  close(fd);
  if (ok) { if (rename(tmp, path) != 0) unlink(tmp); }
  else unlink(tmp);
}

/* Write <dir>[/]ocaml_frametable_<build-id-hex>.cache into [buf]; return 1 on
   success. Keying on the ELF build-id lets many distinct binaries share one cache
   directory without colliding. */
static int frame_buildid_path(char *buf, size_t bufsz, const char *dir)
{
  struct frame_buildid bid;
  frame_get_buildid(&bid);
  if (bid.len == 0) return 0;
  char hex[2 * FRAME_BUILD_ID_MAX + 1];
  for (uint32_t i = 0; i < bid.len; i++)
    snprintf(hex + 2 * i, 3, "%02x", bid.id[i]);
  hex[2 * bid.len] = '\0';
  size_t dlen = strlen(dir);
  const char *sep = (dlen > 0 && dir[dlen - 1] == '/') ? "" : "/";
  if ((size_t) snprintf(buf, bufsz, "%s%socaml_frametable_%s.cache",
                        dir, sep, hex) >= bufsz)
    return 0;
  return 1;
}

/* Resolve the cache path into [buf]; return 1 if caching is enabled.

   OPT-IN: caching is OFF unless CAML_FRAME_CACHE is set, so the compiler's
   default behaviour is byte-for-byte unchanged (fleet enablement is a separate
   env knob — see frame-lazy-findings.md). Values:
     unset / "" / "off" / "none" -> disabled (today's behaviour)
     "auto"                      -> build-id-keyed file under
                                    XDG_CACHE_HOME | TMPDIR | /tmp
     a directory (or trailing /) -> build-id-keyed file in that directory
     any other value             -> used verbatim as the cache file path */
static int frame_cache_path(char *buf, size_t bufsz)
{
  const char *e = getenv("CAML_FRAME_CACHE");
  if (e == NULL || e[0] == '\0'
      || strcmp(e, "off") == 0 || strcmp(e, "none") == 0)
    return 0;
  if (strcmp(e, "auto") == 0) {
    const char *base = getenv("XDG_CACHE_HOME");
    if (base == NULL || base[0] == '\0') base = getenv("TMPDIR");
    if (base == NULL || base[0] == '\0') base = "/tmp";
    return frame_buildid_path(buf, bufsz, base);
  }
  size_t len = strlen(e);
  struct stat st;
  int is_dir = (e[len - 1] == '/')
            || (stat(e, &st) == 0 && S_ISDIR(st.st_mode));
  if (is_dir) return frame_buildid_path(buf, bufsz, e);
  if (len >= bufsz) return 0;
  strcpy(buf, e);
  return 1;
}

/* ------------------------------------------------------------------------- */
/* C1 (bake-frame, task #63): a frame-descriptor table baked into the         */
/* executable at LINK time. The fleet compiler is non-PIE (Type EXEC), so     */
/* every [frame_descr*] is a link-time constant and the ~4 MB hashtable is    */
/* byte-identical across all runs. Rather than rebuild it at every startup     */
/* (~7.5 ms — see frame-lazy-findings.md) we reserve a section in the binary,  */
/* fill it once after linking (a bake step dumps it and objcopy patches it),   */
/* and at startup point [descriptors] straight at the in-image table.          */
/*                                                                            */
/* Safe-by-construction fallback: the reserved section is zero in every        */
/* freshly-linked (unpatched / bootstrap) binary, so [magic] fails to match    */
/* and the runtime rebuilds exactly as today. A relink resets the section to   */
/* zero, so a stale baked table can never survive a rebuild. The bake dump     */
/* reuses the runtime's own [add_frame_descriptors] — no reimplementation of   */
/* the fill logic that could drift.                                            */
/*                                                                            */
/* Guard = magic + runtime-counted num_descr + ELF build-id + cap-fits (all    */
/* O(1)/O(build-id)). Unlike the C2 file cache there is no foreign file to     */
/* mistrust: the build-id note ties the baked table to this exact binary, so   */
/* the full-4 MB FNV checksum is NOT walked by default — startup then faults    */
/* in only the buckets actually probed (true lazy fault, lower RSS). The       */
/* checksum is still stored and verified on demand via CAML_FRAME_BAKE_VERIFY. */

#define FRAME_BAKED_MAGIC 0x314b425846584f56ull /* "VOXFBK1" */
#define FRAME_BAKED_BODY_OFF 4096u               /* body page-aligned for faulting */
#define FRAME_BAKED_CAP_MAX (1u << 19)           /* 524288 slots = 4 MB */
#define FRAME_BAKED_RESERVE \
  (FRAME_BAKED_BODY_OFF + FRAME_BAKED_CAP_MAX * sizeof(frame_descr *))

/* The reserved section. Zero-initialised into a named section => PROGBITS
   (file-backed with zeros in a freshly-linked binary). The post-link bake step
   overwrites it in place with [objcopy --update-section] (same size => no ELF
   relayout, build-id note preserved). Non-const/non-static so the compiler
   never assumes the zero initialiser survives (objcopy rewrites it) and so
   [objcopy] can address the section by name. */
__attribute__((section(".caml_frametable_baked"), aligned(4096)))
unsigned char caml_baked_frametable[FRAME_BAKED_RESERVE];

/* Point [current_frame_descrs] at the baked in-image table; return 1 on a
   validated hit. Any mismatch returns 0 so the caller rebuilds normally. */
static int frame_baked_load(caml_frametable_list *fts, int verify)
{
  struct frame_cache_hdr *h =
    (struct frame_cache_hdr *) (void *) caml_baked_frametable;
  if (h->magic != FRAME_BAKED_MAGIC) return 0;
  intnat num_descr = count_descriptors(fts);
  if (h->num_descr != (uint64_t) num_descr) return 0;
  if (h->cap == 0 || (h->cap & (h->cap - 1)) != 0) return 0; /* power of 2 */
  if (FRAME_BAKED_BODY_OFF + h->cap * sizeof(frame_descr *) > FRAME_BAKED_RESERVE)
    return 0;
  struct frame_buildid bid;
  frame_get_buildid(&bid);
  if (h->build_id_len != bid.len
      || memcmp(h->build_id, bid.id, bid.len) != 0)
    return 0;
  frame_descr **descrs =
    (frame_descr **) (void *) (caml_baked_frametable + FRAME_BAKED_BODY_OFF);
  if (verify && h->checksum != frame_checksum(descrs, (intnat) h->cap))
    return 0;
  current_frame_descrs.descriptors = descrs;
  current_frame_descrs.mask = (int) (h->cap - 1);
  current_frame_descrs.num_descr = (int) num_descr;
  current_frame_descrs.frametables = fts;
  frame_descrs_from_cache = 1; /* copy-out-on-mutation via ensure_heap_descriptors */
  return 1;
}

/* Bake step: serialize the freshly-built table into [path] as the exact
   FRAME_BAKED_RESERVE-byte section image (header at offset 0, descriptors[] at
   FRAME_BAKED_BODY_OFF, zero-padded to the reserve). objcopy --update-section
   then patches this into the binary. Failures are reported but non-fatal. */
static void frame_baked_dump(const char *path)
{
  intnat cap = capacity(current_frame_descrs);
  if (FRAME_BAKED_BODY_OFF + (size_t) cap * sizeof(frame_descr *)
      > FRAME_BAKED_RESERVE) {
    fprintf(stderr,
            "[frame] bake: table (cap=%ld) exceeds reserve %zu — not baked\n",
            (long) cap, (size_t) FRAME_BAKED_RESERVE);
    return;
  }
  unsigned char *img =
    (unsigned char *) caml_stat_calloc_noexc(FRAME_BAKED_RESERVE, 1);
  if (img == NULL) return;
  struct frame_cache_hdr *h = (struct frame_cache_hdr *) (void *) img;
  h->magic = FRAME_BAKED_MAGIC;
  h->num_descr = (uint64_t) current_frame_descrs.num_descr;
  h->cap = (uint64_t) cap;
  h->checksum = frame_checksum(current_frame_descrs.descriptors, cap);
  struct frame_buildid bid;
  frame_get_buildid(&bid);
  h->build_id_len = bid.len;
  memcpy(h->build_id, bid.id, bid.len);
  memcpy(img + FRAME_BAKED_BODY_OFF, current_frame_descrs.descriptors,
         (size_t) cap * sizeof(frame_descr *));
  int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
  int ok = 0;
  if (fd >= 0) {
    ok = (write(fd, img, FRAME_BAKED_RESERVE) == (ssize_t) FRAME_BAKED_RESERVE);
    close(fd);
  }
  caml_stat_free(img);
  if (!ok) fprintf(stderr, "[frame] bake: failed to write %s\n", path);
}

void caml_init_frame_descriptors(void)
{
  caml_frametable_list *frametables = NULL;
  for (int i = 0; caml_frametable[i] != 0; i++)
    frametables = cons(caml_frametable[i], frametables);

  /* `init_frame_descriptors` is called from `init_gc`, before
     any mutator can run. We can mutate [current_frame_descrs]
     at will. */
  const char *fstats = getenv("CAML_FRAME_STATS");
  const char *fbake = getenv("CAML_FRAME_BAKE");
  int bake_verify = getenv("CAML_FRAME_BAKE_VERIFY") != NULL;
  struct timespec t0, t1;
  if (fstats) clock_gettime(CLOCK_MONOTONIC, &t0);
  int hit = 0;
  /* C1: the link-time baked table takes precedence (zero-config, no file I/O).
     In bake mode we always build fresh so the dump reflects this binary. */
  if (fbake == NULL) hit = frame_baked_load(frametables, bake_verify);
  if (!hit) {
    char path[4096];
    int use_cache = frame_cache_path(path, sizeof(path)); /* C2 file cache */
    if (use_cache) hit = frame_cache_load(path, frametables);
    if (!hit) {
      add_frame_descriptors(&current_frame_descrs, frametables);
      if (use_cache) frame_cache_store(path);
    }
  }
  if (fbake) frame_baked_dump(fbake);
  if (fstats) {
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double ms = (t1.tv_sec - t0.tv_sec) * 1000.0
              + (t1.tv_nsec - t0.tv_nsec) / 1e6;
    fprintf(stderr, "[frame] hit=%d num_descr=%d cap=%d init=%.3fms\n",
            hit, current_frame_descrs.num_descr,
            current_frame_descrs.mask + 1, ms);
  }
  /* Bake mode: the section image is dumped; exit before running any mutator.
     _exit avoids atexit handlers touching the half-initialised runtime. */
  if (fbake) { fflush(NULL); _exit(0); }
}

static void register_frametables_from_stw_single(
  caml_frametable_list *new_frametables)
{
  clean_frame_descriptors(&current_frame_descrs);
  add_frame_descriptors(&current_frame_descrs, new_frametables);
}

static void stw_register_frametables(
    caml_domain_state* domain,
    void* frametables,
    int participating_count,
    caml_domain_state** participating)
{
  Caml_global_barrier_if_final(participating_count) {
    register_frametables_from_stw_single((caml_frametable_list *) frametables);
  }
}

void caml_register_frametables(void **table, int ntables) {
  caml_frametable_list *new_frametables = NULL;
  for (int i = 0; i < ntables; i++)
    new_frametables = cons(table[i], new_frametables);

  do {} while (!caml_try_run_on_all_domains(
                 &stw_register_frametables, new_frametables, 0));
}

void caml_copy_and_register_frametables(
  void **table, int * sizes, int ntables)
{
  caml_frametable_list *new_frametables = NULL;
  for (int i = 0; i < ntables; i++)
    new_frametables = copy_cons((intnat **)(table + i),
                                sizes[i], new_frametables);

  do {} while (!caml_try_run_on_all_domains(
                 &stw_register_frametables, new_frametables, 0));
}

static void remove_frame_descriptors(
  caml_frame_descrs * table, void ** frametables, int ntables)
{
  void *frametable;
  caml_frametable_list ** previous;

  /* cannot release the domain lock here (e.g. custom block finaliser) */
  caml_plat_lock_blocking(&table->mutex);

  previous = &table->frametables;

  iter_list(table->frametables, current) {
  resume:
    for (int i = 0; i < ntables; i++) {
      if (current->frametable == frametables[i]) {
        *previous = current->next;
        current->next = table->zombies;
        table->zombies = current;
        ntables--;
        if (ntables == 0) goto release;
        current = *previous;
        frametable = frametables[i];
        frametables[i] = frametables[ntables];
        frametables[ntables] = frametable;
        goto resume;
      }
    }
    previous = &current->next;
  }

 release:
  caml_plat_unlock(&table->mutex);
}

void caml_unregister_frametables(void ** frametables, int ntables)
{
  remove_frame_descriptors(&current_frame_descrs, frametables, ntables);
}

void caml_register_frametable(void * frametables)
{
  caml_register_frametables(&frametables, 1);
}

void* caml_copy_and_register_frametable(void * frametable, int size)
{
  caml_copy_and_register_frametables(&frametable, &size, 1);
  return frametable;
}

void caml_unregister_frametable(void * frametables)
{
  caml_unregister_frametables(&frametables, 1);
}

caml_frame_descrs* caml_get_frame_descrs(void)
{
  return &current_frame_descrs;
}

frame_descr* caml_find_frame_descr(caml_frame_descrs *fds, uintnat pc)
{
  frame_descr * d;
  uintnat h;

  h = Hash_retaddr(pc, fds->mask);
  while (1) {
    d = fds->descriptors[h];
    if (d == 0) return NULL; /* can happen if some code compiled without -g */
    if (Retaddr_frame(d) == pc) break;
    h = (h+1) & fds->mask;
  }
  return d;
}
