/**************************************************************************/
/*                                                                        */
/*                                 OCaml                                  */
/*                                                                        */
/*      KC Sivaramakrishnan, Indian Institute of Technology, Madras       */
/*                   Tom Kelly, OCaml Labs Consultancy                    */
/*                 Stephen Dolan, University of Cambridge                 */
/*                                                                        */
/*   Copyright 2019 Indian Institute of Technology, Madras                */
/*   Copyright 2021 OCaml Labs Consultancy Ltd                            */
/*   Copyright 2019 University of Cambridge                               */
/*                                                                        */
/*   All rights reserved.  This file is distributed under the terms of    */
/*   the GNU Lesser General Public License version 2.1, with the          */
/*   special exception on linking described in the file LICENSE.          */
/*                                                                        */
/**************************************************************************/

#ifndef _GNU_SOURCE
#define _GNU_SOURCE /* for dl_iterate_phdr (ELF build-id) */
#endif

#define CAML_INTERNALS

#include "caml/platform.h"
#include "caml/frame_descriptors.h"
#include "caml/major_gc.h" /* for caml_major_cycles_completed */
#include "caml/memory.h"
#include "caml/fail.h"
#include "caml/shared_heap.h"
#include "caml/backtrace_prim.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined(__ELF__)
/* The bake/load fast path is ELF-only (weak-symbol section reserve); its
   file I/O and timing helpers are POSIX. Non-ELF targets compile none of
   it and always take the rebuild path below. */
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <link.h>
#include "caml/osdeps.h" /* caml_secure_getenv */
#endif

/* A short descriptor does not carry its own return address (it is
   reconstructed by walking the delta chain when a frametable is
   registered), so each hash-table slot stores the absolute return
   address alongside the descriptor-body pointer. An empty slot has
   [fd == NULL]. */
typedef struct {
  uintnat retaddr;
  frame_descr *fd;
} frame_descr_entry;

struct caml_frame_descrs {
  int num_descr;
  int mask;
  frame_descr_entry *descriptors;
  caml_frametable_list *frametables;
  caml_frametable_list *zombies;
  caml_plat_mutex mutex;
};
/* Let us call 'capacity' the length of the descriptors array.

   We maintain the following invariants:
     capacity = mask + 1
     capacity = 0 || Is_power_of_2(capacity)
     num_desc <= 2 * num_descr <= capacity

   For an extensible array we would maintain
      num_desc <= capacity,
    but this is a linear-problem hash table, we need to ensure that
    free slots are frequent enough, so we use a twice-larger capacity:
      num_desc * 2 <= capacity

   We keep the list of frametables that was used to build the hashtable.
   We use it when rebuilding the table after resizing.

   We keep the list of frametables which need to be removed (zombies).
   We remove them in a STW handler before any new addition.

   We allow the user to call functions for frametable removal at any
   time, even inside a STW section (e.g. during custom block finalization).
   To this end, we use a mutex to protect the frametable insertions in
   the zombies list.

   All other modifications should only happen in a STW section.
*/

/* Defined in code generated by ocamlopt */
extern intnat * caml_frametable[];

/* Link-time baked frame-descriptor table. A non-PIE binary has a fixed load
   address, so every [frame_descr*] sits at an identical absolute address in
   every process: the hashtable is a pure function of the linked binary.
   Binaries that opt in link caml_frame_bake_reserve.o, which carries a
   zero-filled PROGBITS section [.caml_frametable_baked]; a post-link step
   (tools/bake_frame_table.sh) fills it with the fully-built table, and at
   startup [frame_baked_load] points [descriptors] straight at the in-image
   array instead of rebuilding it (~7.5 ms on the fleet compiler).

   The baked section lives in the binary image (it is writable, like any
   PROGBITS data, but treated as frozen); the first runtime frametable
   registration/removal (e.g. Dynlink) copies the array out to the heap
   before mutating it ([ensure_heap_descriptors]). Staleness is guarded by
   the GNU build-id plus a load-bias anchor; any mismatch, or a binary
   without the reserve (the weak symbol resolves to NULL), falls back to the
   normal rebuild. */
static int frame_descrs_from_cache = 0;

/* Note: [cur] is bound by this macro */
#define iter_list(list,cur) \
  for (caml_frametable_list *cur = list; cur != NULL; cur = cur->next)

/* Decode one descriptor (short or escaped) into [out], filling in its
   flags, sizes, and the pointers needed to locate its live offsets,
   allocation sizes, and debug words. [d] points at the descriptor body:
   the byte after its LEB128 delta (short), or the escape byte itself
   (medium/long). */
void caml_decode_frame_descr(frame_descr *d, struct frame_descr_decoded *out)
{
  memset(out, 0, sizeof(*out));
  if (frame_is_short(d)) {
    const unsigned char *p = (const unsigned char *)d;
    unsigned char sf = *p++; /* size+flags byte */
    out->is_short = true;
    out->has_allocs = (sf & FRAME_DESCRIPTOR_ALLOC) != 0;
    out->has_debug = (sf & FRAME_DESCRIPTOR_DEBUG) != 0;
    out->frame_size = ((uint32_t)(sf >> 2)) * 16;
    if (out->has_allocs) {
      out->short_reg_bitmap = *p++;
      out->num_allocs = *p++;
      out->short_allocs = p;
      p += (out->num_allocs + 1) / 2; /* 4-bit alloc sizes */
    }
    out->short_live_bytes =
      (uint8_t)((out->frame_size / sizeof(value) + 7) / 8);
    out->short_live = p;
    p += out->short_live_bytes;
    out->end_of_live = p;
    out->num_debuginfo = out->has_allocs ? out->num_allocs : 1;
    if (out->has_debug) {
      p += sizeof(uint32_t) * out->num_debuginfo;
    }
    out->end = p;
    return;
  }

  /* Escaped descriptor: normal or long format. */
  if (frame_return_to_C(d)) {
    out->return_to_C = true;
    /* Top of an ML stack chunk: an empty descriptor. */
    CAMLassert(caml_read_unaligned_uint16(d + Frame_num_live_ofs) == 0);
    out->end_of_live = out->end = d + Frame_live_ofs;
    return;
  }
  out->is_long = frame_is_long(d);
  out->has_allocs = frame_has_allocs(d);
  out->has_debug = frame_has_debug(d);
  out->frame_size = frame_size(d);
  const unsigned char *p;
  if (out->is_long) {
    out->num_live = caml_read_unaligned_uint32(d + Frame_long_num_live_ofs);
    p = d + Frame_long_live_ofs + (uintnat)out->num_live * sizeof(uint32_t);
  } else {
    out->num_live = caml_read_unaligned_uint16(d + Frame_num_live_ofs);
    p = d + Frame_live_ofs + (uintnat)out->num_live * sizeof(uint16_t);
  }
  out->end_of_live = p;
  out->num_debuginfo = 1;
  if (out->has_allocs) {
    out->num_allocs = *p;
    out->num_debuginfo = *p;
    p += (uintnat)(*p) + 1; /* num_allocs byte + one byte per alloc */
  }
  if (out->has_debug) {
    p += sizeof(uint32_t) * out->num_debuginfo;
  }
  out->end = p;
}

/* Iterate over the descriptors of one frametable, reconstructing the
   absolute return address of each descriptor by walking the delta chain.
   An escaped descriptor carries an absolute return address (retaddr_rel);
   a short descriptor's address is the running address plus its delta. */
typedef struct {
  const unsigned char *next; /* points at the next descriptor's delta byte */
  uintnat retaddr;           /* running absolute return address */
  intnat remaining;          /* descriptors left to yield */
} frametable_iter;

static void frametable_iter_start(frametable_iter *it, intnat *tbl)
{
  it->remaining = (intnat)caml_read_unaligned_uintnat(tbl);
  it->next = (const unsigned char *)(tbl + 1);
  it->retaddr = 0;
}

/* Yield the next descriptor body and its absolute return address. Must
   only be called while [it->remaining > 0]. */
static frame_descr *frametable_iter_next(frametable_iter *it,
                                         uintnat *retaddr_out)
{
  const unsigned char *p = it->next;
  frame_descr *d;
  if (*p == FRAME_DELTA_ESCAPE) {
    d = (frame_descr *)p;
    it->retaddr = Retaddr_frame(d);
  } else {
    /* Unsigned LEB128 delta (>= 1, so it never starts with a 0 byte). */
    uintnat delta = 0;
    int shift = 0;
    unsigned char byte;
    do {
      byte = *p++;
      delta |= (uintnat)(byte & 0x7f) << shift;
      shift += 7;
    } while (byte & 0x80);
    it->retaddr += delta;
    d = (frame_descr *)p;
  }
  struct frame_descr_decoded dec;
  caml_decode_frame_descr(d, &dec);
  it->next = dec.end;
  it->remaining--;
  *retaddr_out = it->retaddr;
  return d;
}

static intnat count_descriptors(caml_frametable_list *list) {
  intnat num_descr = 0;
  iter_list(list,cur) {
    num_descr += (intnat)caml_read_unaligned_uintnat(cur->frametable);
  }
  return num_descr;
}

static caml_frametable_list* frametables_list_tail(caml_frametable_list *list) {
  caml_frametable_list *tail = NULL;
  iter_list(list,cur) {
    tail = cur;
  }
  return tail;
}

static int capacity(caml_frame_descrs table) {
  int capacity = table.mask + 1;
  CAMLassert(capacity == 0 || Is_power_of_2(capacity));
  return capacity;
}

static void fill_hashtable(
  caml_frame_descrs *table, caml_frametable_list *new_frametables)
{
  iter_list(new_frametables,cur) {
    frametable_iter it;
    frametable_iter_start(&it, (intnat *) cur->frametable);
    while (it.remaining > 0) {
      uintnat retaddr;
      frame_descr *d = frametable_iter_next(&it, &retaddr);
      uintnat h = Hash_retaddr(retaddr, table->mask);
      while (table->descriptors[h].fd != NULL) {
        h = (h+1) & table->mask;
      }
      table->descriptors[h].retaddr = retaddr;
      table->descriptors[h].fd = d;
    }
  }
}

static void remove_entry(caml_frame_descrs *table, uintnat retaddr,
                         frame_descr * d) {
  uintnat i;
  uintnat r;
  uintnat j;

  i = Hash_retaddr(retaddr, table->mask);
  while (table->descriptors[i].fd != d) {
    i = (i+1) & table->mask;
  }

 r1:
  j = i;
  table->descriptors[i].fd = NULL;
 r2:
  i = (i+1) & table->mask;
  // r3
  if(table->descriptors[i].fd == NULL) return;
  r = Hash_retaddr(table->descriptors[i].retaddr, table->mask);
  /* If r is between i and j (cyclically), i.e. if
     table->descriptors[i]->retaddr don't need to be moved */
  if(( ( j < r )  && ( r <= i ) ) ||
     ( ( i < j )  && ( j < r )  ) ||      /* i cycled, r not */
     ( ( r <= i ) && ( i < j ) )     ) {  /* i and r cycled */
    goto r2;
  }
  // r4
  table->descriptors[j] = table->descriptors[i];
  goto r1;
}

/* If [descriptors] currently points into the baked in-image section, copy
   it out to a heap array before any mutation (registration/removal); the
   section is treated as frozen even though it is technically writable.
   After this the table behaves exactly as a normally-built one. */
static void ensure_heap_descriptors(caml_frame_descrs *table)
{
  if (!frame_descrs_from_cache) return;
  intnat tblsize = capacity(*table);
  frame_descr **heap =
    (frame_descr **) caml_stat_calloc_noexc(tblsize, sizeof(frame_descr *));
  if (heap == NULL) caml_raise_out_of_memory();
  memcpy(heap, table->descriptors, tblsize * sizeof(frame_descr *));
  table->descriptors = heap;
  frame_descrs_from_cache = 0;
  /* The baked section stays in the image untouched for the rest of the
     process; only the heap copy is mutated from here on. */
}

static void clean_frame_descriptors(caml_frame_descrs *table)
{
  intnat decrease = 0;
  caml_frametable_list *cur = table->zombies, *rem;
  if (cur != NULL) {
    /* About to free frametables: if [descriptors] still points into the
       baked section, copy it out before [remove_entry] mutates it. */
    ensure_heap_descriptors(table);
  }
  while (cur != NULL) {
    frametable_iter it;
    frametable_iter_start(&it, (intnat *) cur->frametable);
    intnat len = it.remaining;
    while (it.remaining > 0) {
      uintnat retaddr;
      frame_descr *d = frametable_iter_next(&it, &retaddr);
      remove_entry(table, retaddr, d);
    }
    decrease += len;
    rem = cur;
    cur = cur->next;
    caml_stat_free(rem);
  }
  table->num_descr -= decrease;
  table->zombies = NULL;
}

/* ---- Frametable measurement ---- */

/* As preparation for designing a more memory-efficient frametable
 * format, this code measures various things about the frametables of
 * an executable. It decodes both short and escaped ("medium"/"long")
 * descriptors compatibly, via caml_decode_frame_descr.
 *
 * Settable via GC tweak OCAMLRUNPARAM=Xmeasure_frametables (the
 * frametables registered in this batch). */

extern uintnat caml_measure_frametables;

#define MAX_LOG 32
#define SMALL_FRAMES 32
#define REGS 64
#define MAX_REG (REGS - 1) /* Largest register index recorded in reg tables */
#define MAX_REG_IN_SMALL_MAP 12

/* Why an escaped descriptor could not use the short format. [ESC_FITS] means
   its content is short-compatible, so it escaped only for a positional reason
   (a function / text-section boundary). Values are declared in reporting
   order: cases we expect on real binaries first (cold register last of
   those), then cases we expect never to see. */
enum escape_reason {
  ESC_BADSIZE,      /* frame size 0, > 1008, or not a multiple of 16 */
  ESC_BIGALLOC,     /* an allocation size that does not fit a 4-bit nibble */
  ESC_FT_FIRST,     /* first in its frametable: always escapes; positional,
                       so never returned by classify_escape */
  ESC_FITS,         /* short-compatible: escaped only for a boundary */
  ESC_COLDREG,      /* a live register outside the 8 hot registers */
  ESC_LONG,         /* long (32-bit) descriptor */
  ESC_BADSLOT,      /* a live stack slot is not word-aligned */
  ESC_SLOTBEYOND,   /* a live stack slot outside the frame (stack argument) */
  ESC_NOALLOC_REGS, /* non-allocation descriptor with live registers */
  ESC_MANYALLOCS,   /* more than 255 allocations (comballoc) */
  NUM_ESCAPE_REASONS
};

static const char *const escape_names[NUM_ESCAPE_REASONS] = {
  [ESC_BADSIZE]      = "bad frame size",
  [ESC_BIGALLOC]     = "alloc too large",
  [ESC_FT_FIRST]     = "first in frametable",
  [ESC_FITS]         = "fits (section boundary)",
  [ESC_COLDREG]      = "cold register",
  [ESC_LONG]         = "long descriptor",
  [ESC_BADSLOT]      = "unaligned stack slot",
  [ESC_SLOTBEYOND]   = "stack slot outside frame",
  [ESC_NOALLOC_REGS] = "non-alloc with live registers",
  [ESC_MANYALLOCS]   = "> 255 allocations",
};

struct frametable_stats {
  /* A few per-frametable items */
  unsigned char *last_retaddr;
  unsigned char *min_retaddr;
  unsigned char *max_retaddr;
  unsigned char *min_descr;
  unsigned char *max_descr;
  size_t descrs;

  /* Everything else is accumulated over all frametables */
  size_t frametables;
  size_t total_codesize;
  size_t total_ft_size;
  size_t total_debuginfo_size;
  size_t total_descrs;
  size_t total_debuginfo;

  /* Are frametables in memory before or after the code they describe? */
  size_t ft_before_code;
  size_t ft_after_code;

  /* Descriptor kinds */
  size_t return_to_C;
  size_t with_debug;
  size_t with_alloc;
  size_t short_descrs;
  size_t medium_descrs;
  size_t long_descrs;

  /* Why escaped (non-short) descriptors could not use the short format,
     indexed by enum escape_reason. [ESC_FITS] entries are short-compatible
     and so escaped only for a function / text-section boundary -- the
     descriptors a cross-function delta chain could reclaim. */
  size_t escape_reason[NUM_ESCAPE_REASONS];

  /* Frame sizes */
  size_t small_frames[SMALL_FRAMES];
  size_t log_framesize[MAX_LOG];
  size_t max_framesize;

  /* Relative return addresses */
  size_t log_pos_retaddr_rel[MAX_LOG];
  size_t max_pos_retaddr_rel;
  size_t log_neg_retaddr_rel[MAX_LOG];
  size_t max_neg_retaddr_rel;

  /* Delta from one retaddr to the next */
  size_t log_pos_delta[MAX_LOG];
  size_t max_pos_delta;
  size_t log_neg_delta[MAX_LOG];
  size_t max_neg_delta;

  /* Counts of "live" values (GC regs + slots) */
  size_t small_lives[SMALL_FRAMES];
  size_t log_lives[MAX_LOG];
  size_t max_lives; /* Overall maximum count of lives */

  /* GCable registers */
  size_t reg[REGS]; /* # descriptors using each register */
  size_t reg_count[REGS]; /* Count GCable registers */
  size_t max_regs;
  size_t max_reg[REGS];  /* Count max GCable register index */
  size_t big_reg_descrs; /* Descrs with a register > MAX_REG_IN_SMALL_MAP */
  size_t big_reg_entries; /* live register entries with number > MAX_REG */
  size_t noalloc_with_regs; /* Non-alloc descrs that have registers (anomaly) */

  /* Count of GCable stack slots */
  size_t small_slots[SMALL_FRAMES];
  size_t log_slots[MAX_LOG];
  size_t max_slots;

  /* maximum GCable stack slot offset */
  size_t small_max_slot[SMALL_FRAMES];
  size_t log_max_slot[MAX_LOG];
  size_t max_slot;

  /* Comballoc allocation counts */
  size_t log_comballocs[MAX_LOG];
  size_t small_comballocs[SMALL_FRAMES];
  size_t max_comballocs;

  /* allocation sizes */
  size_t alloc_sizes;
  size_t log_alloc_sizes[MAX_LOG];
  size_t small_alloc_sizes[SMALL_FRAMES];
  size_t max_alloc_size;
};

static void clear_stats(struct frametable_stats *stats)
{
  caml_debuginfo_reset();
  memset(stats, 0, sizeof(*stats));
}

static void clear_per_frametable_stats(struct frametable_stats *stats)
{
  stats->min_retaddr = stats->max_retaddr = stats->last_retaddr =
    stats->min_descr = stats->max_descr = NULL;
  stats->descrs = 0;
  caml_debuginfo_reset();
}

/* Turn `val` into a string representing that number of bytes */

static void report_bytes(char *buf, size_t space, size_t val)
{
  if (val < 1024) {
    snprintf(buf, space, "%zu", val);
  } else {
    char suffix[] = " kMGTE";
    double scaled = val;
    char *p = suffix;
    while(scaled > 1000 && *p) {
      scaled /= 1024.0;
      ++p;
    }
    snprintf(buf, space, "%.2f %ciB", scaled, *p);
  }
}

/* Write text showing an array `vals` of `count` size_t values,
 * without trailing zero values, into `buf` (size `space` bytes). */

/* This works for regs and logs and smalls */
#define TABLE_BUF_SIZE (REGS * 16)

static void report_table(char *fmt, size_t *vals, size_t count)
{
  char buf[TABLE_BUF_SIZE];
  size_t space = TABLE_BUF_SIZE;

  size_t max = count - 1;
  while(max && vals[max] == 0) {
    --max;
  }
  char *p = buf;
  for (size_t i = 0; i <= max; ++i) {
    int len = snprintf(p, space, "%zu ", vals[i]);
    if (len > space) { /* truncated, replace with ... */
      p[space-4] = p[space-3] = p[space-2] = '.';
      p[space-1] = '\0';
      return;
    }
    space -= len;
    p += len;
  }
  printf(fmt, buf);
}

/* At the end of a single frametable, deduce per-frametable sizes and
 * add them to global stats. */

static void accumulate_frametable_stats(intnat *frametable,
                                        struct frametable_stats *stats)
{
  char *debuginfo_low, *debuginfo_high;
  size_t debuginfo_count;
  caml_debuginfo_measurements(&debuginfo_count,
                              &debuginfo_low,
                              &debuginfo_high);
  /* round debuginfo_high up to word boundary */
  debuginfo_high = Align_to(debuginfo_high, uintnat);
  stats->total_codesize += (stats->max_retaddr - stats->min_retaddr);
  stats->total_ft_size += (stats->max_descr - stats->min_descr);
  /* Debuginfo bytes = the span bracketing the record and jump words and the
     name_info/name_and_loc_info structs (counting record words would multiply
     out suffix sharing). The deduped filename/defname strings live in a
     separate section and are not attributed to a frametable here. */
  stats->total_debuginfo_size += (debuginfo_high - debuginfo_low);
  stats->total_descrs += stats->descrs;
  stats->total_debuginfo += debuginfo_count;
  if (stats->min_retaddr) {
    if (stats->min_retaddr > stats->min_descr)
      ++ stats->ft_before_code;
    else
      ++ stats->ft_after_code;
  }
}

/* Is [reg] one of the eight hot registers the short format can encode? */

static bool reg_is_hot(size_t reg)
{
  for (int i = 0; i < FRAME_NUM_HOT_REGS; ++i) {
    if (caml_frame_hot_regs[i] == reg) {
      return true;
    }
  }
  return false;
}

/* Report all accumulated frametable stats to stdout. */

static void report_stats(struct frametable_stats *stats)
{
  char table_buf[TABLE_BUF_SIZE];

  size_t total_size =
    stats->total_codesize
    + stats->total_ft_size
    + stats->total_debuginfo_size;
  printf("Summary of %zu frametables.\n", stats->frametables);
  report_bytes(table_buf, TABLE_BUF_SIZE, stats->total_codesize);
  printf("%s code (%5.2f%%)\n", table_buf,
         (double)stats->total_codesize/total_size * 100.0);
  report_bytes(table_buf, TABLE_BUF_SIZE, stats->total_ft_size);
  printf("%s descriptors (%5.2f%%; %zu descrs, %f bytes each)\n",
         table_buf,
         (double)stats->total_ft_size/total_size * 100.0,
         stats->total_descrs,
         (double)stats->total_ft_size / stats->total_descrs);
  report_bytes(table_buf, TABLE_BUF_SIZE, stats->total_debuginfo_size);
  printf("%s Debuginfo (%5.2f%% %zu entries)\n",
         table_buf,
         (double)stats->total_debuginfo_size/total_size * 100.0,
         stats->total_debuginfo);
  printf("%zu frametables before code, %zu after code.\n",
         stats->ft_before_code, stats->ft_after_code);
  printf("short %zu medium %zu long %zu return to C %zu alloc %zu debug %zu\n",
         stats->short_descrs, stats->medium_descrs, stats->long_descrs,
         stats->return_to_C, stats->with_alloc, stats->with_debug);

  {
    size_t total_escapes = 0;
    for (int i = 0; i < NUM_ESCAPE_REASONS; ++i) {
      total_escapes += stats->escape_reason[i];
    }
    printf("Escaped descriptors\n");
    for (int i = 0; i < NUM_ESCAPE_REASONS; ++i) {
      printf("  %-33s %9zu (%4.1f%%)\n", escape_names[i],
             stats->escape_reason[i],
             total_escapes
               ? 100.0 * stats->escape_reason[i] / total_escapes : 0.0);
    }
    printf("%35s %9zu (%.1f%%)\n", "Total:", total_escapes,
           stats->total_descrs
             ? 100.0 * total_escapes / stats->total_descrs : 0.0);
  }

  printf("Max pos retaddr offset %zu\n", stats->max_pos_retaddr_rel);
  report_table("  (logs %s)\n", stats->log_pos_retaddr_rel, MAX_LOG);
  printf("Max neg retaddr offset %zu\n", stats->max_neg_retaddr_rel);
  report_table("  (logs %s)\n", stats->log_neg_retaddr_rel, MAX_LOG);
  printf("Max retaddr pos delta %zu\n", stats->max_pos_delta);
  report_table("  (logs %s)\n", stats->log_pos_delta, MAX_LOG);
  printf("Max retaddr neg delta %zu\n", stats->max_neg_delta);
  report_table("  (logs %s)\n", stats->log_neg_delta, MAX_LOG);

  printf("Frame sizes (max %zu)\n", stats->max_framesize);
  report_table("  (small %s)\n", stats->small_frames, SMALL_FRAMES);
  report_table("  (logs %s)\n", stats->log_framesize, MAX_LOG);

  printf("Comballoc entries (max %zu)\n",
         stats->max_comballocs);
  report_table("  (small %s)\n", stats->small_comballocs, SMALL_FRAMES);
  report_table("  (logs %s)\n", stats->log_comballocs, MAX_LOG);

  printf("Allocation sizes (wosize-1) (%zu allocs, max %zu)\n",
         stats->alloc_sizes, stats->max_alloc_size);
  report_table("  (small %s)\n", stats->small_alloc_sizes, SMALL_FRAMES);
  report_table("  (logs %s)\n", stats->log_alloc_sizes, MAX_LOG);

  printf("GC live values (max %zu)\n", stats->max_lives);
  report_table("  (small %s)\n", stats->small_lives, SMALL_FRAMES);
  report_table("  (logs %s)\n", stats->log_lives, MAX_LOG);

  printf("GCable stack slots (max %zu)\n", stats->max_slots);
  report_table("  (small %s)\n", stats->small_slots, SMALL_FRAMES);
  report_table("  (logs %s)\n", stats->log_slots, MAX_LOG);

  printf("Max GCable stack slot (max %zu)\n", stats->max_slot);
  report_table("  (small %s)\n", stats->small_max_slot, SMALL_FRAMES);
  report_table("  (logs %s)\n", stats->log_max_slot, MAX_LOG);

  printf("GCable registers (max %zu)\n", stats->max_regs);
  report_table("  (counts %s)\n", stats->reg_count, REGS);
  report_table("  (each reg %s)\n", stats->reg, REGS);
  report_table("  (max %s)\n", stats->max_reg, REGS);

  printf("Descriptors with a register > %d: %zu\n",
         MAX_REG_IN_SMALL_MAP, stats->big_reg_descrs);
  printf("live register entries with number > %d: %zu\n",
         MAX_REG, stats->big_reg_entries);
  printf("Non-allocation descriptors with registers: %zu\n",
         stats->noalloc_with_regs);

  {
    /* The FRAME_NUM_HOT_REGS most-used registers (ties kept in the current
       hot set), as lines to paste into runtime/caml/frame_descriptors.h and
       backend/<arch>/arch.ml -- or a note that no change is warranted. */
    bool chosen[REGS] = { false };
    bool same = true;
    const char *sep;
    for (int k = 0; k < FRAME_NUM_HOT_REGS; ++k) {
      int best = -1;
      for (int r = 0; r < REGS; ++r) {
        if (chosen[r]) continue;
        if (best < 0 || stats->reg[r] > stats->reg[best]
            || (stats->reg[r] == stats->reg[best]
                && reg_is_hot(r) && !reg_is_hot(best)))
          best = r;
      }
      chosen[best] = true;
    }
    for (int r = 0; r < REGS; ++r) {
      if (chosen[r] != reg_is_hot(r)) { same = false; break; }
    }
    if (same) {
      printf("Existing hot register set is optimal.\n");
    } else {
      printf("Hot registers (frame_descriptors.h): {");
      sep = " ";
      for (int r = 0; r < REGS; ++r) {
        if (chosen[r]) { printf("%s%d", sep, r); sep = ", "; }
      }
      printf(" };\n");
      printf("Hot registers (arch.ml): let frame_hot_regs = [|");
      sep = " ";
      for (int r = 0; r < REGS; ++r) {
        if (chosen[r]) { printf("%s%d", sep, r); sep = "; "; }
      }
      printf(" |]\n");
    }
  }
}

/* Actually floor(log_2(x))+1, clamped at MAX_LOG-1.
   mylog(0) = 0
   mylog(1) = 1
   mylog(2) = 2
   mylog(3) = 2
   mylog(4) = 3
   ...
   mylog(255) = 8
   mylog(256) = 9
   etc
  */
Caml_inline size_t mylog(size_t v)
{
  size_t log = 0;
  while(v) {
    v /= 2;
    ++ log;
  }
  /* Clamp so the result is always a valid index into a MAX_LOG table */
  if (log >= MAX_LOG) {
    log = MAX_LOG - 1;
  }
  return log;
}

/* Common code for recording an item in:
   - an optional max value;
   - an optional table of small values (less than SMALL_FRAMES)
   - an optional table of log values.
 */

Caml_inline void count_item(size_t item, size_t *max, size_t *smalls,
                            size_t *logs)
{
  if (max && item > *max) {
    *max = item;
  }
  if (smalls && item < SMALL_FRAMES) {
    ++ smalls[item];
  }
  if (logs) {
    ++ logs[mylog(item)];
  }
}

/* Record a single GCable register: register numbers are normally small
   (we have never observed one larger than MAX_REG_IN_SMALL_MAP), but the
   format permits large ones (e.g. Valx2 values held in SIMD registers),
   so we guard the fixed-size tables and count the outliers separately. */

static void add_reg(size_t reg, size_t *regs, size_t *max_reg,
                    bool *has_big_reg, struct frametable_stats *stats)
{
  ++ *regs;
  if (reg < REGS) {
    ++ stats->reg[reg];
  }
  if (reg > *max_reg) {
    *max_reg = reg;
  }
  if (reg > MAX_REG_IN_SMALL_MAP) {
    *has_big_reg = true;
  }
  if (reg > MAX_REG) {
    ++ stats->big_reg_entries;
  }
}

/* Record a single GCable stack slot, given its byte offset. */

static void add_slot(size_t byte_ofs, size_t *slots, size_t *max_slot)
{
  size_t slot = byte_ofs / sizeof(value);
  ++ *slots;
  if (slot > *max_slot) {
    *max_slot = slot;
  }
}

/* For an escaped (non-short, non-return-to-C, non-first-in-frametable)
   descriptor, determine why it could not be encoded in the short format,
   mirroring [short_encoding] in backend/emitaux.ml (same checks, same
   order). Returns [ESC_FITS] if the content is short-compatible, meaning
   the descriptor escaped only for a function/text-section boundary. */

static enum escape_reason classify_escape(frame_descr *d,
                                          struct frame_descr_decoded *dec)
{
  if (dec->is_long) return ESC_LONG;
  uint32_t size = dec->frame_size; /* in bytes, flag bits already masked off */
  if (size == 0 || size > 1008 || (size & 15) != 0) return ESC_BADSIZE;

  size_t nregs = 0;
  size_t frame_words = size / sizeof(value);
  bool cold_reg = false;
  const uint16_t *ofp = (const uint16_t *)(d + Frame_live_ofs);
  for (uint32_t n = dec->num_live; n > 0; n--, ofp++) {
    uint16_t v = caml_read_unaligned_uint16(ofp);
    if (v & 1) {
      ++ nregs;
      if (!reg_is_hot(v >> 1)) cold_reg = true;
    } else {
      if ((v & (sizeof(value) - 1)) != 0) return ESC_BADSLOT; /* unaligned */
      if ((size_t)(v / sizeof(value)) >= frame_words) return ESC_SLOTBEYOND;
    }
  }
  if (!dec->has_allocs && nregs > 0) return ESC_NOALLOC_REGS;
  if (cold_reg) return ESC_COLDREG;

  if (dec->has_allocs) {
    size_t num_allocs = dec->num_allocs;
    if (num_allocs > 255) return ESC_MANYALLOCS;
    /* Escaped alloc sizes are one byte each (same wosize-1 value the short
       format would store in a nibble), just past the num_allocs byte. */
    const unsigned char *sizes = dec->end_of_live + 1;
    for (size_t i = 0; i < num_allocs; ++i) {
      if (sizes[i] > 15) return ESC_BIGALLOC;
    }
  }
  return ESC_FITS;
}

/* Record stats for a single descriptor, given its decoded form, its
   descriptor body pointer, and its absolute return address (as
   reconstructed by the frametable iterator). */

static void add_descriptor_to_stats(frame_descr *d,
                                    struct frame_descr_decoded *dec,
                                    uintnat retaddr,
                                    struct frametable_stats *stats)
{
  bool first_in_ft = (stats->descrs == 0);
  ++ stats->descrs;
  if (!stats->min_descr || ((unsigned char*)d < stats->min_descr)) {
    stats->min_descr = (unsigned char*)d;
  }

  /* Relative return address: the (signed) byte offset from the
     descriptor to its return address. For short descriptors this is
     implicit (encoded as a delta); we compute it from the
     reconstructed absolute address. */
  intnat retaddr_rel = (intnat)((uintnat)retaddr - (uintnat)d);
  if (retaddr_rel < 0) {
    count_item(-retaddr_rel, &stats->max_neg_retaddr_rel, NULL,
               stats->log_neg_retaddr_rel);
  } else {
    count_item(retaddr_rel, &stats->max_pos_retaddr_rel, NULL,
               stats->log_pos_retaddr_rel);
  }

  unsigned char *retaddr_p = (unsigned char *)retaddr;
  if (stats->last_retaddr) {
    if (retaddr_p < stats->min_retaddr) {
      stats->min_retaddr = retaddr_p;
    }
    if (retaddr_p > stats->max_retaddr) {
      stats->max_retaddr = retaddr_p;
    }
    intnat delta = (uintnat)retaddr_p - (uintnat)stats->last_retaddr;
    if (delta < 0) {
      count_item(-delta, &stats->max_neg_delta, NULL, stats->log_neg_delta);
    } else {
      count_item(delta, &stats->max_pos_delta, NULL, stats->log_pos_delta);
    }
  } else {
    stats->min_retaddr = stats->max_retaddr = retaddr_p;
  }
  stats->last_retaddr = retaddr_p;

  if (dec->return_to_C) {
    ++ stats->return_to_C;
  } else {
    if (dec->is_short) ++ stats->short_descrs;
    else if (dec->is_long) ++ stats->long_descrs;
    else ++ stats->medium_descrs;

    /* For escaped descriptors, record why they could not go short. The first
       descriptor of a frametable always escapes; the rest are classified by
       whether their content fits (a section-boundary escape) or not. */
    if (!dec->is_short) {
      ++ stats->escape_reason[first_in_ft ? ESC_FT_FIRST
                                          : classify_escape(d, dec)];
    }

    uint32_t sz = dec->frame_size; /* in bytes */
    sz /= sizeof(uintnat);
    count_item(sz, &stats->max_framesize, stats->small_frames,
               stats->log_framesize);

    size_t regs = 0; /* number of live registers */
    size_t max_reg = 0; /* max live register number */
    size_t slots = 0; /* number of live stack slots */
    size_t max_slot = 0; /* max live stack slot offset */
    bool has_big_reg = false; /* saw a register too big for the small map */

    /* Extract the normalized (registers, stack slots) live set,
       decoding short and escaped descriptors compatibly. */
    if (dec->is_short) {
      /* Short: live registers come from the hot-register bitmap (set
         only for allocation descriptors); live stack slots from the
         frame's slot bitmap. */
      for (int i = 0; i < FRAME_NUM_HOT_REGS; ++i) {
        if (dec->short_reg_bitmap & (1u << i)) {
          add_reg(caml_frame_hot_regs[i], &regs, &max_reg, &has_big_reg,
                  stats);
        }
      }
      for (uint32_t byte = 0; byte < dec->short_live_bytes; ++byte) {
        unsigned char bits = dec->short_live[byte];
        for (int i = 0; bits != 0; ++i, bits >>= 1) {
          if (bits & 1) {
            size_t byte_ofs = ((size_t)byte * 8 + i) * sizeof(value);
            add_slot(byte_ofs, &slots, &max_slot);
          }
        }
      }
    } else if (dec->is_long) {
      const uint32_t *ofp = (const uint32_t *)(d + Frame_long_live_ofs);
      for (uint32_t n = dec->num_live; n > 0; n--, ofp++) {
        uint32_t v = caml_read_unaligned_uint32(ofp);
        if (v & 1) {
          add_reg(v >> 1, &regs, &max_reg, &has_big_reg, stats);
        } else {
          add_slot(v, &slots, &max_slot);
        }
      }
    } else {
      const uint16_t *ofp = (const uint16_t *)(d + Frame_live_ofs);
      for (uint32_t n = dec->num_live; n > 0; n--, ofp++) {
        uint16_t v = caml_read_unaligned_uint16(ofp);
        if (v & 1) {
          add_reg(v >> 1, &regs, &max_reg, &has_big_reg, stats);
        } else {
          add_slot(v, &slots, &max_slot);
        }
      }
    }

    /* GC live values = live registers + live stack slots. */
    count_item(regs + slots, &stats->max_lives, stats->small_lives,
               stats->log_lives);

    /* Register counts, recorded only for allocation descriptors.
       Non-allocation descriptors are not expected to keep GC roots in
       registers, so count any that do as an anomaly rather than folding
       them into the register statistics. */
    if (dec->has_allocs) {
      if (regs < REGS) {
        ++ stats->reg_count[regs];
      }
      if (max_reg < REGS) {
        ++ stats->max_reg[max_reg];
      }
      if (regs > stats->max_regs) {
        stats->max_regs = regs;
      }
      if (has_big_reg) {
        ++ stats->big_reg_descrs;
      }
    } else if (regs > 0) {
      ++ stats->noalloc_with_regs;
    }

    /* Slot counts */
    count_item(slots, &stats->max_slots, stats->small_slots,
               stats->log_slots);

    /* Maximum slot offset */
    count_item(max_slot, &stats->max_slot, stats->small_max_slot,
               stats->log_max_slot);

    /* Allocation sizes and comballoc counts. The alloc sizes store
       wosize-1 in both encodings (short: 4-bit nibbles; escaped: whole
       bytes after end_of_live), so they are directly comparable. */
    if (dec->has_allocs) {
      ++ stats->with_alloc;
      size_t num_allocs = dec->num_allocs;
      stats->alloc_sizes += num_allocs;
      count_item(num_allocs, &stats->max_comballocs, stats->small_comballocs,
                 stats->log_comballocs);
      if (dec->is_short) {
        for (size_t idx = 0; idx < num_allocs; ++idx) {
          unsigned char byte = dec->short_allocs[idx / 2];
          unsigned char sz = (idx & 1) ? (byte >> 4) : (byte & 0x0f);
          count_item(sz, &stats->max_alloc_size, stats->small_alloc_sizes,
                     stats->log_alloc_sizes);
        }
      } else {
        /* escaped: [num_allocs byte][num_allocs size bytes] */
        const unsigned char *sizes = dec->end_of_live + 1;
        for (size_t idx = 0; idx < num_allocs; ++idx) {
          count_item(sizes[idx], &stats->max_alloc_size,
                     stats->small_alloc_sizes, stats->log_alloc_sizes);
        }
      }
    }

    /* Count debug info if present */
    if (dec->has_debug) {
      ++ stats->with_debug;
      const unsigned char *p = dec->end_of_live;
      if (!dec->is_short && dec->has_allocs) {
        /* escaped: skip num_allocs byte + alloc bytes */
        p += (uintnat)(*p) + 1;
      }
      for (uint32_t i = 0; i < dec->num_debuginfo; ++i) {
        uint32_t offset = caml_read_unaligned_uint32(p);
        if (offset) { /* there may be invalid debuginfo slots */
          caml_debuginfo_measure((debuginfo)(p + offset));
        }
        p += sizeof(uint32_t);
      }
    }
  }

  if (!stats->max_descr || (dec->end > stats->max_descr)) {
    stats->max_descr = (unsigned char *)dec->end;
  }
}

/* Record stats for all descriptors from a frametable */

static void add_frametable_to_stats(intnat *frametable,
                                    struct frametable_stats *stats)
{
  ++ stats->frametables;
  if (!stats->min_descr ||
      ((unsigned char*)frametable < stats->min_descr)) {
    stats->min_descr = (unsigned char*)frametable;
  }
  if (!stats->max_descr ||
      ((unsigned char*)frametable > stats->max_descr)) {
    stats->max_descr = (unsigned char*)(frametable+1);
  }
  frametable_iter it;
  frametable_iter_start(&it, frametable);
  while (it.remaining > 0) {
    uintnat retaddr;
    frame_descr *d = frametable_iter_next(&it, &retaddr);
    struct frame_descr_decoded dec;
    caml_decode_frame_descr(d, &dec);
    add_descriptor_to_stats(d, &dec, retaddr, stats);
  }
}

/* Record and report stats for all frametables on a list */

static void report_frametables_stats(caml_frametable_list *new_frametables)
{
  struct frametable_stats stats;
  clear_stats(&stats);
  iter_list(new_frametables, cur) {
    add_frametable_to_stats(cur->frametable, &stats);
    accumulate_frametable_stats(cur->frametable, &stats);
    clear_per_frametable_stats(&stats);
  }
  report_stats(&stats);
}

static void add_frame_descriptors(
  caml_frame_descrs *table,
  caml_frametable_list *new_frametables)
{
  CAMLassert(new_frametables != NULL);

  ensure_heap_descriptors(table);

  caml_frametable_list *tail = frametables_list_tail(new_frametables);
  intnat increase = count_descriptors(new_frametables);
  intnat tblsize = capacity(*table);

  /* The size of the hashtable is a power of 2 that must remain
     greater or equal to 2 times the number of descriptors. */

  /* Reallocate the caml_frame_descriptor table if it is too small */
  if(tblsize < (table->num_descr + increase) * 2) {

    /* Merge both lists */
    tail->next = table->frametables;
    table->frametables = NULL;

    intnat num_descr = table->num_descr + increase;

    tblsize = 4;
    while (tblsize < 2 * num_descr) tblsize *= 2;

    table->num_descr = num_descr;
    table->mask = tblsize - 1;

    if (table->descriptors != NULL) caml_stat_free(table->descriptors);
    table->descriptors =
      (frame_descr_entry *) caml_stat_calloc_noexc(tblsize,
                                                   sizeof(frame_descr_entry));
    if (table->descriptors == NULL) caml_raise_out_of_memory();

    fill_hashtable(table, new_frametables);
    if (caml_measure_frametables) {
      report_frametables_stats(new_frametables);
    }
  } else {
    table->num_descr += increase;
    fill_hashtable(table, new_frametables);
    if (caml_measure_frametables) {
      report_frametables_stats(new_frametables);
    }
    tail->next = table->frametables;
  }

  table->frametables = new_frametables;
}

/* protected by STW sections */
static caml_frame_descrs current_frame_descrs =
  { 0, -1, NULL, NULL, NULL, CAML_PLAT_MUTEX_INITIALIZER };

static caml_frametable_list *cons(
  intnat *frametable, caml_frametable_list *tl)
{
  caml_frametable_list *li = caml_stat_alloc(sizeof(caml_frametable_list));
  li->frametable = frametable;
  li->next = tl;
  return li;
}

/* This function not only creates a new caml_frametable_list cell but
   also makes a copy of the new frametable.
   Here, we allocate, in a single malloc call, the space for the cons
   cell and the (appended) frametable copy. This way, we do not have
   to change the code that unregisters the frametable since calling free
   on the cons cell will automatically free the frametable copy at the
   same time.
*/
static caml_frametable_list *copy_cons(
  intnat **frametable, intnat size, caml_frametable_list *tl)
{
  caml_frametable_list *li =
    caml_stat_alloc(sizeof(caml_frametable_list) + size);
  intnat *frametable_copy = (intnat*)(li + 1);
  memcpy(frametable_copy, *frametable, size);
  *frametable = frametable_copy;
  li->frametable = frametable_copy;
  li->next = tl;
  return li;
}

#define FRAME_BUILD_ID_MAX 64

struct frame_cache_hdr {
  uint64_t magic;
  uint64_t num_descr;
  uint64_t cap;             /* = mask + 1, length of the descriptors array */
  uint64_t checksum;        /* FNV-1a over the [cap] descriptor words */
  uint64_t anchor;          /* &caml_baked_frametable at bake time: the stored
                               descriptors are absolute pointers, so any change
                               of load bias (PIE/ASLR relink or a dynamic
                               loader placing the image elsewhere) must reject
                               the bake; build-id+checksum cannot catch it. */
  uint32_t build_id_len;
  unsigned char build_id[FRAME_BUILD_ID_MAX];
};

/* The ELF GNU build-id of the running executable. Fixed per binary; the strong
   half of the staleness guard (a cache from any other build is rejected). */
struct frame_buildid { unsigned char id[FRAME_BUILD_ID_MAX]; uint32_t len; };

#if defined(__ELF__)
static int frame_buildid_cb(struct dl_phdr_info *info, size_t sz, void *data)
{
  (void) sz;
  struct frame_buildid *out = (struct frame_buildid *) data;
  for (int i = 0; i < info->dlpi_phnum; i++) {
    const ElfW(Phdr) *ph = &info->dlpi_phdr[i];
    if (ph->p_type != PT_NOTE) continue;
    const char *p = (const char *) (info->dlpi_addr + ph->p_vaddr);
    const char *end = p + ph->p_memsz;
    while (p + sizeof(ElfW(Nhdr)) <= end) {
      const ElfW(Nhdr) *n = (const ElfW(Nhdr) *) p;
      const char *name = p + sizeof(*n);
      const char *desc = name + ((n->n_namesz + 3) & ~3u);
      if (n->n_type == NT_GNU_BUILD_ID && n->n_namesz == 4
          && memcmp(name, "GNU", 4) == 0
          && n->n_descsz > 0 && n->n_descsz <= FRAME_BUILD_ID_MAX) {
        memcpy(out->id, desc, n->n_descsz);
        out->len = n->n_descsz;
        return 1;
      }
      p = desc + ((n->n_descsz + 3) & ~3u);
    }
  }
  return 1; /* only the main program (first object) is inspected */
}

static void frame_get_buildid(struct frame_buildid *out)
{
  out->len = 0;
  dl_iterate_phdr(frame_buildid_cb, out);
}
#else
/* Non-ELF targets: no build-id and no bake (see the gates in
   frame_baked_load/dump); the stub keeps the call sites compiling. */
static void frame_get_buildid(struct frame_buildid *out) { out->len = 0; }
#endif /* __ELF__ */

static uint64_t frame_checksum(frame_descr **d, intnat cap)
{
  uint64_t h = 1469598103934665603ull;
  for (intnat i = 0; i < cap; i++)
    h = (h ^ (uint64_t)(uintnat) d[i]) * 1099511628211ull;
  return h;
}

/* ------------------------------------------------------------------------- */
/* C1 (bake-frame, task #63): a frame-descriptor table baked into the         */
/* executable at LINK time. The fleet compiler is non-PIE (Type EXEC), so     */
/* every [frame_descr*] is a link-time constant and the ~4 MB hashtable is    */
/* byte-identical across all runs. Rather than rebuild it at every startup     */
/* (~7.5 ms — see frame-lazy-findings.md) we reserve a section in the binary,  */
/* fill it once after linking (a bake step dumps it and objcopy patches it),   */
/* and at startup point [descriptors] straight at the in-image table.          */
/*                                                                            */
/* Safe-by-construction fallback: the reserved section is zero in every        */
/* freshly-linked (unpatched / bootstrap) binary, so [magic] fails to match    */
/* and the runtime rebuilds exactly as today. A relink resets the section to   */
/* zero, so a stale baked table can never survive a rebuild. The bake dump     */
/* reuses the runtime's own [add_frame_descriptors] — no reimplementation of   */
/* the fill logic that could drift.                                            */
/*                                                                            */
/* Guard = magic + runtime-counted num_descr + ELF build-id + cap-fits (all    */
/* O(1)/O(build-id)). Unlike the C2 file cache there is no foreign file to     */
/* mistrust: the build-id note ties the baked table to this exact binary, so   */
/* the full-4 MB FNV checksum is NOT walked by default — startup then faults    */
/* in only the buckets actually probed (true lazy fault, lower RSS). The       */
/* checksum is still stored and verified on demand via CAML_FRAME_BAKE_VERIFY. */

#define FRAME_BAKED_MAGIC 0x324b424d5246584full /* "OXFRMBK2" (v2: adds the load-bias anchor) */
#define FRAME_BAKED_BODY_OFF 4096u               /* body page-aligned for faulting */
/* Sized for growth: the current fleet compiler needs cap = 2^19 exactly
   (num_descr ~ 259.5k), i.e. ~1% headroom before the dump falls back and
   the whole optimisation silently reverts. 2^20 gives ~4x headroom for
   ~4 MB more reserve in opted-in binaries only. */
#define FRAME_BAKED_CAP_MAX (1u << 20)           /* 1048576 slots = 8 MB */
#define FRAME_BAKED_RESERVE \
  (FRAME_BAKED_BODY_OFF + FRAME_BAKED_CAP_MAX * sizeof(frame_descr *))

/* The reserve is NOT defined here: it lives in a separate, opt-in object
   (runtime/caml_frame_bake_reserve.c => caml_frame_bake_reserve.o, installed
   beside libasmrun.a). We reference it WEAKLY so that a binary linked WITHOUT
   the reserve object — every normal executable, since the object is not in
   libasmrun.a — resolves the symbol to NULL and falls straight through to the
   rebuild path with ZERO size or runtime cost (no 4 MB section, base file size
   preserved byte-for-byte). Only binaries that opt in (the compiler, by adding
   the reserve object to their link line) carry the section and are bakeable.
   The weak reference means no config fork in the runtime: presence of the
   symbol is the switch. */
extern unsigned char caml_baked_frametable[] __attribute__((weak));

/* Point [current_frame_descrs] at the baked in-image table; return 1 on a
   validated hit. Any mismatch returns 0 so the caller rebuilds normally. */
static int frame_baked_load(caml_frametable_list *fts, int verify)
{
#if !defined(__ELF__)
  /* The bake is ELF-only: it relies on the GNU build-id and on the ELF
     section/objcopy pipeline. Non-ELF targets always rebuild. */
  (void) fts; (void) verify;
  return 0;
#else
  /* Weak-null check FIRST: if this binary was linked without the reserve
     object, the symbol is NULL and there is no baked table — rebuild. */
  if (caml_baked_frametable == NULL) return 0;
  struct frame_cache_hdr *h =
    (struct frame_cache_hdr *) (void *) caml_baked_frametable;
  if (h->magic != FRAME_BAKED_MAGIC) return 0;
  if (h->anchor != (uint64_t)(uintnat) caml_baked_frametable)
    return 0; /* load bias differs from bake time (PIE/ASLR): pointers stale */
  intnat num_descr = count_descriptors(fts);
  if (h->num_descr != (uint64_t) num_descr) return 0;
  if (h->cap == 0 || (h->cap & (h->cap - 1)) != 0) return 0; /* power of 2 */
  if (h->cap > FRAME_BAKED_CAP_MAX) return 0; /* prevent cap*8 overflow */
  if (FRAME_BAKED_BODY_OFF + h->cap * sizeof(frame_descr *) > FRAME_BAKED_RESERVE)
    return 0;
  struct frame_buildid bid;
  frame_get_buildid(&bid);
  if (h->build_id_len != bid.len
      || memcmp(h->build_id, bid.id, bid.len) != 0)
    return 0;
  frame_descr **descrs =
    (frame_descr **) (void *) (caml_baked_frametable + FRAME_BAKED_BODY_OFF);
  if (verify && h->checksum != frame_checksum(descrs, (intnat) h->cap))
    return 0;
  current_frame_descrs.descriptors = descrs;
  current_frame_descrs.mask = (int) (h->cap - 1);
  current_frame_descrs.num_descr = (int) num_descr;
  current_frame_descrs.frametables = fts;
  frame_descrs_from_cache = 1; /* copy-out-on-mutation via ensure_heap_descriptors */
  return 1;
#endif /* __ELF__ */
}

/* Bake step: serialize the freshly-built table into [path] as the exact
   FRAME_BAKED_RESERVE-byte section image (header at offset 0, descriptors[] at
   FRAME_BAKED_BODY_OFF, zero-padded to the reserve). objcopy --update-section
   then patches this into the binary. Failures are reported but non-fatal. */
static void frame_baked_dump(const char *path)
{
#if !defined(__ELF__)
  (void) path;
  fprintf(stderr, "[frame] bake: unsupported on non-ELF targets\n");
#else
  intnat cap = capacity(current_frame_descrs);
  if (FRAME_BAKED_BODY_OFF + (size_t) cap * sizeof(frame_descr *)
      > FRAME_BAKED_RESERVE) {
    fprintf(stderr,
            "[frame] bake: table (cap=%ld) exceeds reserve %zu — not baked\n",
            (long) cap, (size_t) FRAME_BAKED_RESERVE);
    return;
  }
  unsigned char *img =
    (unsigned char *) caml_stat_calloc_noexc(FRAME_BAKED_RESERVE, 1);
  if (img == NULL) return;
  struct frame_cache_hdr *h = (struct frame_cache_hdr *) (void *) img;
  h->magic = FRAME_BAKED_MAGIC;
  h->num_descr = (uint64_t) current_frame_descrs.num_descr;
  h->cap = (uint64_t) cap;
  h->checksum = frame_checksum(current_frame_descrs.descriptors, cap);
  h->anchor = (uint64_t)(uintnat) caml_baked_frametable;
  struct frame_buildid bid;
  frame_get_buildid(&bid);
  h->build_id_len = bid.len;
  memcpy(h->build_id, bid.id, bid.len);
  memcpy(img + FRAME_BAKED_BODY_OFF, current_frame_descrs.descriptors,
         (size_t) cap * sizeof(frame_descr *));
  int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
  int ok = 0;
  if (fd >= 0) {
    ok = (write(fd, img, FRAME_BAKED_RESERVE) == (ssize_t) FRAME_BAKED_RESERVE);
    close(fd);
  }
  caml_stat_free(img);
  if (!ok) fprintf(stderr, "[frame] bake: failed to write %s\n", path);
#endif /* __ELF__ */
}

void caml_init_frame_descriptors(void)
{
  caml_frametable_list *frametables = NULL;
  for (int i = 0; caml_frametable[i] != 0; i++)
    frametables = cons(caml_frametable[i], frametables);

  /* `init_frame_descriptors` is called from `init_gc`, before
     any mutator can run. We can mutate [current_frame_descrs]
     at will. */
#if defined(__ELF__)
  /* caml_secure_getenv: bake mode truncates and writes a caller-named
     file with the process's privileges, so it must be inert (like the
     other runtime env controls) in setuid/setgid executables. */
  const char *fstats = caml_secure_getenv("CAML_FRAME_STATS");
  const char *fbake = caml_secure_getenv("CAML_FRAME_BAKE");
  int bake_verify = caml_secure_getenv("CAML_FRAME_BAKE_VERIFY") != NULL;
  /* Bake mode is only meaningful for binaries that link the reserve
     section: ignore the variable elsewhere (silently -- stderr chatter
     from a leaked variable must not fail strict-stderr build actions), so
     an inherited CAML_FRAME_BAKE cannot turn ordinary OCaml programs into
     dump-and-exit no-ops. */
  if (fbake != NULL && caml_baked_frametable == NULL) fbake = NULL;
  struct timespec t0, t1;
  if (fstats) clock_gettime(CLOCK_MONOTONIC, &t0);
  int hit = 0;
  /* C1: the link-time baked table takes precedence (zero-config, no file I/O).
     In bake mode we always build fresh so the dump reflects this binary. */
  if (fbake == NULL) hit = frame_baked_load(frametables, bake_verify);
  if (!hit) {
    add_frame_descriptors(&current_frame_descrs, frametables);
  }
  if (fbake) frame_baked_dump(fbake);
  if (fstats) {
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double ms = (t1.tv_sec - t0.tv_sec) * 1000.0
              + (t1.tv_nsec - t0.tv_nsec) / 1e6;
    fprintf(stderr, "[frame] hit=%d num_descr=%d cap=%d init=%.3fms\n",
            hit, current_frame_descrs.num_descr,
            current_frame_descrs.mask + 1, ms);
  }
  /* Bake mode: the section image is dumped; exit before running any mutator.
     _exit avoids atexit handlers touching the half-initialised runtime. */
  if (fbake) { fflush(NULL); _exit(0); }
#else
  /* Non-ELF targets: no baked-table support, always rebuild. */
  add_frame_descriptors(&current_frame_descrs, frametables);
#endif /* __ELF__ */
}

static void register_frametables_from_stw_single(
  caml_frametable_list *new_frametables)
{
  clean_frame_descriptors(&current_frame_descrs);
  add_frame_descriptors(&current_frame_descrs, new_frametables);
}

static void stw_register_frametables(
    caml_domain_state* domain,
    void* frametables,
    int participating_count,
    caml_domain_state** participating)
{
  Caml_global_barrier_if_final(participating_count) {
    register_frametables_from_stw_single((caml_frametable_list *) frametables);
  }
}

void caml_register_frametables(void **table, int ntables) {
  caml_frametable_list *new_frametables = NULL;
  for (int i = 0; i < ntables; i++)
    new_frametables = cons(table[i], new_frametables);

  do {} while (!caml_try_run_on_all_domains(
                 &stw_register_frametables, new_frametables, 0));
}

void caml_copy_and_register_frametables(
  void **table, int * sizes, int ntables)
{
  caml_frametable_list *new_frametables = NULL;
  for (int i = 0; i < ntables; i++)
    new_frametables = copy_cons((intnat **)(table + i),
                                sizes[i], new_frametables);

  do {} while (!caml_try_run_on_all_domains(
                 &stw_register_frametables, new_frametables, 0));
}

static void remove_frame_descriptors(
  caml_frame_descrs * table, void ** frametables, int ntables)
{
  void *frametable;
  caml_frametable_list ** previous;

  /* cannot release the domain lock here (e.g. custom block finaliser) */
  caml_plat_lock_blocking(&table->mutex);

  previous = &table->frametables;

  iter_list(table->frametables, current) {
  resume:
    for (int i = 0; i < ntables; i++) {
      if (current->frametable == frametables[i]) {
        *previous = current->next;
        current->next = table->zombies;
        table->zombies = current;
        ntables--;
        if (ntables == 0) goto release;
        current = *previous;
        frametable = frametables[i];
        frametables[i] = frametables[ntables];
        frametables[ntables] = frametable;
        goto resume;
      }
    }
    previous = &current->next;
  }

 release:
  caml_plat_unlock(&table->mutex);
}

void caml_unregister_frametables(void ** frametables, int ntables)
{
  remove_frame_descriptors(&current_frame_descrs, frametables, ntables);
}

void caml_register_frametable(void * frametables)
{
  caml_register_frametables(&frametables, 1);
}

void* caml_copy_and_register_frametable(void * frametable, int size)
{
  caml_copy_and_register_frametables(&frametable, &size, 1);
  return frametable;
}

void caml_unregister_frametable(void * frametables)
{
  caml_unregister_frametables(&frametables, 1);
}

caml_frame_descrs* caml_get_frame_descrs(void)
{
  return &current_frame_descrs;
}

frame_descr* caml_find_frame_descr(caml_frame_descrs *fds, uintnat pc)
{
  uintnat h;

  h = Hash_retaddr(pc, fds->mask);
  while (1) {
    frame_descr_entry e = fds->descriptors[h];
    /* On stack overflow (via guard page/SEGV) the PC is not in frame tables */
    if (e.fd == NULL) return NULL;
    if (e.retaddr == pc) return e.fd;
    h = (h+1) & fds->mask;
  }
}
