(executable
 (name fake_solver)
 (modules fake_solver)
 (libraries unix)
 (enabled_if (= %{context_name} main)))

(test
 (name test_smt)
 (modules test_smt)
 (libraries vox_smt vox_smt_solver unix)
 (enabled_if (= %{context_name} main))
 (action (run %{test} %{exe:fake_solver.exe})))

(test
 (name test_z3)
 (modules test_z3)
 (libraries vox_smt vox_smt_solver)
 (enabled_if
  (and (= %{context_name} main) (= %{env:VOX_TEST_Z3=false} true)))
 (action (run %{test} %{bin:z3})))
