(executable
 (name fake_solver)
 (modules fake_solver)
 (libraries unix)
 (enabled_if (= %{context_name} main)))

(test
 (name test_smt)
 (modules test_smt)
 (libraries vox_smt vox_smt_solver unix)
 (enabled_if (= %{context_name} main))
 (action (run %{test} %{exe:fake_solver.exe})))

(test
 (name test_z3)
 (modules test_z3)
 (libraries vox_smt vox_smt_solver)
 (enabled_if
  (and (= %{context_name} main) (= %{env:VOX_TEST_Z3=false} true)))
 (action (run %{test} %{bin:z3})))

(copy_files ../../testsuite/tests/vox/smt_solver.ml)
(copy_files ../../testsuite/tests/vox/smt_solver.reference)

(executable
 (name smt_solver)
 (modules smt_solver)
 (libraries vox_smt vox_smt_solver)
 (enabled_if (= %{context_name} main)))

(rule
 (alias runtest)
 (deps smt_solver.reference)
 (enabled_if
  (and (= %{context_name} main) (= %{env:VOX_TEST_Z3=false} true)))
 (action
  (progn
   (with-stdout-to smt_solver.output (run %{exe:smt_solver.exe} %{bin:z3}))
   (diff smt_solver.reference smt_solver.output))))
