(* TEST
 has-z3;
 flags = "-extension refinement_types";
 source_directories = "${test_source_directory}/../../../verification/library";
 all_modules = "pref.mli pref.ml copy_spec.ml copy_heap_proofs.ml copy_model_proofs.ml copy_complete_proofs.ml copy_sound_proofs.ml copy_template_proofs.ml level_spec.ml lower_locality_spec.ml level_proofs.ml lower_locality_proofs.ml level_unifier_spec.ml marked_occurs_proofs.ml level_unifier_proofs.ml level_unifier_metadata.ml generalize_spec.ml generalize_proofs.ml generalize_scheme_proofs.ml level_finite_spec.ml level_finite_proofs.ml forest_transport.ml pooled_spec.ml pooled_proofs.ml pooled_allocation_proofs.ml provenance_spec.ml provenance_proofs.ml relative_generalization.ml compression_model_proofs.ml compression_finite_proofs.ml hmc_word64.ml hm_declarative.ml hm_environment_spec.ml compression_spec.ml compression_path_proofs.ml compression_proofs.ml structure_finite_proofs.ml structure_spec.ml optimized_unifier_spec.ml optimized_metadata.ml copy_cleanup_spec.ml copy_cleanup_proofs.ml nested_pool_spec.ml nested_pool_proofs.ml representative_level.ml representative_pool_spec.ml representative_pool_proofs.ml effective_level.ml representative_mutation.ml effective_copy_spec.ml effective_copy_heap_proofs.ml effective_copy_metadata.ml effective_copy_finite.ml representative_certificate.ml copy_certificate_spec.ml copy_certificate_capture.ml copy_certificate_proofs.ml hm_execution_spec.ml effective_lower_spec.ml effective_lower_proofs.ml terminal_lower_spec.ml terminal_lower_proofs.ml effective_compression_spec.ml effective_compression_proofs.ml effective_unifier_spec.ml effective_unifier_finite.ml effective_unifier_frame.ml effective_scan_proofs.ml effective_compression_metadata.ml effective_unifier_heads.ml effective_unifier_metadata.ml effective_unifier_order.ml hm_primitive_constraints.ml hm_type_proofs.ml hm_conditional_constraints.ml hm_list_case_constraints.ml hm_effective_execution_spec.ml hm_effective_forest.ml effective_unifier_pool.ml hm_effective_runtime.ml hm_effective_registration.ml hm_effective_bound.ml hm_runtime_spec.ml hm_effective_paths.ml hm_effective_result.ml hm_effective_membership.ml hm_effective_driver_proofs.ml hm_annotation_trace.ml hm_annotation_trace_spec.ml hm_annotation_owned.ml hm_annotation_owned_demo.ml";
 { bytecode; }
 { native; }
*)
let () = ()
