(* TEST
 has-z3;
 source_directories = "${test_source_directory}/../../../verification/library";
 readonly_files = "vox_sequence.mli vox_sequence.ml vox_http_spec.mli";
 readonly_files += " vox_http_spec.ml vox_http_model.ml vox_http.mli vox_http.ml";
 readonly_files += " vox_int_sequence.mli vox_int_sequence.ml vox_iarray.mli";
 readonly_files += " vox_iarray.ml vox_string_view.mli vox_string_view.ml";
 readonly_files += " vox_sat_spec.mli vox_sat_spec.ml vox_sat_proof.mli";
 readonly_files += " vox_sat_proof.ml vox_sat.mli vox_sat.ml";
 readonly_files += " vox_cdcl_total_proof.mli";
 readonly_files += " vox_cdcl_total_proof.ml vox_cdcl_total.mli";
 readonly_files += " vox_cdcl_total.ml vox_credits.mli vox_credits.ml";
 readonly_files += " vox_ordered_sequence.ml vox_merge_proofs.ml";
 readonly_files += " vox_sort_cost.mli vox_sort_cost.ml vox_merge_sort.mli vox_merge_sort.ml";
 readonly_files += " vox_lz4_model.ml vox_parallel.mli vox_parallel.ml";
 readonly_files += " borrow.mli borrow.ml borrow_iarray.mli";
 readonly_files += " borrow_iarray.ml pref.mli pref.ml vox_pref_semantics.mli";
 readonly_files += " vox_pref_semantics.ml ghost_pref.mli ghost_pref.ml";
 readonly_files += " vox_big_credits.mli vox_big_credits.ml vox_ackermann.ml";
 readonly_files += " vox_union_find_potential.ml vox_union_find_levels.ml";
 readonly_files += " vox_union_find_path_cost.ml vox_union_find_model.ml";
 readonly_files += " vox_union_find_forest.ml vox_union_find_rank.ml";
 readonly_files += " vox_union_find_mass.ml vox_union_find_link.ml";
 readonly_files += " vox_union_find_worker.ml vox_union_find_amortized.ml";
 readonly_files += " vox_union_find_bank.ml vox_union_find_spec.ml";
 readonly_files += " vox_union_find_events.mli vox_union_find_events.ml";
 readonly_files += " vox_union_find.mli vox_union_find.ml";
 readonly_files += " vox_union_find_complexity.ml vox_union_find_simple.mli";
 readonly_files += " vox_union_find_simple.ml vox_partition.ml";
 readonly_files += " vox_partition_classes.ml vox_partition_classes_proof.ml";
 readonly_files += " vox_partition_classes_bridge.ml";
 readonly_files += " vox_partition_transport_proof.ml";
 readonly_files += " vox_partition_classes_group.ml";
 readonly_files += " vox_union_find_partition_proof.ml";
 readonly_files += " vox_union_find_online.mli";
 readonly_files += " vox_union_find_online.ml vox_connectivity.mli";
 readonly_files += " vox_connectivity.ml vox_union_find_online_cost.ml";
 readonly_files += " raw_memory.mli raw_memory.ml vox_lz4_spec_storage.ml";
 readonly_files += " vox_lz4_spec_parse.ml vox_lz4_spec_decode.ml";
 readonly_files += " vox_lz4_spec_decode_bytes.ml vox_lz4_spec_bytes.ml";
 readonly_files += " vox_lz4_heap_bytes.ml vox_lz4_match_proof.ml vox_lz4_spec_match.ml";
 readonly_files += " vox_lz4_spec_plan.ml vox_lz4_spec_token.ml";
 readonly_files += " vox_lz4_spec_wire.ml vox_lz4_spec_hashes.ml";
 readonly_files += " vox_lz4_spec_scan.ml vox_lz4_spec.ml vox_lz4_buffer.ml";
 readonly_files += " vox_lz4_packed.ml vox_lz4_encode_buffer.ml";
 readonly_files += " vox_lz4_packed_encode.ml vox_lz4_snapshot.ml";
 readonly_files += " vox_lz4_string_copy.mli vox_lz4_string_copy.ml";
 readonly_files += " vox_lz4_roundtrip.ml vox_lz4_general_match.ml";
 readonly_files += " vox_lz4_string_match.ml vox_lz4_general_plan.ml";
 readonly_files += " vox_lz4_general_encode.ml vox_lz4_general_wire.ml";
 readonly_files += " vox_lz4_decode_bytes_proof.ml";
 readonly_files += " vox_lz4_decode_bytes_roundtrip.ml vox_lz4_general_cost.ml";
 readonly_files += " vox_lz4_general_bridge.ml vox_lz4_general_sized.ml";
 readonly_files += " vox_lz4_string_encode.ml vox_lz4_general_roundtrip.ml";
 readonly_files += " vox_lz4_fast_plan_model.ml vox_lz4_mutable_scan.ml";
 readonly_files += " vox_lz4_string_scan.ml vox_lz4_fast_plan_roundtrip.ml";
 readonly_files += " vox_lz4_string_decode.ml vox_lz4_string_codec.ml";
 readonly_files += " vox_lz4_string_roundtrip.ml vox_lz4_forward_model.ml";
 readonly_files += " vox_lz4_streaming.ml vox_lz4_streaming_codec.ml";
 readonly_files += " vox_lz4_streaming_roundtrip.ml";
 readonly_files += " vox_lz4_fast_hints_reference.ml vox_lz4_checked_api.ml";
 readonly_files += " vox_lz4.mli vox_lz4.ml verified_atomic.mli";
 readonly_files += " verified_atomic.ml unique_cell.mli unique_cell.ml";
 readonly_files += " one_shot.mli one_shot.ml channel_buffer.mli";
 readonly_files += " channel_buffer.ml spin_lock.mli spin_lock.ml";
 readonly_files += " unique_lock.mli unique_lock.ml";
 readonly_files += " reference_lock.mli reference_lock.ml vox_control.mli";
 readonly_files += " vox_control.ml vox_table_model.ml";
 readonly_files += " vox_table_model_proofs.ml vox_table_bits.ml";
 readonly_files += " vox_table_probe.ml vox_table_wrap.ml vox_table_mask.ml";
 readonly_files += " vox_table_map.ml vox_table_invariant.ml";
 readonly_files += " vox_table_initial.ml vox_table_update_proofs.ml";
 readonly_files += " vox_table_insert_proofs.ml vox_table_migration_proofs.ml";
 readonly_files += " vox_table_read_proofs.ml vox_table_search_spec.ml";
 readonly_files += " vox_table_stop_proof.ml vox_table_storage.mli";
 readonly_files += " vox_table_storage.ml vox_table_search.ml";
 readonly_files += " vox_table_mutation.ml vox_table_coverage.ml";
 readonly_files += " vox_table_occupancy.ml vox_table_vacancy_progress.ml";
 readonly_files += " vox_table_vacancy.ml vox_table_insert.ml";
 readonly_files += " vox_table_migrate.ml vox_table_resize.ml";
 readonly_files += " vox_table_implementation.ml vox_table_bindings.ml";
 readonly_files += " vox_table_bindings_bridge.ml";
 readonly_files += " vox_verified_flat_hashtbl.mli";
 readonly_files += " vox_verified_flat_hashtbl.ml vox_traversal.mli";
 readonly_files += " vox_traversal.ml library_build_check.ml";
 {
   setup-ocamlc.opt-build-env;
   compile_only = "true";
   flags = "-extension refinement_types -principal -vox-library";
   all_modules = "vox_sequence.mli vox_sequence.ml vox_http_spec.mli";
   all_modules += " vox_http_spec.ml";
   ocamlc.opt;
   flags = "-extension refinement_types -vox-library";
   all_modules = "vox_http_model.ml vox_http.mli vox_http.ml";
   ocamlc.opt;
   flags = "-extension refinement_types -principal -vox-library";
   all_modules = "vox_int_sequence.mli vox_int_sequence.ml vox_iarray.mli";
   all_modules += " vox_iarray.ml vox_string_view.mli vox_string_view.ml";
   all_modules += " vox_sat_spec.mli vox_sat_spec.ml vox_sat_proof.mli";
   all_modules += " vox_sat_proof.ml vox_sat.mli vox_sat.ml";
   ocamlc.opt;
   flags = "-extension refinement_types -vox-library";
   all_modules = "vox_cdcl_total_proof.mli vox_cdcl_total_proof.ml";
   all_modules += " vox_cdcl_total.mli vox_cdcl_total.ml";
   ocamlc.opt;
   flags = "-extension refinement_types -principal -vox-library";
   all_modules = "vox_credits.mli vox_credits.ml vox_ordered_sequence.ml";
   all_modules += " vox_merge_proofs.ml vox_sort_cost.mli vox_sort_cost.ml vox_merge_sort.mli";
   all_modules += " vox_merge_sort.ml vox_lz4_model.ml vox_parallel.mli";
   all_modules += " vox_parallel.ml borrow.mli borrow.ml";
   all_modules += " borrow_iarray.mli borrow_iarray.ml pref.mli pref.ml";
   all_modules += " vox_pref_semantics.mli vox_pref_semantics.ml";
   all_modules += " ghost_pref.mli ghost_pref.ml vox_big_credits.mli";
   all_modules += " vox_big_credits.ml vox_ackermann.ml";
   all_modules += " vox_union_find_potential.ml vox_union_find_levels.ml";
   all_modules += " vox_union_find_path_cost.ml vox_union_find_model.ml";
   all_modules += " vox_union_find_forest.ml vox_union_find_rank.ml";
   all_modules += " vox_union_find_mass.ml vox_union_find_link.ml";
   all_modules += " vox_union_find_worker.ml vox_union_find_amortized.ml";
   all_modules += " vox_union_find_bank.ml vox_union_find_spec.ml";
   all_modules += " vox_union_find_events.mli vox_union_find_events.ml";
   all_modules += " vox_union_find.mli vox_union_find.ml";
   all_modules += " vox_union_find_complexity.ml vox_union_find_simple.mli";
   all_modules += " vox_union_find_simple.ml vox_partition.ml";
   all_modules += " vox_partition_classes.ml vox_partition_classes_proof.ml";
   all_modules += " vox_partition_classes_bridge.ml";
   all_modules += " vox_partition_transport_proof.ml";
   all_modules += " vox_partition_classes_group.ml";
   all_modules += " vox_union_find_partition_proof.ml vox_union_find_online.mli";
   all_modules += " vox_union_find_online.ml vox_connectivity.mli";
   all_modules += " vox_connectivity.ml vox_union_find_online_cost.ml";
   all_modules += " raw_memory.mli raw_memory.ml vox_lz4_spec_storage.ml";
   all_modules += " vox_lz4_spec_parse.ml vox_lz4_spec_decode.ml";
   all_modules += " vox_lz4_spec_decode_bytes.ml vox_lz4_spec_bytes.ml";
   all_modules += " vox_lz4_heap_bytes.ml vox_lz4_match_proof.ml vox_lz4_spec_match.ml";
   all_modules += " vox_lz4_spec_plan.ml vox_lz4_spec_token.ml";
   all_modules += " vox_lz4_spec_wire.ml vox_lz4_spec_hashes.ml";
   all_modules += " vox_lz4_spec_scan.ml vox_lz4_spec.ml vox_lz4_buffer.ml";
   all_modules += " vox_lz4_packed.ml vox_lz4_encode_buffer.ml";
   all_modules += " vox_lz4_packed_encode.ml vox_lz4_snapshot.ml";
   all_modules += " vox_lz4_string_copy.mli vox_lz4_string_copy.ml";
   all_modules += " vox_lz4_roundtrip.ml vox_lz4_general_match.ml";
   all_modules += " vox_lz4_string_match.ml vox_lz4_general_plan.ml";
   all_modules += " vox_lz4_general_encode.ml vox_lz4_general_wire.ml";
   all_modules += " vox_lz4_decode_bytes_proof.ml";
   all_modules += " vox_lz4_decode_bytes_roundtrip.ml";
   all_modules += " vox_lz4_general_cost.ml vox_lz4_general_bridge.ml";
   all_modules += " vox_lz4_general_sized.ml vox_lz4_string_encode.ml";
   all_modules += " vox_lz4_general_roundtrip.ml vox_lz4_fast_plan_model.ml";
   all_modules += " vox_lz4_mutable_scan.ml vox_lz4_string_scan.ml";
   all_modules += " vox_lz4_fast_plan_roundtrip.ml vox_lz4_string_decode.ml";
   all_modules += " vox_lz4_string_codec.ml vox_lz4_string_roundtrip.ml";
   all_modules += " vox_lz4_forward_model.ml vox_lz4_streaming.ml";
   all_modules += " vox_lz4_streaming_codec.ml";
   all_modules += " vox_lz4_streaming_roundtrip.ml";
   all_modules += " vox_lz4_fast_hints_reference.ml vox_lz4_checked_api.ml";
   all_modules += " vox_lz4.mli vox_lz4.ml verified_atomic.mli";
   all_modules += " verified_atomic.ml unique_cell.mli unique_cell.ml";
   all_modules += " one_shot.mli one_shot.ml channel_buffer.mli";
   all_modules += " channel_buffer.ml spin_lock.mli spin_lock.ml";
   all_modules += " unique_lock.mli unique_lock.ml";
   all_modules += " reference_lock.mli reference_lock.ml vox_control.mli";
   all_modules += " vox_control.ml";
   ocamlc.opt;
   flags = "-extension refinement_types -vox-library";
   all_modules = "vox_table_model.ml vox_table_model_proofs.ml";
   all_modules += " vox_table_bits.ml vox_table_probe.ml vox_table_wrap.ml";
   all_modules += " vox_table_mask.ml vox_table_map.ml";
   all_modules += " vox_table_invariant.ml vox_table_initial.ml";
   all_modules += " vox_table_update_proofs.ml vox_table_insert_proofs.ml";
   all_modules += " vox_table_migration_proofs.ml vox_table_read_proofs.ml";
   all_modules += " vox_table_search_spec.ml vox_table_stop_proof.ml";
   all_modules += " vox_table_storage.mli vox_table_storage.ml";
   all_modules += " vox_table_search.ml vox_table_mutation.ml";
   all_modules += " vox_table_coverage.ml vox_table_occupancy.ml";
   all_modules += " vox_table_vacancy_progress.ml vox_table_vacancy.ml";
   all_modules += " vox_table_insert.ml vox_table_migrate.ml";
   all_modules += " vox_table_resize.ml vox_table_implementation.ml";
   all_modules += " vox_table_bindings.ml vox_table_bindings_bridge.ml";
   all_modules += " vox_verified_flat_hashtbl.mli";
   all_modules += " vox_verified_flat_hashtbl.ml";
   ocamlc.opt;
   flags = "-extension refinement_types -principal -vox-library";
   all_modules = "vox_traversal.mli vox_traversal.ml";
   ocamlc.opt;
   check-ocamlc.opt-output;
   flags = "";
   compile_only = "false";
   all_modules = "library_build_check.ml";
   program = "${test_build_directory}/check.exe";
   ocamlc.opt;
   arguments = "${test_source_directory}";
   run;
   check-program-output;
 }
 {
   setup-ocamlopt.opt-build-env;
   compile_only = "true";
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "vox_sequence.mli vox_sequence.ml vox_http_spec.mli";
   all_modules += " vox_http_spec.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -smt-assume-verified -vox-library";
   all_modules = "vox_http_model.ml vox_http.mli vox_http.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "vox_int_sequence.mli vox_int_sequence.ml vox_iarray.mli";
   all_modules += " vox_iarray.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -O3 -vox-library";
   all_modules = "vox_string_view.mli vox_string_view.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "vox_sat_spec.mli vox_sat_spec.ml vox_sat_proof.mli";
   all_modules += " vox_sat_proof.ml vox_sat.mli vox_sat.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -smt-assume-verified -vox-library";
   all_modules = "vox_cdcl_total_proof.mli vox_cdcl_total_proof.ml";
   all_modules += " vox_cdcl_total.mli vox_cdcl_total.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "vox_credits.mli vox_credits.ml vox_ordered_sequence.ml";
   all_modules += " vox_merge_proofs.ml vox_sort_cost.mli vox_sort_cost.ml vox_merge_sort.mli";
   all_modules += " vox_merge_sort.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -O3 -vox-library";
   all_modules = "vox_lz4_model.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "vox_parallel.mli vox_parallel.ml borrow.mli borrow.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -O3 -vox-library";
   all_modules = "borrow_iarray.mli borrow_iarray.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "pref.mli pref.ml vox_pref_semantics.mli";
   all_modules += " vox_pref_semantics.ml ghost_pref.mli ghost_pref.ml";
   all_modules += " vox_big_credits.mli vox_big_credits.ml vox_ackermann.ml";
   all_modules += " vox_union_find_potential.ml vox_union_find_levels.ml";
   all_modules += " vox_union_find_path_cost.ml vox_union_find_model.ml";
   all_modules += " vox_union_find_forest.ml vox_union_find_rank.ml";
   all_modules += " vox_union_find_mass.ml vox_union_find_link.ml";
   all_modules += " vox_union_find_worker.ml vox_union_find_amortized.ml";
   all_modules += " vox_union_find_bank.ml vox_union_find_spec.ml";
   all_modules += " vox_union_find_events.mli vox_union_find_events.ml";
   all_modules += " vox_union_find.mli vox_union_find.ml";
   all_modules += " vox_union_find_complexity.ml vox_union_find_simple.mli";
   all_modules += " vox_union_find_simple.ml vox_partition.ml";
   all_modules += " vox_partition_classes.ml vox_partition_classes_proof.ml";
   all_modules += " vox_partition_classes_bridge.ml";
   all_modules += " vox_partition_transport_proof.ml";
   all_modules += " vox_partition_classes_group.ml";
   all_modules += " vox_union_find_partition_proof.ml vox_union_find_online.mli";
   all_modules += " vox_union_find_online.ml vox_connectivity.mli";
   all_modules += " vox_connectivity.ml vox_union_find_online_cost.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -O3 -vox-library";
   all_modules = "raw_memory.mli raw_memory.ml vox_lz4_spec_storage.ml";
   all_modules += " vox_lz4_spec_parse.ml vox_lz4_spec_decode.ml";
   all_modules += " vox_lz4_spec_decode_bytes.ml vox_lz4_spec_bytes.ml";
   all_modules += " vox_lz4_heap_bytes.ml vox_lz4_match_proof.ml vox_lz4_spec_match.ml";
   all_modules += " vox_lz4_spec_plan.ml vox_lz4_spec_token.ml";
   all_modules += " vox_lz4_spec_wire.ml vox_lz4_spec_hashes.ml";
   all_modules += " vox_lz4_spec_scan.ml vox_lz4_spec.ml vox_lz4_buffer.ml";
   all_modules += " vox_lz4_packed.ml vox_lz4_encode_buffer.ml";
   all_modules += " vox_lz4_packed_encode.ml vox_lz4_snapshot.ml";
   all_modules += " vox_lz4_string_copy.mli vox_lz4_string_copy.ml";
   all_modules += " vox_lz4_roundtrip.ml vox_lz4_general_match.ml";
   all_modules += " vox_lz4_string_match.ml vox_lz4_general_plan.ml";
   all_modules += " vox_lz4_general_encode.ml vox_lz4_general_wire.ml";
   all_modules += " vox_lz4_decode_bytes_proof.ml";
   all_modules += " vox_lz4_decode_bytes_roundtrip.ml";
   all_modules += " vox_lz4_general_cost.ml vox_lz4_general_bridge.ml";
   all_modules += " vox_lz4_general_sized.ml vox_lz4_string_encode.ml";
   all_modules += " vox_lz4_general_roundtrip.ml vox_lz4_fast_plan_model.ml";
   all_modules += " vox_lz4_mutable_scan.ml vox_lz4_string_scan.ml";
   all_modules += " vox_lz4_fast_plan_roundtrip.ml vox_lz4_string_decode.ml";
   all_modules += " vox_lz4_string_codec.ml vox_lz4_string_roundtrip.ml";
   all_modules += " vox_lz4_forward_model.ml vox_lz4_streaming.ml";
   all_modules += " vox_lz4_streaming_codec.ml";
   all_modules += " vox_lz4_streaming_roundtrip.ml";
   all_modules += " vox_lz4_fast_hints_reference.ml vox_lz4_checked_api.ml";
   all_modules += " vox_lz4.mli vox_lz4.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "verified_atomic.mli verified_atomic.ml unique_cell.mli";
   all_modules += " unique_cell.ml one_shot.mli one_shot.ml";
   all_modules += " channel_buffer.mli channel_buffer.ml spin_lock.mli";
   all_modules += " spin_lock.ml unique_lock.mli";
   all_modules += " unique_lock.ml reference_lock.mli reference_lock.ml";
   all_modules += " vox_control.mli vox_control.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -smt-assume-verified -O3 -vox-library";
   all_modules = "vox_table_model.ml vox_table_model_proofs.ml";
   all_modules += " vox_table_bits.ml vox_table_probe.ml vox_table_wrap.ml";
   all_modules += " vox_table_mask.ml vox_table_map.ml";
   all_modules += " vox_table_invariant.ml vox_table_initial.ml";
   all_modules += " vox_table_update_proofs.ml vox_table_insert_proofs.ml";
   all_modules += " vox_table_migration_proofs.ml vox_table_read_proofs.ml";
   all_modules += " vox_table_search_spec.ml vox_table_stop_proof.ml";
   all_modules += " vox_table_storage.mli vox_table_storage.ml";
   all_modules += " vox_table_search.ml vox_table_mutation.ml";
   all_modules += " vox_table_coverage.ml vox_table_occupancy.ml";
   all_modules += " vox_table_vacancy_progress.ml vox_table_vacancy.ml";
   all_modules += " vox_table_insert.ml vox_table_migrate.ml";
   all_modules += " vox_table_resize.ml vox_table_implementation.ml";
   all_modules += " vox_table_bindings.ml vox_table_bindings_bridge.ml";
   all_modules += " vox_verified_flat_hashtbl.mli";
   all_modules += " vox_verified_flat_hashtbl.ml";
   ocamlopt.opt;
   flags = "-extension refinement_types -principal -smt-assume-verified -vox-library";
   all_modules = "vox_traversal.mli vox_traversal.ml";
   ocamlopt.opt;
   check-ocamlopt.opt-output;
 }
*)

(* The Vox library as verification/library/build.sh builds it: every
   module in its order, verified by the bytecode compiler (-principal except
   for the modules build.sh exempts), then compiled natively with
   -smt-assume-verified (at -O3 for the modules build.sh names), plus
   Vox_traversal, which build.sh does not install. library_build_check.ml
   checks that the modules listed above are exactly build.sh's, in its
   order. *)
