(* TEST
 has-z3;
 source_directories = "${test_source_directory}/../../../verification/library";
 readonly_files = "vox_sequence.mli vox_sequence.ml vox_sat_spec.mli";
 readonly_files += " vox_sat_spec.ml vox_sat_proof.mli vox_sat_proof.ml";
 readonly_files += " vox_sat.mli vox_sat.ml";
 readonly_files += " vox_cdcl_total_proof.mli vox_cdcl_total_proof.ml";
 readonly_files += " vox_cdcl_total.mli vox_cdcl_total.ml";
 set lib = "";
 {
   setup-ocamlc.opt-build-env;
   lib = "${test_build_directory_prefix}/ocamlc.opt";
   flags = "-extension refinement_types -principal -vox-library";
   module = "vox_sequence.mli";
   ocamlc.opt;
   module = "vox_sequence.ml";
   ocamlc.opt;
   module = "vox_sat_spec.mli";
   ocamlc.opt;
   module = "vox_sat_spec.ml";
   ocamlc.opt;
   module = "vox_sat_proof.mli";
   ocamlc.opt;
   module = "vox_sat_proof.ml";
   ocamlc.opt;
   module = "vox_sat.mli";
   ocamlc.opt;
   compiler_output2 = "${lib}/vox_sat.lambda";
   flags += " -dlambda";
   module = "vox_sat.ml";
   ocamlc.opt;
   compiler_output2 = "${lib}/ocamlc.opt.output";
   flags = "-extension refinement_types -vox-library";
   module = "vox_cdcl_total_proof.mli";
   ocamlc.opt;
   module = "vox_cdcl_total_proof.ml";
   ocamlc.opt;
   module = "vox_cdcl_total.mli";
   ocamlc.opt;
   compiler_output2 = "${lib}/vox_cdcl_total.lambda";
   flags += " -dlambda";
   module = "vox_cdcl_total.ml";
   ocamlc.opt;
   compiler_output2 = "${lib}/ocamlc.opt.output";
   flags = "-extension refinement_types";
   src = "${lib}/vox_sat_spec.cmi ${lib}/vox_sat.cmi";
   src += " ${lib}/vox_cdcl_total.cmi";
   dst = "${test_build_directory_prefix}/ocamlc.opt.public/";
   compiler_directory_suffix = ".public";
   readonly_files = "sat_public.ml emitted_code.ml sat_boundary_check.ml";
   setup-ocamlc.opt-build-env;
   copy;
   unset module;
   compile_only = "false";
   binary_modules = "${lib}/vox_sequence ${lib}/vox_sat_spec";
   binary_modules += " ${lib}/vox_sat_proof ${lib}/vox_sat";
   binary_modules += " ${lib}/vox_cdcl_total_proof ${lib}/vox_cdcl_total";
   all_modules = "sat_public.ml";
   program = "${lib}.public/sat_public.exe";
   ocamlc.opt;
   check-ocamlc.opt-output;
   output = "${lib}.public/sat_public.output";
   reference = "${test_source_directory}/sat_boundary.client.reference";
   run;
   check-program-output;
   unset binary_modules;
   compiler_output2 = "${lib}.public/checker.output";
   flags = "";
   all_modules = "emitted_code.ml sat_boundary_check.ml";
   program = "${lib}.public/check.exe";
   ocamlc.opt;
   arguments = "${lib}";
   output = "${lib}.public/check.output";
   stdout = "${output}";
   stderr = "${output}";
   reference = "${test_source_directory}/sat_boundary.checks-byte.reference";
   run;
   check-program-output;
 }
 {
   setup-ocamlopt.opt-build-env;
   lib = "${test_build_directory_prefix}/ocamlopt.opt";
   flags = "-extension refinement_types -principal -vox-library";
   module = "vox_sequence.mli";
   ocamlopt.opt;
   module = "vox_sequence.ml";
   ocamlopt.opt;
   module = "vox_sat_spec.mli";
   ocamlopt.opt;
   module = "vox_sat_spec.ml";
   ocamlopt.opt;
   module = "vox_sat_proof.mli";
   ocamlopt.opt;
   module = "vox_sat_proof.ml";
   ocamlopt.opt;
   module = "vox_sat.mli";
   ocamlopt.opt;
   compiler_output2 = "${lib}/vox_sat.lambda";
   flags += " -dlambda";
   module = "vox_sat.ml";
   ocamlopt.opt;
   compiler_output2 = "${lib}/ocamlopt.opt.output";
   flags = "-extension refinement_types -vox-library";
   module = "vox_cdcl_total_proof.mli";
   ocamlopt.opt;
   module = "vox_cdcl_total_proof.ml";
   ocamlopt.opt;
   module = "vox_cdcl_total.mli";
   ocamlopt.opt;
   compiler_output2 = "${lib}/vox_cdcl_total.lambda";
   flags += " -dlambda";
   module = "vox_cdcl_total.ml";
   ocamlopt.opt;
   compiler_output2 = "${lib}/ocamlopt.opt.output";
   flags = "-extension refinement_types";
   src = "${lib}/vox_sat_spec.cmi ${lib}/vox_sat.cmi";
   src += " ${lib}/vox_cdcl_total.cmi";
   src += " ${lib}/vox_sequence.cmx ${lib}/vox_sat_spec.cmx";
   src += " ${lib}/vox_sat_proof.cmx ${lib}/vox_sat.cmx";
   src += " ${lib}/vox_cdcl_total_proof.cmx ${lib}/vox_cdcl_total.cmx";
   dst = "${test_build_directory_prefix}/ocamlopt.opt.public/";
   compiler_directory_suffix = ".public";
   readonly_files = "sat_public.ml emitted_code.ml sat_boundary_check.ml";
   setup-ocamlopt.opt-build-env;
   copy;
   unset module;
   compile_only = "false";
   binary_modules = "${lib}/vox_sequence ${lib}/vox_sat_spec";
   binary_modules += " ${lib}/vox_sat_proof ${lib}/vox_sat";
   binary_modules += " ${lib}/vox_cdcl_total_proof ${lib}/vox_cdcl_total";
   all_modules = "sat_public.ml";
   program = "${lib}.public/sat_public.exe";
   ocamlopt.opt;
   check-ocamlopt.opt-output;
   output = "${lib}.public/sat_public.output";
   reference = "${test_source_directory}/sat_boundary.client.reference";
   run;
   check-program-output;
   unset binary_modules;
   compiler_output2 = "${lib}.public/checker.output";
   flags = "";
   all_modules = "emitted_code.ml sat_boundary_check.ml";
   program = "${lib}.public/check.exe";
   ocamlopt.opt;
   arguments = "${lib} ${lib}/vox_cdcl_total_proof.o";
   output = "${lib}.public/check.output";
   stdout = "${output}";
   stderr = "${output}";
   reference = "${test_source_directory}/sat_boundary.checks-native.reference";
   run;
   check-program-output;
 }
*)

(* The SAT solver's boundary. With each compiler, the library is compiled
   as verification/library/build.sh does (-principal except for the total
   solver), the public client sat_public.ml is compiled with only the
   interfaces of Vox_sat_spec, Vox_sat and Vox_cdcl_total, linked and run,
   and sat_boundary_check.ml checks the Lambda of the two public modules (and, natively, the object of the total solver's proof module)
   for proof code. *)
