(* TEST
 has-z3;
 source_directories = "${test_source_directory}/../../../verification/library";
 set lib = "";
 readonly_files = "pref.mli pref.ml vox_pref_semantics.mli";
 readonly_files += " vox_pref_semantics.ml pref_list.mli pref_list.ml";
 readonly_files += " pref_tree.mli pref_tree.ml pref_ring.mli pref_ring.ml";
 readonly_files += " pref_ring_proofs.ml pref_ring_checks.ml";
 readonly_files += " pref_ring_alloc.ml pref_ring_splice_model.ml";
 readonly_files += " pref_ring_splice_setup.ml pref_ring_splice.mli";
 readonly_files += " pref_ring_splice.ml pref_ring_reverse_model.ml";
 readonly_files += " pref_ring_reverse_setup.ml pref_ring_reverse.mli";
 readonly_files += " pref_ring_reverse.ml pref_ring_general.mli";
 readonly_files += " pref_ring_general.ml pref_ring_splice_general.mli";
 readonly_files += " pref_ring_splice_general.ml emitted_code.ml";
 readonly_files += " structures_erasure_check.ml";
 setup-ocamlopt.opt-build-env;
 lib = "${test_build_directory_prefix}/ocamlopt.opt";
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref.mli.output";
 module = "pref.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref.lambda";
 module = "pref.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/vox_pref_semantics.mli.output";
 module = "vox_pref_semantics.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/vox_pref_semantics.lambda";
 module = "vox_pref_semantics.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref_list.mli.output";
 module = "pref_list.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_list.lambda";
 module = "pref_list.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref_tree.mli.output";
 module = "pref_tree.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_tree.lambda";
 module = "pref_tree.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref_ring.mli.output";
 module = "pref_ring.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring.lambda";
 module = "pref_ring.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_proofs.lambda";
 module = "pref_ring_proofs.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_checks.lambda";
 module = "pref_ring_checks.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_alloc.lambda";
 module = "pref_ring_alloc.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_splice_model.lambda";
 module = "pref_ring_splice_model.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_splice_setup.lambda";
 module = "pref_ring_splice_setup.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref_ring_splice.mli.output";
 module = "pref_ring_splice.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_splice.lambda";
 module = "pref_ring_splice.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_reverse_model.lambda";
 module = "pref_ring_reverse_model.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_reverse_setup.lambda";
 module = "pref_ring_reverse_setup.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref_ring_reverse.mli.output";
 module = "pref_ring_reverse.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_reverse.lambda";
 module = "pref_ring_reverse.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref_ring_general.mli.output";
 module = "pref_ring_general.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_general.lambda";
 module = "pref_ring_general.ml";
 ocamlopt.opt;
 flags = "-extension refinement_types";
 compiler_output2 = "${lib}/pref_ring_splice_general.mli.output";
 module = "pref_ring_splice_general.mli";
 ocamlopt.opt;
 flags = "-extension refinement_types -dlambda";
 compiler_output2 = "${lib}/pref_ring_splice_general.lambda";
 module = "pref_ring_splice_general.ml";
 ocamlopt.opt;
 unset module;
 flags = "";
 compiler_output2 = "${lib}/checker.output";
 all_modules = "emitted_code.ml structures_erasure_check.ml";
 program = "${lib}/check.exe";
 ocamlopt.opt;
 arguments = "${lib}";
 run;
 check-program-output;
*)

(* The linked lists, trees and rings: the named runtime functions of
   pref_list, pref_tree and the ring modules, compiled natively with
   -dlambda, and every function of the same module they call by name, call
   only runtime functions of a fixed list, no model function, lemma, [_def]
   equation or heap law, and use no model module; the observers do not
   split or join tokens (see structures_erasure_check.ml). *)
