#!/usr/bin/env bash
# Fail-closed promote gate for the corpus headline (board #69, DESIGN.md §11).
#
# Promoting a corpus-run JSON to the committed snapshot tests/corpus/baseline_summary.json
# (the source STATUS.md reads for the headline solved-rate) is a deliberate step — but
# nothing used to check the MEASURING BINARY's provenance, and a debug-oracle-on / dirty-
# tree measurement silently became the headline (the contamination this board fixes).
#
# This gate refuses to promote unless the run JSON's provenance stamp says the number came
# from a RELEASE-CONFIG binary on a CLEAN tree with ZERO soundness mismatches:
#   release_config == true   (assertions off AND debug oracles off AND tree not dirty)
#   mismatch_count  == 0      (no verdict contradicts a :status label)
# There is NO override flag — a wrong-config number can never be promoted. Fix the config
# and re-measure (see `make corpus-run-release`).
#
# Usage: tools/promote_baseline.sh [RUN_JSON]   (default ../logs/corpus-run.json)
set -uo pipefail

RUN_JSON="${1:-../logs/corpus-run.json}"
DEST="tests/corpus/baseline_summary.json"

[ -f "$RUN_JSON" ] || {
  echo "promote-baseline: no run JSON at '$RUN_JSON' (run 'make corpus-run-release' first)" >&2
  exit 2
}

# The JSON is machine-generated by corpus_run.sh with a fixed layout, so field extraction
# by sed is sufficient (and matches how that script hand-writes the JSON).
stamp=$(grep -o '"stamp": {[^}]*}' "$RUN_JSON")
release=$(printf '%s' "$stamp" | sed -n 's/.*"release_config": \([a-z]*\).*/\1/p')
mismatch=$(sed -n 's/.*"mismatch_count": \([0-9][0-9]*\).*/\1/p' "$RUN_JSON")
[ -n "$release" ] || release=absent
[ -n "$mismatch" ] || mismatch=absent

fail=0
if [ "$release" != true ]; then
  echo "promote-baseline: REFUSED — measurement is not release-config (release_config=$release)." >&2
  echo "  stamp: ${stamp:-<none: pre-#69 or malformed JSON>}" >&2
  fail=1
fi
if [ "$mismatch" != 0 ]; then
  echo "promote-baseline: REFUSED — mismatch_count=$mismatch (must be exactly 0)." >&2
  fail=1
fi
if [ "$fail" -ne 0 ]; then
  echo "promote-baseline: FAIL-CLOSED, no override. Build release + clean tree and re-measure:" >&2
  echo "    make corpus-run-release" >&2
  exit 1
fi

cp "$RUN_JSON" "$DEST"
echo "promote-baseline: OK — promoted '$RUN_JSON' -> $DEST"
echo "  $stamp"
echo "  (add/refresh the honesty '_note' by hand before committing, as before.)"
